//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                10   xyzw        0     NONE   float   xyz 
// TEXCOORD                11   xyzw        1     NONE   float   xyzw
// COLOR                    1   xyzw        2     NONE   float      w
// COLOR                    0   xyzw        3     NONE   float    y w
// TEXCOORD                 0   xyzw        4     NONE   float   xy  
// SV_Position              0   xyzw        5      POS   float   xyz 
// SV_IsFrontFace           0   x           6    FFACE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xyzw        4   TARGET   float   xyzw
// SV_Target                5   xyzw        5   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[33], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[211], immediateIndexed
      0x0000002C: dcl_constantbuffer CB2[20], immediateIndexed
      0x0000003C: dcl_constantbuffer CB3[1], immediateIndexed
      0x0000004C: dcl_constantbuffer CB4[6], immediateIndexed
      0x0000005C: dcl_constantbuffer CB5[42], immediateIndexed
      0x0000006C: dcl_constantbuffer CB6[20], immediateIndexed
      0x0000007C: dcl_sampler s0, mode_default
      0x00000088: dcl_sampler s1, mode_default
      0x00000094: dcl_sampler s2, mode_default
      0x000000A0: dcl_sampler s3, mode_default
      0x000000AC: dcl_resource_texture3d (uint,uint,uint,uint) t0
      0x000000BC: dcl_resource_texture3d (float,float,float,float) t1
      0x000000CC: dcl_resource_texture3d (float,float,float,float) t2
      0x000000DC: dcl_resource_texture3d (float,float,float,float) t3
      0x000000EC: dcl_resource_texture3d (float,float,float,float) t4
      0x000000FC: dcl_resource_texture3d (float,float,float,float) t5
      0x0000010C: dcl_resource_texture3d (float,float,float,float) t6
      0x0000011C: dcl_resource_texture3d (float,float,float,float) t7
      0x0000012C: dcl_resource_texture3d (float,float,float,float) t8
      0x0000013C: dcl_resource_texture3d (float,float,float,float) t9
      0x0000014C: dcl_resource_texture3d (float,float,float,float) t10
      0x0000015C: dcl_resource_texture2darray (float,float,float,float) t11
      0x0000016C: dcl_resource_buffer (uint,uint,uint,uint) t12
      0x0000017C: dcl_resource_texture2d (float,float,float,float) t13
      0x0000018C: dcl_resource_texture2d (float,float,float,float) t14
      0x0000019C: dcl_resource_texture2d (float,float,float,float) t15
      0x000001AC: dcl_resource_texture2d (float,float,float,float) t16
      0x000001BC: dcl_resource_texture2d (float,float,float,float) t17
      0x000001CC: dcl_input_ps linear centroid v0.xyz
      0x000001D8: dcl_input_ps linear centroid v1.xyzw
      0x000001E4: dcl_input_ps linear v2.w
      0x000001F0: dcl_input_ps linear v3.yw
      0x000001FC: dcl_input_ps linear v4.xy
      0x00000208: dcl_input_ps_siv linear noperspective v5.xyz, position
      0x00000218: dcl_input_ps_sgv constant v6.x, is_front_face
      0x00000228: dcl_output o0.xyzw
      0x00000234: dcl_output o1.xyzw
      0x00000240: dcl_output o2.xyzw
      0x0000024C: dcl_output o3.xyzw
      0x00000258: dcl_output o4.xyzw
      0x00000264: dcl_output o5.xyzw
      0x00000270: dcl_temps 19
   0  0x00000278: mul r0.xyz, v0.yzxy, v1.zxyz
   1  0x00000294: mad r0.xyz, v1.yzxy, v0.zxyz, -r0.xyzx
   2  0x000002BC: mul r0.xyz, r0.xyzx, v1.wwww
   3  0x000002D8: mul r1.xyzw, v5.yyyy, cb1[45].xyzw
   4  0x000002F8: mad r1.xyzw, v5.xxxx, cb1[44].xyzw, r1.xyzw
   5  0x00000320: mad r1.xyzw, v5.zzzz, cb1[46].xyzw, r1.xyzw
   6  0x00000348: add r1.xyzw, r1.xyzw, cb1[47].xyzw
   7  0x00000368: div r1.xyz, r1.xyzx, r1.wwww
   8  0x00000384: add r2.xyz, r1.xyzx, -cb1[71].xyzx
   9  0x000003A8: mul r0.w, cb1[148].w, cb2[9].w
  10  0x000003CC: movc r1.w, v6.x, l(1.000000), l(-1.000000)
  11  0x000003F0: mul r0.w, r0.w, r1.w
  12  0x0000040C: mul r3.xy, v4.xyxx, cb6[15].xxxx
  13  0x0000042C: sample_indexable(texture2d)(float,float,float,float) r3.zw, r3.xyxx, t14.zwxy, s0
  14  0x00000458: add r4.xy, r3.zwzz, r3.zwzz
  15  0x00000474: mad r3.zw, r3.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
  16  0x000004B0: dp2 r1.w, r3.zwzz, r3.zwzz
  17  0x000004CC: add r1.w, -r1.w, l(1.000000)
  18  0x000004EC: max r1.w, r1.w, l(0.000000)
  19  0x00000508: sqrt r4.z, r1.w
  20  0x0000051C: add r4.xyz, r4.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
  21  0x00000544: mad r4.xyz, cb6[15].yyyy, r4.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
  22  0x00000578: mul_sat r1.w, v2.w, l(4.000000)
  23  0x00000594: mov r5.x, v0.z
  24  0x000005A8: mov r5.y, r0.z
  25  0x000005BC: mov r5.z, v1.z
  26  0x000005D0: add r4.xyz, r4.xyzx, -r5.xyzx
  27  0x000005F0: mad r4.xyz, r1.wwww, r4.xyzx, r5.xyzx
  28  0x00000614: mad r5.xyz, r4.xyzx, r0.wwww, -r4.xyzx
  29  0x0000063C: mad r4.xyz, cb6[15].zzzz, r5.xyzx, r4.xyzx
  30  0x00000664: mad r4.xyz, r4.xyzx, cb1[145].wwww, cb1[145].xyzx
  31  0x00000690: dp3 r2.w, r4.xyzx, r4.xyzx
  32  0x000006AC: rsq r2.w, r2.w
  33  0x000006C0: mul r4.xyz, r2.wwww, r4.xyzx
  34  0x000006DC: mul r0.xyz, r0.xyzx, r4.yyyy
  35  0x000006F8: mad r0.xyz, r4.xxxx, v0.xyzx, r0.xyzx
  36  0x0000071C: mad r0.xyz, r4.zzzz, v1.xyzx, r0.xyzx
  37  0x00000740: dp3 r2.w, r0.xyzx, r0.xyzx
  38  0x0000075C: rsq r2.w, r2.w
  39  0x00000770: mul r0.xyz, r0.xyzx, r2.wwww
  40  0x0000078C: mul r4.xyz, r0.wwww, r0.xyzx
  41  0x000007A8: sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r3.xyxx, t15.xyzw, s0
  42  0x000007D4: mul r6.xyz, r5.xyzx, cb6[15].wwww
  43  0x000007F4: mul r6.xyz, r6.xyzx, cb6[2].xyzx
  44  0x00000814: mul r6.xyz, r5.wwww, r6.xyzx
  45  0x00000830: ld_indexable(texture2d)(float,float,float,float) r2.w, l(0, 0, 0, 0), t13.yzwx
  46  0x00000860: ne r3.z, r2.w, l(0.000000)
  47  0x0000087C: div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
  48  0x000008A4: add r2.w, r2.w, l(-1.000000)
  49  0x000008C0: mad r2.w, cb6[16].x, r2.w, l(1.000000)
  50  0x000008E8: movc r2.w, r3.z, r2.w, l(1.000000)
  51  0x0000090C: mad r6.xyz, r6.xyzx, r2.wwww, cb6[3].xyzx
  52  0x00000934: mul r7.xyz, r5.xyzx, cb6[6].xyzx
  53  0x00000954: ge r2.w, l(0.000000), cb1[210].w
  54  0x00000974: if_z r2.w
  55  0x00000980:   add r2.w, cb1[210].w, l(-1.000000)
  56  0x000009A0:   div r2.w, r2.w, cb1[210].w
  57  0x000009C0:   div r3.z, l(0.500000), cb1[210].w
  58  0x000009E0:   mad r8.xyz, r7.xzyx, r2.wwww, r3.zzzz
  59  0x00000A04:   mad r2.w, r8.y, cb1[210].w, l(-0.500000)
  60  0x00000A2C:   round_ni r3.z, r2.w
  61  0x00000A40:   add r2.w, r2.w, -r3.z
  62  0x00000A60:   add r3.z, r3.z, r8.x
  63  0x00000A7C:   div r8.y, r3.z, cb1[210].w
  64  0x00000A9C:   mov r8.w, l(0)
  65  0x00000AB0:   sample_indexable(texture2darray)(float,float,float,float) r9.xyz, r8.yzwy, t11.xyzw, s2
  66  0x00000ADC:   div r3.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[210].w
  67  0x00000B08:   add r8.x, r3.z, r8.y
  68  0x00000B24:   sample_indexable(texture2darray)(float,float,float,float) r8.xyz, r8.xzwx, t11.xyzw, s2
  69  0x00000B50:   add r8.xyz, -r9.xyzx, r8.xyzx
  70  0x00000B70:   mad r8.xyz, r2.wwww, r8.xyzx, r9.xyzx
  71  0x00000B94:   mad r5.xyz, -r5.xyzx, cb6[6].xyzx, r8.xyzx
  72  0x00000BC0:   mad r7.xyz, cb1[210].xyzx, r5.xyzx, r7.xyzx
  73  0x00000BE8: endif 
  74  0x00000BEC: sample_indexable(texture2d)(float,float,float,float) r3.xyz, r3.xyxx, t16.xyzw, s0
  75  0x00000C18: mul_sat r2.w, r3.x, l(2.500000)
  76  0x00000C34: add r5.xyz, r7.xyzx, -cb5[41].xyzx
  77  0x00000C58: mad_sat r5.xyz, r2.wwww, r5.xyzx, cb5[41].xyzx
  78  0x00000C80: mul r3.w, r3.x, cb6[16].z
  79  0x00000CA0: mad r3.w, cb5[3].x, r3.w, l(-0.037500)
  80  0x00000CC8: mad r3.w, r1.w, r3.w, l(0.037500)
  81  0x00000CEC: add r3.w, r3.w, -cb5[3].y
  82  0x00000D10: mad r3.w, r2.w, r3.w, cb5[3].y
  83  0x00000D38: add r3.x, r3.x, l(-0.550000)
  84  0x00000D54: mul_sat r3.x, r3.x, l(2.250000)
  85  0x00000D70: add r4.w, -r3.w, cb5[3].z
  86  0x00000D94: mad_sat r3.w, r3.x, r4.w, r3.w
  87  0x00000DB8: add r3.y, r3.y, cb6[16].w
  88  0x00000DD8: mad r3.y, r3.y, cb6[17].z, l(-0.800000)
  89  0x00000E00: mad r1.w, r1.w, r3.y, l(0.800000)
  90  0x00000E24: mad_sat r1.w, r3.x, l(-0.100000), r1.w
  91  0x00000E48: itof r8.xy, cb1[150].xyxx
  92  0x00000E60: mad r3.y, r8.y, l(0.000000), r8.x
  93  0x00000E84: mad_sat r3.y, r3.y, cb3[0].x, cb3[0].y
  94  0x00000EB0: min r3.y, r3.y, v3.y
  95  0x00000ECC: add r8.xy, v5.xyxx, -cb1[138].xyxx
  96  0x00000EF0: mul r8.xy, r8.xyxx, l(0.015625, 0.015625, 0.000000, 0.000000)
  97  0x00000F18: sample_b_indexable(texture2d)(float,float,float,float) r4.w, r8.xyxx, t17.yzwx, s3, cb1[150].w
  98  0x00000F50: add r3.y, r3.y, r4.w
  99  0x00000F6C: add r3.y, r3.y, l(-0.500000)
 100  0x00000F88: mul r7.xyz, r7.xyzx, cb6[14].xyzx
 101  0x00000FA8: mad r8.xyz, r7.xyzx, v2.wwww, -r7.xyzx
 102  0x00000FD0: mad r7.xyz, cb6[19].yyyy, r8.xyzx, r7.xyzx
 103  0x00000FF8: mul_sat r7.xyz, r2.wwww, r7.xyzx
 104  0x00001014: max r2.w, r2.w, l(0.000001)
 105  0x00001030: log r2.w, r2.w
 106  0x00001044: mul r2.w, r2.w, l(2.200000)
 107  0x00001060: exp r2.w, r2.w
 108  0x00001074: mad r3.x, r3.x, l(0.500000), l(1.000000)
 109  0x00001098: mul r2.w, r2.w, r3.x
 110  0x000010B4: lt r3.x, l(0.001000), |v3.w|
 111  0x000010D4: round_ni r8.xy, v5.xyxx
 112  0x000010E8: dp2 r4.w, r8.xyxx, l(347.834503, 3343.283691, 0.000000, 0.000000)
 113  0x00001110: sincos null, r4.w, r4.w
 114  0x00001128: mul r4.w, r4.w, l(1000.000000)
 115  0x00001144: frc r4.w, r4.w
 116  0x00001158: lt r5.w, v3.w, l(0.000000)
 117  0x00001174: add r6.w, v3.w, l(1.000000)
 118  0x00001190: lt r6.w, r4.w, r6.w
 119  0x000011AC: lt r4.w, v3.w, r4.w
 120  0x000011C8: movc r4.w, r5.w, r6.w, r4.w
 121  0x000011EC: ieq r4.w, r4.w, l(0)
 122  0x00001208: and r3.x, r3.x, r4.w
 123  0x00001224: discard_nz r3.x
 124  0x00001230: mad r3.x, r3.z, r3.y, l(-0.333300)
 125  0x00001254: lt r3.x, r3.x, l(0.000000)
 126  0x00001270: discard_nz r3.x
 127  0x0000127C: min r2.w, r2.w, l(1.000000)
 128  0x00001298: mad o2.z, r1.w, cb1[146].y, cb1[146].x
 129  0x000012C4: mad r3.xyz, r7.xyzx, cb1[143].wwww, cb1[143].xyzx
 130  0x000012F0: and r1.w, cb1[150].z, l(32)
 131  0x00001310: max r6.xyz, r6.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
 132  0x00001338: movc r6.xyz, r1.wwww, r6.xyzx, l(0,0,0,0)
 133  0x00001368: mov_sat o4.w, cb6[18].x
 134  0x00001380: mad r7.xyz, r2.xyzx, cb1[200].xyzx, cb1[201].xyzx
 135  0x000013AC: max r7.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
 136  0x000013D4: min r7.xyz, r7.xyzx, l(0.990000, 0.990000, 0.990000, 0.000000)
 137  0x000013FC: mul r7.xyz, r7.xyzx, cb1[202].xyzx
 138  0x0000141C: ftoi r8.xyz, r7.xyzx
 139  0x00001430: mov r8.w, l(0)
 140  0x00001444: ld_indexable(texture3d)(uint,uint,uint,uint) r8.xyzw, r8.xyzw, t0.xyzw
 141  0x00001468: utof r8.xyzw, r8.xyzw
 142  0x0000147C: add r1.w, cb1[202].w, l(1.000000)
 143  0x0000149C: div r7.xyz, r7.xyzx, r8.wwww
 144  0x000014B8: frc r7.xyz, r7.xyzx
 145  0x000014CC: mul r7.xyz, r7.xyzx, cb1[202].wwww
 146  0x000014EC: mad r7.xyz, r8.xyzx, r1.wwww, r7.xyzx
 147  0x00001510: add r7.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 148  0x00001538: mul r7.xyz, r7.xyzx, cb1[203].xyzx
 149  0x00001558: lt r1.w, l(0.000000), cb2[11].w
 150  0x00001578: if_nz r1.w
 151  0x00001584:   sample_l_indexable(texture3d)(float,float,float,float) r1.w, r7.xyzx, t10.yzwx, s1, l(0.000000)
 152  0x000015B8: else 
 153  0x000015BC:   lt r4.w, l(0.000000), cb2[11].z
 154  0x000015DC:   movc r1.w, r4.w, cb4[5].x, l(1.000000)
 155  0x00001604: endif 
 156  0x00001608: mov_sat r8.xyz, r3.xyzx
 157  0x0000161C: sqrt o4.xyz, r8.xyzx
 158  0x00001630: mul r4.w, r3.w, cb1[144].w
 159  0x00001650: mad r8.xyz, r5.xyzx, cb1[143].wwww, cb1[143].xyzx
 160  0x0000167C: mad r9.xyz, r4.wwww, l(0.080000, 0.080000, 0.080000, 0.000000), cb1[144].xyzx
 161  0x000016B0: dp3 r4.w, r9.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
 162  0x000016D8: mad r10.xyz, r4.wwww, l(2.040400, -4.795100, 2.755200, 0.000000), l(-0.332400, 0.641700, 0.690300, 0.000000)
 163  0x00001714: mad r4.w, r2.w, r10.x, r10.y
 164  0x00001738: mad r4.w, r4.w, r2.w, r10.z
 165  0x0000175C: mul r4.w, r2.w, r4.w
 166  0x00001778: max r4.w, r2.w, r4.w
 167  0x00001794: lt r5.w, l(0.000000), cb2[19].w
 168  0x000017B4: if_nz r5.w
 169  0x000017C0:   add r3.xyz, r3.xyzx, r8.xyzx
 170  0x000017DC:   and r10.xy, cb1[150].zzzz, l(4, 8, 0, 0)
 171  0x00001808:   sample_l_indexable(texture3d)(float,float,float,float) r11.xyz, r7.xyzx, t1.xyzw, s1, l(0.000000)
 172  0x0000183C:   sample_l_indexable(texture3d)(float,float,float,float) r12.xyz, r7.xyzx, t2.xyzw, s1, l(0.000000)
 173  0x00001870:   mad r12.xyz, r12.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
 174  0x000018AC:   sample_l_indexable(texture3d)(float,float,float,float) r13.xyz, r7.xyzx, t3.xyzw, s1, l(0.000000)
 175  0x000018E0:   mad r13.xyz, r13.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
 176  0x0000191C:   sample_l_indexable(texture3d)(float,float,float,float) r14.xyz, r7.xyzx, t4.xyzw, s1, l(0.000000)
 177  0x00001950:   mad r14.xyz, r14.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
 178  0x0000198C:   mul r12.xyz, r11.xxxx, r12.xyzx
 179  0x000019A8:   mul r12.yzw, r12.xxyz, l(0.000000, 1.732051, 1.732051, 1.732051)
 180  0x000019D0:   mul r13.xyz, r11.yyyy, r13.xyzx
 181  0x000019EC:   mul r13.yzw, r13.xxyz, l(0.000000, 1.732051, 1.732051, 1.732051)
 182  0x00001A14:   mul r14.xyz, r11.zzzz, r14.xyzx
 183  0x00001A30:   mul r14.yzw, r14.xxyz, l(0.000000, 1.732051, 1.732051, 1.732051)
 184  0x00001A58:   mov r12.x, r11.x
 185  0x00001A6C:   movc r12.xyzw, r10.xxxx, r12.xyzw, l(0,0,0,0)
 186  0x00001A9C:   mov r13.x, r11.y
 187  0x00001AB0:   movc r13.xyzw, r10.xxxx, r13.xyzw, l(0,0,0,0)
 188  0x00001AE0:   mov r14.x, r11.z
 189  0x00001AF4:   movc r11.xyzw, r10.xxxx, r14.xyzw, l(0,0,0,0)
 190  0x00001B24:   sample_l_indexable(texture3d)(float,float,float,float) r10.xzw, r7.xyzx, t5.xwyz, s1, l(0.000000)
 191  0x00001B58:   sample_l_indexable(texture3d)(float,float,float,float) r14.xyz, r7.xyzx, t6.xyzw, s1, l(0.000000)
 192  0x00001B8C:   mad r14.xyz, r14.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
 193  0x00001BC8:   sample_l_indexable(texture3d)(float,float,float,float) r15.xyz, r7.xyzx, t7.xyzw, s1, l(0.000000)
 194  0x00001BFC:   mad r15.xyz, r15.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
 195  0x00001C38:   sample_l_indexable(texture3d)(float,float,float,float) r16.xyz, r7.xyzx, t8.xyzw, s1, l(0.000000)
 196  0x00001C6C:   mad r16.xyz, r16.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
 197  0x00001CA8:   mul r14.xyz, r10.xxxx, r14.xyzx
 198  0x00001CC4:   mul r14.yzw, r14.xxyz, cb1[153].xxxx
 199  0x00001CE4:   mul r15.xyz, r10.zzzz, r15.xyzx
 200  0x00001D00:   mul r15.yzw, r15.xxyz, cb1[153].yyyy
 201  0x00001D20:   mul r16.xyz, r10.wwww, r16.xyzx
 202  0x00001D3C:   mul r16.yzw, r16.xxyz, cb1[153].zzzz
 203  0x00001D5C:   mov r14.x, r10.x
 204  0x00001D70:   mov r17.x, cb1[153].x
 205  0x00001D88:   mov r17.yzw, l(0,1.732051,1.732051,1.732051)
 206  0x00001DA8:   mad r14.xyzw, r14.xyzw, r17.xyzw, r12.xyzw
 207  0x00001DCC:   mov r15.x, r10.z
 208  0x00001DE0:   mov r17.x, cb1[153].y
 209  0x00001DF8:   mov r17.yzw, l(0,1.732051,1.732051,1.732051)
 210  0x00001E18:   mad r15.xyzw, r15.xyzw, r17.xyzw, r13.xyzw
 211  0x00001E3C:   mov r16.x, r10.w
 212  0x00001E50:   mov r17.x, cb1[153].z
 213  0x00001E68:   mov r17.yzw, l(0,1.732051,1.732051,1.732051)
 214  0x00001E88:   mad r16.xyzw, r16.xyzw, r17.xyzw, r11.xyzw
 215  0x00001EAC:   movc r12.xyzw, r10.yyyy, r14.xyzw, r12.xyzw
 216  0x00001ED0:   movc r13.xyzw, r10.yyyy, r15.xyzw, r13.xyzw
 217  0x00001EF4:   movc r10.xyzw, r10.yyyy, r16.xyzw, r11.xyzw
 218  0x00001F18:   mul r11.yzw, r4.yyzx, l(0.000000, -1.023328, 1.023328, -1.023328)
 219  0x00001F40:   mov r11.x, l(0.886228)
 220  0x00001F54:   dp4 r12.x, r12.xyzw, r11.xyzw
 221  0x00001F70:   dp4 r12.y, r13.xyzw, r11.xyzw
 222  0x00001F8C:   dp4 r12.z, r10.xyzw, r11.xyzw
 223  0x00001FA8:   max r10.xyz, r12.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
 224  0x00001FD0:   mul r10.xyz, r10.xyzx, cb1[165].xyzx
 225  0x00001FF0:   mul r11.xyz, r10.xyzx, l(0.318310, 0.318310, 0.318310, 0.000000)
 226  0x00002018:   if_nz cb0[32].w
 227  0x00002028:     lt r5.w, l(0.000000), cb1[174].y
 228  0x00002048:     if_nz r5.w
 229  0x00002054:       sample_l_indexable(texture3d)(float,float,float,float) r7.xyzw, r7.xyzx, t9.xyzw, s1, l(0.000000)
 230  0x00002088:       mad r7.xyz, r7.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
 231  0x000020C4:       dp3 r5.w, r7.xyzx, r7.xyzx
 232  0x000020E0:       rsq r5.w, r5.w
 233  0x000020F4:       mul r7.xyz, r5.wwww, r7.xyzx
 234  0x00002110:       dp3 r5.w, r4.xyzx, r7.xyzx
 235  0x0000212C:       div r5.w, r5.w, cb1[204].x
 236  0x0000214C:       add_sat r5.w, r5.w, cb1[204].z
 237  0x0000216C:       add r6.w, r5.w, l(-1.000000)
 238  0x00002188:       mad r6.w, cb1[204].y, r6.w, l(1.000000)
 239  0x000021B0:       mul r12.x, r6.w, r7.w
 240  0x000021CC:       add r13.xyz, r7.xyzx, r7.xyzx
 241  0x000021E8:       mad r7.xyz, r5.wwww, r13.xyzx, -r7.xyzx
 242  0x00002210:       mad r5.w, -r7.w, r6.w, l(1.000000)
 243  0x00002238:       mad r5.w, -r5.w, r5.w, l(1.000000)
 244  0x00002260:       mad r0.xyz, r0.xyzx, r0.wwww, -r7.xyzx
 245  0x00002288:       mad r0.xyz, r5.wwww, r0.xyzx, r7.xyzx
 246  0x000022AC:       dp3_sat r6.w, r7.xyzx, r4.xyzx
 247  0x000022C8:       add r7.x, -r6.w, l(1.000000)
 248  0x000022E8:       mad r12.y, r5.w, r7.x, r6.w
 249  0x0000230C:     else 
 250  0x00002310:       mov r0.xyz, r4.xyzx
 251  0x00002324:       mov r12.xy, l(1.000000,1.000000,0,0)
 252  0x00002344:     endif 
 253  0x00002348:     and r5.w, cb1[150].z, l(16)
 254  0x00002368:     ld_indexable(buffer)(uint,uint,uint,uint) r6.w, l(12, 12, 12, 12), t12.yzwx
 255  0x00002398:     ld_indexable(buffer)(uint,uint,uint,uint) r7.y, l(13, 13, 13, 13), t12.yxzw
 256  0x000023C8:     ld_indexable(buffer)(uint,uint,uint,uint) r7.z, l(14, 14, 14, 14), t12.yzxw
 257  0x000023F8:     ld_indexable(buffer)(uint,uint,uint,uint) r7.w, l(15, 15, 15, 15), t12.yzwx
 258  0x00002428:     ld_indexable(buffer)(uint,uint,uint,uint) r8.w, l(16, 16, 16, 16), t12.yzwx
 259  0x00002458:     ld_indexable(buffer)(uint,uint,uint,uint) r13.y, l(17, 17, 17, 17), t12.yxzw
 260  0x00002488:     ld_indexable(buffer)(uint,uint,uint,uint) r13.z, l(18, 18, 18, 18), t12.yzxw
 261  0x000024B8:     ld_indexable(buffer)(uint,uint,uint,uint) r13.w, l(19, 19, 19, 19), t12.yzwx
 262  0x000024E8:     ld_indexable(buffer)(uint,uint,uint,uint) r9.w, l(20, 20, 20, 20), t12.yzwx
 263  0x00002518:     ld_indexable(buffer)(uint,uint,uint,uint) r14.y, l(21, 21, 21, 21), t12.yxzw
 264  0x00002548:     ld_indexable(buffer)(uint,uint,uint,uint) r14.z, l(22, 22, 22, 22), t12.yzxw
 265  0x00002578:     ld_indexable(buffer)(uint,uint,uint,uint) r14.w, l(23, 23, 23, 23), t12.yzwx
 266  0x000025A8:     ld_indexable(buffer)(uint,uint,uint,uint) r15.x, l(24, 24, 24, 24), t12.xyzw
 267  0x000025D8:     ld_indexable(buffer)(uint,uint,uint,uint) r15.y, l(25, 25, 25, 25), t12.yxzw
 268  0x00002608:     ld_indexable(buffer)(uint,uint,uint,uint) r15.z, l(26, 26, 26, 26), t12.yzxw
 269  0x00002638:     ld_indexable(buffer)(uint,uint,uint,uint) r15.w, l(27, 27, 27, 27), t12.yzwx
 270  0x00002668:     ld_indexable(buffer)(uint,uint,uint,uint) r16.x, l(28, 28, 28, 28), t12.xyzw
 271  0x00002698:     ld_indexable(buffer)(uint,uint,uint,uint) r16.y, l(29, 29, 29, 29), t12.yxzw
 272  0x000026C8:     ld_indexable(buffer)(uint,uint,uint,uint) r16.z, l(30, 30, 30, 30), t12.yzxw
 273  0x000026F8:     ld_indexable(buffer)(uint,uint,uint,uint) r16.w, l(31, 31, 31, 31), t12.yzwx
 274  0x00002728:     ld_indexable(buffer)(uint,uint,uint,uint) r17.x, l(32, 32, 32, 32), t12.xyzw
 275  0x00002758:     ld_indexable(buffer)(uint,uint,uint,uint) r17.y, l(33, 33, 33, 33), t12.yxzw
 276  0x00002788:     ld_indexable(buffer)(uint,uint,uint,uint) r17.z, l(34, 34, 34, 34), t12.yzxw
 277  0x000027B8:     ld_indexable(buffer)(uint,uint,uint,uint) r17.w, l(35, 35, 35, 35), t12.yzwx
 278  0x000027E8:     ld_indexable(buffer)(uint,uint,uint,uint) r18.x, l(36, 36, 36, 36), t12.xyzw
 279  0x00002818:     ld_indexable(buffer)(uint,uint,uint,uint) r18.y, l(37, 37, 37, 37), t12.yxzw
 280  0x00002848:     ld_indexable(buffer)(uint,uint,uint,uint) r18.z, l(38, 38, 38, 38), t12.yzxw
 281  0x00002878:     mad r7.x, r15.z, l(-0.333333), r6.w
 282  0x0000289C:     mad r13.x, r16.z, l(-0.333333), r8.w
 283  0x000028C0:     mad r14.x, r17.z, l(-0.333333), r9.w
 284  0x000028E4:     mov r0.w, l(1.000000)
 285  0x000028F8:     dp4 r7.x, r7.wyzx, r0.xyzw
 286  0x00002914:     dp4 r7.y, r13.wyzx, r0.xyzw
 287  0x00002930:     dp4 r7.z, r14.wyzx, r0.xyzw
 288  0x0000294C:     mul r13.xyzw, r0.yzzx, r0.xyzz
 289  0x00002968:     dp4 r14.x, r15.xyzw, r13.xyzw
 290  0x00002984:     dp4 r14.y, r16.xyzw, r13.xyzw
 291  0x000029A0:     dp4 r14.z, r17.xyzw, r13.xyzw
 292  0x000029BC:     mul r0.y, r0.y, r0.y
 293  0x000029D8:     mad r0.x, r0.x, r0.x, -r0.y
 294  0x00002A00:     add r0.yzw, r7.xxyz, r14.xxyz
 295  0x00002A1C:     mad r0.xyz, r18.xyzx, r0.xxxx, r0.yzwy
 296  0x00002A40:     max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
 297  0x00002A68:     mul r0.xyz, r0.xyzx, cb1[174].zzzz
 298  0x00002A88:     mul r0.w, r12.y, r12.x
 299  0x00002AA4:     mul r0.xyz, r0.wwww, r0.xyzx
 300  0x00002AC0:     movc r0.xyz, r5.wwww, r0.xyzx, l(0,0,0,0)
 301  0x00002AF0:     mad r11.xyz, r10.xyzx, l(0.318310, 0.318310, 0.318310, 0.000000), r0.xyzx
 302  0x00002B20:   endif 
 303  0x00002B24:   dp3 r0.x, r1.xyzx, r1.xyzx
 304  0x00002B40:   sqrt r0.x, r0.x
 305  0x00002B54:   mad_sat r0.x, r0.x, cb2[13].x, cb2[13].y
 306  0x00002B80:   mad r0.y, r0.x, l(-2.000000), l(3.000000)
 307  0x00002BA4:   mul r0.x, r0.x, r0.x
 308  0x00002BC0:   mul r0.x, r0.x, r0.y
 309  0x00002BDC:   min r0.x, r0.x, l(1.000000)
 310  0x00002BF8:   mad r0.x, r0.x, cb2[13].z, cb2[13].w
 311  0x00002C24:   mul r0.xyz, r0.xxxx, r11.xyzx
 312  0x00002C40:   dp3 r0.w, r0.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
 313  0x00002C68:   mul r0.xyzw, r0.xyzw, cb2[19].wwww
 314  0x00002C88:   mul r0.xyz, r3.xyzx, r0.xyzx
 315  0x00002CA4:   mad r1.xyz, r5.xyzx, l(2.040400, 2.040400, 2.040400, 0.000000), l(-0.332400, -0.332400, -0.332400, 0.000000)
 316  0x00002CE0:   mad r3.xyz, r5.xyzx, l(-4.795100, -4.795100, -4.795100, 0.000000), l(0.641700, 0.641700, 0.641700, 0.000000)
 317  0x00002D1C:   mad r7.xyz, r5.xyzx, l(2.755200, 2.755200, 2.755200, 0.000000), l(0.690300, 0.690300, 0.690300, 0.000000)
 318  0x00002D58:   mad r1.xyz, r2.wwww, r1.xyzx, r3.xyzx
 319  0x00002D7C:   mad r1.xyz, r1.xyzx, r2.wwww, r7.xyzx
 320  0x00002DA0:   mul r1.xyz, r2.wwww, r1.xyzx
 321  0x00002DBC:   max r1.xyz, r1.xyzx, r2.wwww
 322  0x00002DD8:   mul r0.xyz, r0.xyzx, r1.xyzx
 323  0x00002DF4: else 
 324  0x00002DF8:   mov r0.xyzw, l(0,0,0,0)
 325  0x00002E18: endif 
 326  0x00002E1C: mad r1.xyz, r9.xyzx, l(0.450000, 0.450000, 0.450000, 0.000000), r8.xyzx
 327  0x00002E4C: lt r2.w, l(0.000000), cb1[147].z
 328  0x00002E6C: if_nz r2.w
 329  0x00002E78:   add r3.xyz, r2.xyzx, -cb2[8].xyzx
 330  0x00002E9C:   add r7.xyz, cb2[9].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 331  0x00002EC8:   lt r3.xyz, r7.xyzx, |r3.xyzx|
 332  0x00002EE8:   or r2.w, r3.y, r3.x
 333  0x00002F04:   or r2.w, r3.z, r2.w
 334  0x00002F20:   dp3 r2.x, r2.xyzx, l(0.577000, 0.577000, 0.577000, 0.000000)
 335  0x00002F48:   mul r2.x, r2.x, l(0.002000)
 336  0x00002F64:   frc r2.x, r2.x
 337  0x00002F78:   lt r2.x, l(0.500000), r2.x
 338  0x00002F94:   movc r2.xyz, r2.xxxx, l(0,1.000000,1.000000,0), l(1.000000,1.000000,0,0)
 339  0x00002FD0:   movc r6.xyz, r2.wwww, r2.xyzx, r6.xyzx
 340  0x00002FF4: endif 
 341  0x00002FF8: mad r0.xyz, cb1[152].yyyy, r1.xyzx, r0.xyzx
 342  0x00003020: add o0.xyz, r6.xyzx, r0.xyzx
 343  0x0000303C: mul r0.xyz, v5.xyxx, l(0.007812, 0.007812, 0.007812, 0.000000)
 344  0x00003064: frc r0.xyz, r0.xyzx
 345  0x00003078: mad r0.xyz, r0.xyzx, l(128.000000, 128.000000, 128.000000, 0.000000), l(-64.340622, -72.465622, -64.340622, 0.000000)
 346  0x000030B4: mul r0.xyz, r0.xyyx, r0.xyzx
 347  0x000030D0: dp3 r0.x, r0.xyzx, l(20.390625, 60.703125, 2.428121, 0.000000)
 348  0x000030F8: frc r0.x, r0.x
 349  0x0000310C: add r0.x, r0.x, l(-0.500000)
 350  0x00003128: mad o1.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
 351  0x00003164: mad r0.y, r0.w, r4.w, l(0.003906)
 352  0x00003188: log r0.y, r0.y
 353  0x0000319C: mad r0.y, r0.y, l(0.062500), l(0.500000)
 354  0x000031C0: mad o3.w, r0.x, l(0.003922), r0.y
 355  0x000031E4: mov o0.w, l(0)
 356  0x000031F8: mov o1.w, cb2[11].y
 357  0x00003210: mov o2.xw, l(0,0,0,0.509804)
 358  0x00003230: mov o2.y, r3.w
 359  0x00003244: mov o3.xyz, r5.xyzx
 360  0x00003258: mov o5.x, r1.w
 361  0x0000326C: mov o5.yzw, l(0,1.000000,1.000000,1.000000)
 362  0x0000328C: ret 
// Approximately 0 instruction slots used
