//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                10   xyzw        0     NONE   float       
// TEXCOORD                11   xyzw        1     NONE   float       
// COLOR                    1   xyzw        2     NONE   float       
// COLOR                    0   xyzw        3     NONE   float    y w
// TEXCOORD                 0   xyzw        4     NONE   float   xy  
// GBX_SHADOW_DEPTH         0   x           5     NONE   float   x   
// GBX_PIXEL_POSITION       0    yzw        5     NONE   float       
// SV_Position              0   xyzw        6      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_DEPTH                 0    N/A   oDepth    DEPTH   float    YES
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[13], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[151], immediateIndexed
      0x0000002C: dcl_constantbuffer CB2[1], immediateIndexed
      0x0000003C: dcl_constantbuffer CB3[16], immediateIndexed
      0x0000004C: dcl_sampler s0, mode_default
      0x00000058: dcl_sampler s1, mode_default
      0x00000064: dcl_resource_texture2d (float,float,float,float) t0
      0x00000074: dcl_resource_texture2d (float,float,float,float) t1
      0x00000084: dcl_input_ps linear v3.yw
      0x00000090: dcl_input_ps linear v4.xy
      0x0000009C: dcl_input_ps linear v5.x
      0x000000A8: dcl_input_ps_siv linear noperspective v6.xy, position
      0x000000B8: dcl_output o0.xyzw
      0x000000C4: dcl_output oDepth
      0x000000CC: dcl_temps 1
   0  0x000000D4: round_ni r0.xy, v6.xyxx
   1  0x000000E8: dp2 r0.x, r0.xyxx, l(347.834503, 3343.283691, 0.000000, 0.000000)
   2  0x00000110: sincos null, r0.x, r0.x
   3  0x00000128: mul r0.x, r0.x, l(1000.000000)
   4  0x00000144: frc r0.x, r0.x
   5  0x00000158: add r0.y, v3.w, l(1.000000)
   6  0x00000174: lt r0.y, r0.x, r0.y
   7  0x00000190: lt r0.x, v3.w, r0.x
   8  0x000001AC: lt r0.z, v3.w, l(0.000000)
   9  0x000001C8: movc r0.x, r0.z, r0.y, r0.x
  10  0x000001EC: ieq r0.x, r0.x, l(0)
  11  0x00000208: lt r0.y, l(0.001000), |v3.w|
  12  0x00000228: and r0.x, r0.y, r0.x
  13  0x00000244: discard_nz r0.x
  14  0x00000250: itof r0.xy, cb1[150].xyxx
  15  0x00000268: mad r0.x, r0.y, l(0.000000), r0.x
  16  0x0000028C: mad_sat r0.x, r0.x, cb2[0].x, cb2[0].y
  17  0x000002B8: min r0.x, r0.x, v3.y
  18  0x000002D4: add r0.yz, v6.xxyx, -cb1[138].xxyx
  19  0x000002F8: mul r0.yz, r0.yyzy, l(0.000000, 0.015625, 0.015625, 0.000000)
  20  0x00000320: sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t1.yxzw, s1, cb1[150].w
  21  0x00000358: add r0.x, r0.y, r0.x
  22  0x00000374: add r0.x, r0.x, l(-0.500000)
  23  0x00000390: mul r0.yz, v4.xxyx, cb3[15].xxxx
  24  0x000003B0: sample_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t0.xzyw, s0
  25  0x000003DC: mad r0.x, r0.y, r0.x, l(-0.333300)
  26  0x00000400: lt r0.x, r0.x, l(0.000000)
  27  0x0000041C: discard_nz r0.x
  28  0x00000428: mov o0.xyzw, l(0,0,0,0)
  29  0x00000448: mad_sat oDepth, v5.x, cb0[12].w, cb0[12].z
  30  0x00000470: ret 
// Approximately 0 instruction slots used
