//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      0x00000000: cs_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[16], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[124], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_resource_texture2d (float,float,float,float) t0
      0x00000048: dcl_resource_buffer (float,float,float,float) t1
      0x00000058: dcl_resource_buffer (float,float,float,float) t2
      0x00000068: dcl_resource_texture2d (uint,uint,uint,uint) t3
      0x00000078: dcl_uav_typed_texture2d (float,float,float,float) u0
      0x00000088: dcl_uav_typed_buffer (uint,uint,uint,uint) u1
      0x00000098: dcl_input vThreadGroupID.xy
      0x000000A0: dcl_input vThreadIDInGroup.xy
      0x000000A8: dcl_input vThreadID.xyz
      0x000000B0: dcl_temps 13
      0x000000B8: dcl_tgsm_raw g0, 4
      0x000000C8: dcl_tgsm_raw g1, 4
      0x000000D8: dcl_tgsm_structured g2, 4, 1024
      0x000000EC: dcl_tgsm_raw g3, 4
      0x000000FC: dcl_tgsm_raw g4, 4
      0x0000010C: dcl_tgsm_raw g5, 4
      0x0000011C: dcl_tgsm_raw g6, 4
      0x0000012C: dcl_thread_group 8, 8, 1
   0  0x0000013C: imad r0.x, vThreadIDInGroup.y, l(8), vThreadIDInGroup.x
   1  0x00000158: imad r0.yz, vThreadID.xxyx, cb0[14].yyyy, cb0[12].xxyx
   2  0x00000180: utof r0.yz, r0.yyzy
   3  0x00000194: add r0.yz, r0.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
   4  0x000001BC: mul r1.xy, r0.yzyy, cb1[123].zwzz
   5  0x000001DC: sample_l_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t0.yzwx, s0, l(0.000000)
   6  0x00000210: mad r1.x, r0.w, cb1[57].x, cb1[57].y
   7  0x0000023C: mad r0.w, r0.w, cb1[57].z, -cb1[57].w
   8  0x0000026C: div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
   9  0x00000294: add r1.y, r0.w, r1.x
  10  0x000002B0: if_z r0.x
  11  0x000002BC:   store_raw g3.x, l(0), l(340282346638528859811704183484516925440.000000)
  12  0x000002D8:   store_raw g4.x, l(0), l(0)
  13  0x000002F4:   store_raw g5.x, l(0), l(340282346638528859811704183484516925440.000000)
  14  0x00000310:   store_raw g6.x, l(0), l(0)
  15  0x0000032C:   store_raw g0.x, l(0), l(0)
  16  0x00000348:   store_raw g1.x, l(0), l(0)
  17  0x00000364: endif 
  18  0x00000368: sync_g_t
  19  0x0000036C: lt r0.w, r1.y, l(20000.000000)
  20  0x00000388: if_nz r0.w
  21  0x00000394:   atomic_umin g3, l(0), r1.y
  22  0x000003B0:   atomic_umax g4, l(0), r1.y
  23  0x000003CC: endif 
  24  0x000003D0: sync_g_t
  25  0x000003D4: ld_raw r2.z, l(0), g3.xxxx
  26  0x000003F0: ld_raw r3.z, l(0), g4.xxxx
  27  0x0000040C: if_nz r0.w
  28  0x00000418:   add r0.w, r2.z, r3.z
  29  0x00000434:   mul r0.w, r0.w, l(0.500000)
  30  0x00000450:   ge r2.w, r1.y, r0.w
  31  0x0000046C:   if_nz r2.w
  32  0x00000478:     atomic_umin g5, l(0), r1.y
  33  0x00000494:   endif 
  34  0x00000498:   ge r0.w, r0.w, r1.y
  35  0x000004B4:   if_nz r0.w
  36  0x000004C0:     atomic_umax g6, l(0), r1.y
  37  0x000004DC:   endif 
  38  0x000004E0: endif 
  39  0x000004E4: sync_g_t
  40  0x000004E8: ld_raw r4.z, l(0), g5.xxxx
  41  0x00000504: ld_raw r5.z, l(0), g6.xxxx
  42  0x00000520: ieq r0.w, r2.z, l(0x7f7fffff)
  43  0x0000053C: ieq r2.w, r3.z, l(0)
  44  0x00000558: and r0.w, r0.w, r2.w
  45  0x00000574: lt r2.w, |cb1[25].x|, l(0.000010)
  46  0x00000598: lt r3.w, |cb1[26].x|, l(0.000010)
  47  0x000005BC: and r2.w, r2.w, r3.w
  48  0x000005D8: if_nz r2.w
  49  0x000005E4:   mov r6.x, cb1[32].x
  50  0x000005FC:   mov r6.y, cb1[33].y
  51  0x00000614:   add r6.zw, r6.xxxy, r6.xxxy
  52  0x00000630:   utof r7.xyzw, cb0[12].zwxy
  53  0x00000648:   mul r7.xy, r6.zwzz, r7.xyxx
  54  0x00000664:   mul r8.xy, cb0[13].xyxx, cb1[122].xyxx
  55  0x00000688:   div r7.xy, r7.xyxx, r8.xyxx
  56  0x000006A4:   add r7.zw, r7.zzzw, -cb1[121].xxxy
  57  0x000006C8:   mul r6.zw, r6.zzzw, r7.zzzw
  58  0x000006E4:   mad r6.xy, r6.zwzz, cb1[122].zwzz, -r6.xyxx
  59  0x00000710:   utof r6.zw, vThreadGroupID.xxxy
  60  0x00000720:   mad r6.zw, r6.zzzw, r7.xxxy, r6.xxxy
  61  0x00000744:   iadd r7.zw, vThreadGroupID.xxxy, l(0, 0, 1, 1)
  62  0x00000768:   utof r7.zw, r7.zzzw
  63  0x0000077C:   mad r6.xy, r7.zwzz, r7.xyxx, r6.xyxx
  64  0x000007A0:   mul r6.xyzw, r6.xyzw, l(1.000000, -1.000000, 1.000000, -1.000000)
  65  0x000007C8:   mul r7.xy, r2.zzzz, r6.zwzz
  66  0x000007E4:   mul r7.zw, r5.zzzz, r6.zzzw
  67  0x00000800:   min r2.xy, r7.zwzz, r7.xyxx
  68  0x0000081C:   mul r7.xy, r2.zzzz, r6.xyxx
  69  0x00000838:   mul r7.zw, r5.zzzz, r6.xxxy
  70  0x00000854:   max r5.xy, r7.zwzz, r7.xyxx
  71  0x00000870:   mul r7.xy, r4.zzzz, r6.zwzz
  72  0x0000088C:   mul r6.zw, r3.zzzz, r6.zzzw
  73  0x000008A8:   min r4.xy, r6.zwzz, r7.xyxx
  74  0x000008C4:   mul r6.zw, r4.zzzz, r6.xxxy
  75  0x000008E0:   mul r6.xy, r3.zzzz, r6.xyxx
  76  0x000008FC:   max r3.xy, r6.xyxx, r6.zwzz
  77  0x00000918: else 
  78  0x0000091C:   ishl r6.xy, cb0[12].zwzz, l(1, 1, 0, 0)
  79  0x00000948:   utof r6.xy, r6.xyxx
  80  0x0000095C:   mul r6.zw, cb0[13].xxxy, cb1[122].xxxy
  81  0x00000980:   div r6.xy, r6.xyxx, r6.zwzz
  82  0x0000099C:   utof r6.zw, cb0[12].xxxy
  83  0x000009B4:   add r6.zw, r6.zzzw, -cb1[121].xxxy
  84  0x000009D8:   mul r6.zw, r6.zzzw, cb1[122].zzzw
  85  0x000009F8:   mad r6.zw, r6.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
  86  0x00000A34:   utof r7.xy, vThreadGroupID.xyxx
  87  0x00000A44:   mad r7.xy, r7.xyxx, r6.xyxx, r6.zwzz
  88  0x00000A68:   mul r7.xy, r7.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000)
  89  0x00000A90:   iadd r7.zw, vThreadGroupID.xxxy, l(0, 0, 1, 1)
  90  0x00000AB4:   utof r7.zw, r7.zzzw
  91  0x00000AC8:   mad r6.xy, r7.zwzz, r6.xyxx, r6.zwzz
  92  0x00000AEC:   mul r6.xy, r6.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000)
  93  0x00000B14:   lt r2.w, cb1[27].w, l(1.000000)
  94  0x00000B34:   add r3.w, r2.z, cb1[57].w
  95  0x00000B54:   mul r3.w, r3.w, cb1[57].z
  96  0x00000B74:   div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  97  0x00000B9C:   mad r4.w, r2.z, cb1[26].z, cb1[27].z
  98  0x00000BC8:   movc r3.w, r2.w, r3.w, r4.w
  99  0x00000BEC:   mul r7.yzw, r7.yyyy, cb1[33].xxyw
 100  0x00000C0C:   mad r7.xyz, r7.xxxx, cb1[32].xywx, r7.yzwy
 101  0x00000C34:   mad r8.xyz, r3.wwww, cb1[34].xywx, r7.xyzx
 102  0x00000C5C:   add r8.xyz, r8.xyzx, cb1[35].xywx
 103  0x00000C7C:   mul r6.yzw, r6.yyyy, cb1[33].xxyw
 104  0x00000C9C:   mad r6.xyz, r6.xxxx, cb1[32].xywx, r6.yzwy
 105  0x00000CC4:   mad r9.xyz, r3.wwww, cb1[34].xywx, r6.xyzx
 106  0x00000CEC:   add r9.xyz, r9.xyzx, cb1[35].xywx
 107  0x00000D0C:   add r3.w, r5.z, cb1[57].w
 108  0x00000D2C:   mul r3.w, r3.w, cb1[57].z
 109  0x00000D4C:   div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
 110  0x00000D74:   mad r4.w, r5.z, cb1[26].z, cb1[27].z
 111  0x00000DA0:   movc r3.w, r2.w, r3.w, r4.w
 112  0x00000DC4:   mad r10.xyz, r3.wwww, cb1[34].xywx, r7.xyzx
 113  0x00000DEC:   add r10.xyz, r10.xyzx, cb1[35].xywx
 114  0x00000E0C:   mad r11.xyz, r3.wwww, cb1[34].xywx, r6.xyzx
 115  0x00000E34:   add r11.xyz, r11.xyzx, cb1[35].xywx
 116  0x00000E54:   div r8.xy, r8.xyxx, r8.zzzz
 117  0x00000E70:   div r8.zw, r10.xxxy, r10.zzzz
 118  0x00000E8C:   min r2.xy, r8.zwzz, r8.xyxx
 119  0x00000EA8:   div r8.xy, r9.xyxx, r9.zzzz
 120  0x00000EC4:   div r8.zw, r11.xxxy, r11.zzzz
 121  0x00000EE0:   max r5.xy, r8.zwzz, r8.xyxx
 122  0x00000EFC:   add r3.w, r4.z, cb1[57].w
 123  0x00000F1C:   mul r3.w, r3.w, cb1[57].z
 124  0x00000F3C:   div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
 125  0x00000F64:   mad r4.w, r4.z, cb1[26].z, cb1[27].z
 126  0x00000F90:   movc r3.w, r2.w, r3.w, r4.w
 127  0x00000FB4:   mad r8.xyz, r3.wwww, cb1[34].xywx, r7.xyzx
 128  0x00000FDC:   add r8.xyz, r8.xyzx, cb1[35].xywx
 129  0x00000FFC:   mad r9.xyz, r3.wwww, cb1[34].xywx, r6.xyzx
 130  0x00001024:   add r9.xyz, r9.xyzx, cb1[35].xywx
 131  0x00001044:   add r3.w, r3.z, cb1[57].w
 132  0x00001064:   mul r3.w, r3.w, cb1[57].z
 133  0x00001084:   div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
 134  0x000010AC:   mad r4.w, r3.z, cb1[26].z, cb1[27].z
 135  0x000010D8:   movc r2.w, r2.w, r3.w, r4.w
 136  0x000010FC:   mad r7.xyz, r2.wwww, cb1[34].xywx, r7.xyzx
 137  0x00001124:   add r7.xyz, r7.xyzx, cb1[35].xywx
 138  0x00001144:   mad r6.xyz, r2.wwww, cb1[34].xywx, r6.xyzx
 139  0x0000116C:   add r6.xyz, r6.xyzx, cb1[35].xywx
 140  0x0000118C:   div r8.xy, r8.xyxx, r8.zzzz
 141  0x000011A8:   div r7.xy, r7.xyxx, r7.zzzz
 142  0x000011C4:   min r4.xy, r7.xyxx, r8.xyxx
 143  0x000011E0:   div r7.xy, r9.xyxx, r9.zzzz
 144  0x000011FC:   div r6.xy, r6.xyxx, r6.zzzz
 145  0x00001218:   max r3.xy, r6.xyxx, r7.xyxx
 146  0x00001234: endif 
 147  0x00001238: if_z r0.w
 148  0x00001244:   mad r0.yz, r0.yyzy, cb1[123].zzwz, -cb1[58].wwzw
 149  0x00001274:   div r0.yz, r0.yyzy, cb1[58].xxyx
 150  0x00001294:   mul r0.yz, r1.yyyy, r0.yyzy
 151  0x000012B0:   mul r6.xyz, r0.zzzz, cb1[45].xyzx
 152  0x000012D0:   mad r0.yzw, r0.yyyy, cb1[44].xxyz, r6.xxyz
 153  0x000012F8:   mad r0.yzw, r1.yyyy, cb1[46].xxyz, r0.yyzw
 154  0x00001320:   add r0.yzw, r0.yyzw, cb1[47].xxyz
 155  0x00001340:   add r2.xyz, r2.xyzx, r5.xyzx
 156  0x0000135C:   mul r6.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 157  0x00001384:   mul r7.xyz, r6.yyyy, cb1[13].xyzx
 158  0x000013A4:   mad r6.xyw, r6.xxxx, cb1[12].xyxz, r7.xyxz
 159  0x000013CC:   mad r6.xyz, r6.zzzz, cb1[14].xyzx, r6.xywx
 160  0x000013F4:   add r6.xyz, r6.xyzx, cb1[15].xyzx
 161  0x00001414:   add r6.xyz, r6.xyzx, -cb1[62].xyzx
 162  0x00001438:   mad r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -r5.xyzx
 163  0x0000146C:   dp3 r2.x, r2.xyzx, r2.xyzx
 164  0x00001488:   add r2.yzw, r3.xxyz, r4.xxyz
 165  0x000014A4:   mul r4.xyz, r2.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000)
 166  0x000014CC:   mul r5.xyw, r4.yyyy, cb1[13].xyxz
 167  0x000014EC:   mad r4.xyw, r4.xxxx, cb1[12].xyxz, r5.xyxw
 168  0x00001514:   mad r4.xyz, r4.zzzz, cb1[14].xyzx, r4.xywx
 169  0x0000153C:   add r4.xyz, r4.xyzx, cb1[15].xyzx
 170  0x0000155C:   add r4.xyz, r4.xyzx, -cb1[62].xyzx
 171  0x00001580:   mad r2.yzw, r2.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000), -r3.xxyz
 172  0x000015B4:   dp3 r2.y, r2.yzwy, r2.yzwy
 173  0x000015D0:   sqrt r2.xy, r2.xyxx
 174  0x000015E4:   lt r2.z, r5.z, r1.y
 175  0x00001600:   mov r3.y, l(0)
 176  0x00001614:   mov r5.x, l(0)
 177  0x00001628:   mov r2.w, r0.x
 178  0x0000163C:   loop 
 179  0x00001640:     uge r3.w, r2.w, cb0[10].x
 180  0x00001660:     breakc_nz r3.w
 181  0x0000166C:     ld_indexable(buffer)(float,float,float,float) r7.xyzw, r2.wwww, t2.xyzw
 182  0x00001690:     f16tof32 r3.w, r7.w
 183  0x000016A4:     sincos r8.x, r9.x, r3.w
 184  0x000016C0:     ishl r3.w, r2.w, l(1)
 185  0x000016DC:     ld_indexable(buffer)(float,float,float,float) r10.xyzw, r3.wwww, t1.xyzw
 186  0x00001700:     bfi r3.w, l(31), l(1), r2.w, l(1)
 187  0x0000172C:     ld_indexable(buffer)(float,float,float,float) r11.xyzw, r3.wwww, t1.xyzw
 188  0x00001750:     lt r3.w, |r11.y|, |r11.x|
 189  0x00001774:     dp2 r4.w, r11.xzxx, r11.xzxx
 190  0x00001790:     sqrt r4.w, r4.w
 191  0x000017A4:     div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 192  0x000017CC:     mul r3.x, r4.w, -r11.z
 193  0x000017EC:     mul r3.z, r4.w, r11.x
 194  0x00001808:     dp2 r4.w, r11.yzyy, r11.yzyy
 195  0x00001824:     sqrt r4.w, r4.w
 196  0x00001838:     div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 197  0x00001860:     mul r5.y, r4.w, r11.z
 198  0x0000187C:     mul r5.z, r4.w, -r11.y
 199  0x0000189C:     movc r3.xzw, r3.wwww, r3.xxyz, r5.xxyz
 200  0x000018C0:     mul r5.yzw, r3.zzwx, r11.zzxy
 201  0x000018DC:     mad r5.yzw, r11.yyzx, r3.wwxz, -r5.yyzw
 202  0x00001904:     mad r4.w, r11.w, l(0.500000), r10.w
 203  0x00001928:     div r4.w, r10.w, r4.w
 204  0x00001944:     mul r8.yzw, r4.wwww, r11.xxyz
 205  0x00001960:     add r9.yzw, r6.xxyz, -r10.xxyz
 206  0x00001980:     dp3 r11.x, r9.yzwy, r3.xzwx
 207  0x0000199C:     dp3 r11.y, r9.yzwy, r5.yzwy
 208  0x000019B8:     dp3 r11.z, r9.yzwy, r8.yzwy
 209  0x000019D4:     add r9.yzw, r4.xxyz, -r10.xxyz
 210  0x000019F4:     dp3 r10.x, r9.yzwy, r3.xzwx
 211  0x00001A10:     dp3 r10.y, r9.yzwy, r5.yzwy
 212  0x00001A2C:     dp3 r10.z, r9.yzwy, r8.yzwy
 213  0x00001A48:     dp3 r12.x, r7.xyzx, r3.xzwx
 214  0x00001A64:     dp3 r12.y, r7.xyzx, r5.yzwy
 215  0x00001A80:     dp3 r12.z, r7.xyzx, r8.yzwy
 216  0x00001A9C:     dp3 r3.x, r12.xyzx, r12.xyzx
 217  0x00001AB8:     rsq r3.x, r3.x
 218  0x00001ACC:     mul r3.xzw, r3.xxxx, r12.xxyz
 219  0x00001AE8:     add r4.w, r10.w, cb0[14].z
 220  0x00001B08:     add r5.y, r2.x, r4.w
 221  0x00001B24:     dp3 r5.z, -r11.xyzx, -r11.xyzx
 222  0x00001B48:     mul r5.y, r5.y, r5.y
 223  0x00001B64:     lt r5.y, r5.z, r5.y
 224  0x00001B80:     add r5.w, r2.x, r10.w
 225  0x00001B9C:     div r6.w, r5.w, r8.x
 226  0x00001BB8:     mad r7.xyz, -r6.wwww, r3.xzwx, r11.xyzx
 227  0x00001BE0:     dp3 r6.w, -r7.xyzx, -r7.xyzx
 228  0x00001C04:     dp3 r7.x, r3.xzwx, -r7.xyzx
 229  0x00001C24:     lt r7.y, l(0.000000), r7.x
 230  0x00001C40:     mul r7.x, r7.x, r7.x
 231  0x00001C5C:     mul r7.z, r9.x, r9.x
 232  0x00001C78:     mul r6.w, r6.w, r7.z
 233  0x00001C94:     ge r6.w, r7.x, r6.w
 234  0x00001CB0:     and r6.w, r6.w, r7.y
 235  0x00001CCC:     dp3 r7.x, r3.xzwx, -r11.xyzx
 236  0x00001CEC:     lt r7.y, l(0.000000), -r7.x
 237  0x00001D0C:     mul r7.w, r7.x, r7.x
 238  0x00001D28:     mul r8.y, r8.x, r8.x
 239  0x00001D44:     mul r8.z, r5.z, r8.y
 240  0x00001D60:     ge r7.w, r7.w, r8.z
 241  0x00001D7C:     and r7.y, r7.w, r7.y
 242  0x00001D98:     mul r7.w, r5.w, r5.w
 243  0x00001DB4:     ge r5.z, r7.w, r5.z
 244  0x00001DD0:     movc r5.z, r7.y, r5.z, l(-1)
 245  0x00001DF4:     and r5.z, r5.z, r6.w
 246  0x00001E10:     add r5.w, -r5.w, r7.x
 247  0x00001E30:     lt r5.w, r5.w, cb0[14].z
 248  0x00001E50:     and r5.z, r5.w, r5.z
 249  0x00001E6C:     and r5.y, r5.z, r5.y
 250  0x00001E88:     if_nz r5.y
 251  0x00001E94:       imm_atomic_iadd r9.x, g0, l(0), l(1)
 252  0x00001EB8:       umin r5.y, r9.x, l(511)
 253  0x00001ED4:       store_structured g2.x, r5.y, l(0), r2.w
 254  0x00001EF8:     endif 
 255  0x00001EFC:     add r4.w, r2.y, r4.w
 256  0x00001F18:     dp3 r5.y, -r10.xyzx, -r10.xyzx
 257  0x00001F3C:     mul r4.w, r4.w, r4.w
 258  0x00001F58:     lt r4.w, r5.y, r4.w
 259  0x00001F74:     add r5.z, r2.y, r10.w
 260  0x00001F90:     div r5.w, r5.z, r8.x
 261  0x00001FAC:     mad r7.xyw, -r5.wwww, r3.xzxw, r10.xyxz
 262  0x00001FD4:     dp3 r5.w, -r7.xywx, -r7.xywx
 263  0x00001FF8:     dp3 r6.w, r3.xzwx, -r7.xywx
 264  0x00002018:     lt r7.x, l(0.000000), r6.w
 265  0x00002034:     mul r6.w, r6.w, r6.w
 266  0x00002050:     mul r5.w, r5.w, r7.z
 267  0x0000206C:     ge r5.w, r6.w, r5.w
 268  0x00002088:     and r5.w, r5.w, r7.x
 269  0x000020A4:     dp3 r3.x, r3.xzwx, -r10.xyzx
 270  0x000020C4:     lt r3.z, l(0.000000), -r3.x
 271  0x000020E4:     mul r3.w, r3.x, r3.x
 272  0x00002100:     mul r6.w, r5.y, r8.y
 273  0x0000211C:     ge r3.w, r3.w, r6.w
 274  0x00002138:     and r3.z, r3.w, r3.z
 275  0x00002154:     mul r3.w, r5.z, r5.z
 276  0x00002170:     ge r3.w, r3.w, r5.y
 277  0x0000218C:     movc r3.z, r3.z, r3.w, l(-1)
 278  0x000021B0:     and r3.z, r3.z, r5.w
 279  0x000021CC:     add r3.x, -r5.z, r3.x
 280  0x000021EC:     lt r3.x, r3.x, cb0[14].z
 281  0x0000220C:     and r3.x, r3.x, r3.z
 282  0x00002228:     and r3.x, r3.x, r4.w
 283  0x00002244:     if_nz r3.x
 284  0x00002250:       imm_atomic_iadd r7.x, g1, l(0), l(1)
 285  0x00002274:       umin r3.x, r7.x, l(511)
 286  0x00002290:       iadd r3.x, r3.x, l(512)
 287  0x000022AC:       store_structured g2.x, r3.x, l(0), r2.w
 288  0x000022D0:     endif 
 289  0x000022D4:     iadd r2.w, r2.w, l(64)
 290  0x000022F0:   endloop 
 291  0x000022F4:   sync_g_t
 292  0x000022F8:   ld_raw r0.x, l(0), g0.xxxx
 293  0x00002314:   ld_raw r2.x, l(0), g1.xxxx
 294  0x00002330:   movc r2.y, r2.z, r2.x, r0.x
 295  0x00002354:   umin r2.y, r2.y, l(512)
 296  0x00002370:   iadd r0.x, r0.x, r2.x
 297  0x0000238C:   div r2.x, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[14].z
 298  0x000023B8:   bfi r2.z, l(1), l(9), r2.z, l(0)
 299  0x000023E4:   mov r3.y, l(0)
 300  0x000023F8:   mov r4.x, l(0)
 301  0x0000240C:   mov r2.w, l(1.000000)
 302  0x00002420:   mov r3.w, l(0)
 303  0x00002434:   loop 
 304  0x00002438:     uge r4.w, r3.w, r2.y
 305  0x00002454:     breakc_nz r4.w
 306  0x00002460:     iadd r4.w, r2.z, r3.w
 307  0x0000247C:     ld_structured r4.w, r4.w, l(0), g2.xxxx
 308  0x000024A0:     ld_indexable(buffer)(float,float,float,float) r5.xyzw, r4.wwww, t2.xyzw
 309  0x000024C4:     f16tof32 r6.x, r5.w
 310  0x000024D8:     ushr r5.w, r5.w, l(16)
 311  0x000024F4:     f16tof32 r5.w, r5.w
 312  0x00002508:     sincos null, r6.y, r6.x
 313  0x00002520:     mad r6.y, -r6.y, l(6.283185), l(6.283185)
 314  0x00002548:     ishl r6.z, r4.w, l(1)
 315  0x00002564:     ld_indexable(buffer)(float,float,float,float) r7.xyzw, r6.zzzz, t1.xyzw
 316  0x00002588:     add r6.z, -r5.z, -cb0[13].z
 317  0x000025B0:     dp2_sat r6.z, cb0[13].wwww, r6.zzzz
 318  0x000025D0:     add r6.z, -r6.z, l(1.000000)
 319  0x000025F0:     mul r6.z, r6.z, r7.w
 320  0x0000260C:     bfi r4.w, l(31), l(1), r4.w, l(1)
 321  0x00002638:     ld_indexable(buffer)(float,float,float,float) r8.xyzw, r4.wwww, t1.xyzw
 322  0x0000265C:     lt r4.w, l(0.000000), r8.w
 323  0x00002678:     if_nz r4.w
 324  0x00002684:       lt r4.w, |r8.y|, |r8.x|
 325  0x000026A8:       dp2 r6.w, r8.xzxx, r8.xzxx
 326  0x000026C4:       sqrt r6.w, r6.w
 327  0x000026D8:       div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 328  0x00002700:       mul r3.x, r6.w, -r8.z
 329  0x00002720:       mul r3.z, r6.w, r8.x
 330  0x0000273C:       dp2 r6.w, r8.yzyy, r8.yzyy
 331  0x00002758:       sqrt r6.w, r6.w
 332  0x0000276C:       div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 333  0x00002794:       mul r4.y, r6.w, r8.z
 334  0x000027B0:       mul r4.z, r6.w, -r8.y
 335  0x000027D0:       movc r4.yzw, r4.wwww, r3.xxyz, r4.xxyz
 336  0x000027F4:       mul r9.xyz, r4.zwyz, r8.zxyz
 337  0x00002810:       mad r9.xyz, r8.yzxy, r4.wyzw, -r9.xyzx
 338  0x00002838:       mad r3.x, r8.w, l(0.500000), r6.z
 339  0x0000285C:       div r3.x, r6.z, r3.x
 340  0x00002878:       mul r8.xyz, r3.xxxx, r8.xyzx
 341  0x00002894:       add r10.xyz, r0.yzwy, -r7.xyzx
 342  0x000028B4:       dp3 r11.x, r10.xyzx, r4.yzwy
 343  0x000028D0:       dp3 r11.y, r10.xyzx, r9.xyzx
 344  0x000028EC:       dp3 r11.z, r10.xyzx, r8.xyzx
 345  0x00002908:       dp3 r10.x, r5.xyzx, r4.yzwy
 346  0x00002924:       dp3 r10.y, r5.xyzx, r9.xyzx
 347  0x00002940:       dp3 r10.z, r5.xyzx, r8.xyzx
 348  0x0000295C:       dp3 r3.x, r11.xyzx, r11.xyzx
 349  0x00002978:       sqrt r3.x, r3.x
 350  0x0000298C:       div r4.yzw, -r11.xxyz, r3.xxxx
 351  0x000029AC:       dp3 r3.z, r10.xyzx, r10.xyzx
 352  0x000029C8:       rsq r3.z, r3.z
 353  0x000029DC:       mul r5.xyz, r3.zzzz, r10.xyzx
 354  0x000029F8:     else 
 355  0x000029FC:       add r7.xyz, -r0.yzwy, r7.xyzx
 356  0x00002A1C:       dp3 r3.z, r7.xyzx, r7.xyzx
 357  0x00002A38:       sqrt r3.x, r3.z
 358  0x00002A4C:       div r4.yzw, r7.xxyz, r3.xxxx
 359  0x00002A68:     endif 
 360  0x00002A6C:     dp3 r3.z, r4.yzwy, r5.xyzx
 361  0x00002A88:     mad r4.y, |r3.z|, l(-0.156583), l(1.570796)
 362  0x00002AB0:     add r4.z, -|r3.z|, l(1.000000)
 363  0x00002AD0:     sqrt r4.z, r4.z
 364  0x00002AE4:     mul r4.w, r4.z, r4.y
 365  0x00002B00:     ge r3.z, r3.z, l(0.000000)
 366  0x00002B1C:     mad r4.y, -r4.y, r4.z, l(3.141593)
 367  0x00002B44:     movc r3.z, r3.z, r4.w, r4.y
 368  0x00002B68:     div r4.y, r6.z, r3.x
 369  0x00002B84:     lt r4.z, r4.y, l(1.000000)
 370  0x00002BA0:     div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.y
 371  0x00002BC8:     movc r4.y, r4.z, r4.y, r4.w
 372  0x00002BEC:     mul r4.w, r4.y, r4.y
 373  0x00002C08:     mad r5.x, r4.w, l(0.087293), l(-0.301895)
 374  0x00002C2C:     mad r4.w, r5.x, r4.w, l(1.000000)
 375  0x00002C50:     mul r5.x, r4.y, r4.w
 376  0x00002C6C:     mad r4.y, -r4.w, r4.y, l(1.570796)
 377  0x00002C94:     movc r4.y, r4.z, r5.x, r4.y
 378  0x00002CB8:     max r4.z, r4.y, r6.x
 379  0x00002CD4:     min r4.w, r4.y, r6.x
 380  0x00002CF0:     add r4.z, -r4.w, r4.z
 381  0x00002D10:     ge r4.z, r4.z, r3.z
 382  0x00002D2C:     sincos null, r4.w, r4.w
 383  0x00002D44:     mad r4.w, -r4.w, l(6.283185), l(6.283185)
 384  0x00002D6C:     add r5.x, r4.y, r6.x
 385  0x00002D88:     ge r5.y, r3.z, r5.x
 386  0x00002DA4:     add r4.y, -r4.y, r6.x
 387  0x00002DC4:     add r3.z, r3.z, -|r4.y|
 388  0x00002DE4:     add r4.y, -|r4.y|, r5.x
 389  0x00002E04:     div_sat r3.z, r3.z, r4.y
 390  0x00002E20:     add r3.z, -r3.z, l(1.000000)
 391  0x00002E40:     mad r4.y, r3.z, l(-2.000000), l(3.000000)
 392  0x00002E64:     mul r3.z, r3.z, r3.z
 393  0x00002E80:     mul r3.z, r3.z, r4.y
 394  0x00002E9C:     mul r3.z, r4.w, r3.z
 395  0x00002EB8:     movc r3.z, r5.y, l(0), r3.z
 396  0x00002EDC:     movc r3.z, r4.z, r4.w, r3.z
 397  0x00002F00:     div r3.z, r3.z, r6.y
 398  0x00002F1C:     min r3.z, r3.z, l(1.000000)
 399  0x00002F38:     add r3.z, -r3.z, l(1.000000)
 400  0x00002F58:     mul r3.x, r2.x, r3.x
 401  0x00002F74:     mad_sat r3.x, r3.x, l(3.000000), l(-2.000000)
 402  0x00002F98:     add r4.y, -r3.z, l(1.000000)
 403  0x00002FB8:     mad r3.x, r3.x, r4.y, r3.z
 404  0x00002FDC:     add r3.z, -r5.w, l(1.000000)
 405  0x00002FFC:     mad r3.x, r3.x, r3.z, r5.w
 406  0x00003020:     mul r2.w, r2.w, r3.x
 407  0x0000303C:     iadd r3.w, r3.w, l(1)
 408  0x00003058:   endloop 
 409  0x0000305C:   ieq r0.yz, vThreadIDInGroup.xxyx, l(0, 0, 0, 0)
 410  0x00003080:   and r0.y, r0.z, r0.y
 411  0x0000309C:   ult r0.zw, vThreadGroupID.xxxy, cb0[15].xxxy
 412  0x000030B8:   and r0.z, r0.w, r0.z
 413  0x000030D4:   and r0.y, r0.z, r0.y
 414  0x000030F0:   if_nz r0.y
 415  0x000030FC:     imad r0.y, vThreadGroupID.y, cb0[15].x, vThreadGroupID.x
 416  0x0000311C:     store_uav_typed u1.xyzw, r0.yyyy, r0.xxxx
 417  0x00003138:   endif 
 418  0x0000313C: else 
 419  0x00003140:   mov r2.w, l(1.000000)
 420  0x00003154: endif 
 421  0x00003158: imul null, r0.xyzw, vThreadID.xyzz, cb0[14].yyyy
 422  0x00003178: ld_indexable(texture2d)(uint,uint,uint,uint) r0.x, r0.xyzw, t3.xyzw
 423  0x0000319C: and r0.x, r0.x, l(1)
 424  0x000031B8: movc r1.xzw, r0.xxxx, r2.wwww, l(1.000000,0,1.000000,1.000000)
 425  0x000031E8: store_uav_typed u0.xyzw, vThreadID.xyyy, r1.xyzw
 426  0x00003200: ret 
// Approximately 0 instruction slots used
