//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      0x00000000: cs_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[14], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[120], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_resource_texture2d (float,float,float,float) t0
      0x00000048: dcl_resource_buffer (float,float,float,float) t1
      0x00000058: dcl_resource_buffer (float,float,float,float) t2
      0x00000068: dcl_uav_typed_texture2d (float,float,float,float) u0
      0x00000078: dcl_uav_typed_buffer (uint,uint,uint,uint) u1
      0x00000088: dcl_input vThreadGroupID.xy
      0x00000090: dcl_input vThreadIDInGroup.xy
      0x00000098: dcl_input vThreadID.xy
      0x000000A0: dcl_temps 13
      0x000000A8: dcl_tgsm_raw g0, 4
      0x000000B8: dcl_tgsm_raw g1, 4
      0x000000C8: dcl_tgsm_structured g2, 4, 1024
      0x000000DC: dcl_tgsm_raw g3, 4
      0x000000EC: dcl_tgsm_raw g4, 4
      0x000000FC: dcl_tgsm_raw g5, 4
      0x0000010C: dcl_tgsm_raw g6, 4
      0x0000011C: dcl_thread_group 8, 8, 1
   0  0x0000012C: imad r0.x, vThreadIDInGroup.y, l(8), vThreadIDInGroup.x
   1  0x00000148: imad r0.yz, vThreadID.xxyx, cb0[12].yyyy, cb0[10].xxyx
   2  0x00000170: utof r0.yz, r0.yyzy
   3  0x00000184: add r0.yz, r0.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
   4  0x000001AC: mul r1.xy, r0.yzyy, cb1[119].zwzz
   5  0x000001CC: sample_l_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t0.yzwx, s0, l(0.000000)
   6  0x00000200: mad r1.x, r0.w, cb1[53].x, cb1[53].y
   7  0x0000022C: mad r0.w, r0.w, cb1[53].z, -cb1[53].w
   8  0x0000025C: div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
   9  0x00000284: add r1.y, r0.w, r1.x
  10  0x000002A0: if_z r0.x
  11  0x000002AC:   store_raw g3.x, l(0), l(340282346638528859811704183484516925440.000000)
  12  0x000002C8:   store_raw g4.x, l(0), l(0)
  13  0x000002E4:   store_raw g5.x, l(0), l(340282346638528859811704183484516925440.000000)
  14  0x00000300:   store_raw g6.x, l(0), l(0)
  15  0x0000031C:   store_raw g0.x, l(0), l(0)
  16  0x00000338:   store_raw g1.x, l(0), l(0)
  17  0x00000354: endif 
  18  0x00000358: sync_g_t
  19  0x0000035C: lt r0.w, r1.y, l(20000.000000)
  20  0x00000378: if_nz r0.w
  21  0x00000384:   atomic_umin g3, l(0), r1.y
  22  0x000003A0:   atomic_umax g4, l(0), r1.y
  23  0x000003BC: endif 
  24  0x000003C0: sync_g_t
  25  0x000003C4: ld_raw r2.z, l(0), g3.xxxx
  26  0x000003E0: ld_raw r3.z, l(0), g4.xxxx
  27  0x000003FC: if_nz r0.w
  28  0x00000408:   add r0.w, r2.z, r3.z
  29  0x00000424:   mul r0.w, r0.w, l(0.500000)
  30  0x00000440:   ge r1.z, r1.y, r0.w
  31  0x0000045C:   if_nz r1.z
  32  0x00000468:     atomic_umin g5, l(0), r1.y
  33  0x00000484:   endif 
  34  0x00000488:   ge r0.w, r0.w, r1.y
  35  0x000004A4:   if_nz r0.w
  36  0x000004B0:     atomic_umax g6, l(0), r1.y
  37  0x000004CC:   endif 
  38  0x000004D0: endif 
  39  0x000004D4: sync_g_t
  40  0x000004D8: ld_raw r4.z, l(0), g5.xxxx
  41  0x000004F4: ld_raw r5.z, l(0), g6.xxxx
  42  0x00000510: ieq r0.w, r2.z, l(0x7f7fffff)
  43  0x0000052C: ieq r1.z, r3.z, l(0)
  44  0x00000548: and r0.w, r0.w, r1.z
  45  0x00000564: lt r1.z, |cb1[25].x|, l(0.000010)
  46  0x00000588: lt r1.w, |cb1[26].x|, l(0.000010)
  47  0x000005AC: and r1.z, r1.w, r1.z
  48  0x000005C8: if_nz r1.z
  49  0x000005D4:   mov r6.x, cb1[28].x
  50  0x000005EC:   mov r6.y, cb1[29].y
  51  0x00000604:   add r1.zw, r6.xxxy, r6.xxxy
  52  0x00000620:   utof r7.xyzw, cb0[10].zwxy
  53  0x00000638:   mul r6.zw, r1.zzzw, r7.xxxy
  54  0x00000654:   mul r7.xy, cb0[11].xyxx, cb1[118].xyxx
  55  0x00000678:   div r6.zw, r6.zzzw, r7.xxxy
  56  0x00000694:   add r7.xy, r7.zwzz, -cb1[117].xyxx
  57  0x000006B8:   mul r1.zw, r1.zzzw, r7.xxxy
  58  0x000006D4:   mad r1.zw, r1.zzzw, cb1[118].zzzw, -r6.xxxy
  59  0x00000700:   utof r6.xy, vThreadGroupID.xyxx
  60  0x00000710:   mad r6.xy, r6.xyxx, r6.zwzz, r1.zwzz
  61  0x00000734:   mul r6.xy, r6.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000)
  62  0x0000075C:   iadd r7.xy, vThreadGroupID.xyxx, l(1, 1, 0, 0)
  63  0x00000780:   utof r7.xy, r7.xyxx
  64  0x00000794:   mad r1.zw, r7.xxxy, r6.zzzw, r1.zzzw
  65  0x000007B8:   mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 1.000000, -1.000000)
  66  0x000007E0:   mul r6.zw, r2.zzzz, r6.xxxy
  67  0x000007FC:   mul r7.xy, r5.zzzz, r6.xyxx
  68  0x00000818:   min r2.xy, r6.zwzz, r7.xyxx
  69  0x00000834:   mul r6.zw, r1.zzzw, r2.zzzz
  70  0x00000850:   mul r7.xy, r1.zwzz, r5.zzzz
  71  0x0000086C:   max r5.xy, r6.zwzz, r7.xyxx
  72  0x00000888:   mul r6.zw, r4.zzzz, r6.xxxy
  73  0x000008A4:   mul r6.xy, r3.zzzz, r6.xyxx
  74  0x000008C0:   min r4.xy, r6.xyxx, r6.zwzz
  75  0x000008DC:   mul r6.xy, r1.zwzz, r4.zzzz
  76  0x000008F8:   mul r1.zw, r1.zzzw, r3.zzzz
  77  0x00000914:   max r3.xy, r1.zwzz, r6.xyxx
  78  0x00000930: else 
  79  0x00000934:   ishl r1.zw, cb0[10].zzzw, l(0, 0, 1, 1)
  80  0x00000960:   utof r1.zw, r1.zzzw
  81  0x00000974:   mul r6.xy, cb0[11].xyxx, cb1[118].xyxx
  82  0x00000998:   div r1.zw, r1.zzzw, r6.xxxy
  83  0x000009B4:   utof r6.xy, cb0[10].xyxx
  84  0x000009CC:   add r6.xy, r6.xyxx, -cb1[117].xyxx
  85  0x000009F0:   mul r6.xy, r6.xyxx, cb1[118].zwzz
  86  0x00000A10:   mad r6.xy, r6.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  87  0x00000A4C:   utof r6.zw, vThreadGroupID.xxxy
  88  0x00000A5C:   mad r6.zw, r6.zzzw, r1.zzzw, r6.xxxy
  89  0x00000A80:   mul r6.zw, r6.zzzw, l(0.000000, 0.000000, 1.000000, -1.000000)
  90  0x00000AA8:   iadd r7.xy, vThreadGroupID.xyxx, l(1, 1, 0, 0)
  91  0x00000ACC:   utof r7.xy, r7.xyxx
  92  0x00000AE0:   mad r1.zw, r7.xxxy, r1.zzzw, r6.xxxy
  93  0x00000B04:   mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 1.000000, -1.000000)
  94  0x00000B2C:   lt r2.w, cb1[27].w, l(1.000000)
  95  0x00000B4C:   add r3.w, r2.z, cb1[53].w
  96  0x00000B6C:   mul r3.w, r3.w, cb1[53].z
  97  0x00000B8C:   div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  98  0x00000BB4:   mad r4.w, r2.z, cb1[26].z, cb1[27].z
  99  0x00000BE0:   movc r3.w, r2.w, r3.w, r4.w
 100  0x00000C04:   mul r6.xyw, r6.wwww, cb1[29].xyxw
 101  0x00000C24:   mad r6.xyz, r6.zzzz, cb1[28].xywx, r6.xywx
 102  0x00000C4C:   mad r7.xyz, r3.wwww, cb1[30].xywx, r6.xyzx
 103  0x00000C74:   add r7.xyz, r7.xyzx, cb1[31].xywx
 104  0x00000C94:   mul r8.xyz, r1.wwww, cb1[29].xywx
 105  0x00000CB4:   mad r8.xyz, r1.zzzz, cb1[28].xywx, r8.xyzx
 106  0x00000CDC:   mad r9.xyz, r3.wwww, cb1[30].xywx, r8.xyzx
 107  0x00000D04:   add r9.xyz, r9.xyzx, cb1[31].xywx
 108  0x00000D24:   add r1.z, r5.z, cb1[53].w
 109  0x00000D44:   mul r1.z, r1.z, cb1[53].z
 110  0x00000D64:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
 111  0x00000D8C:   mad r1.w, r5.z, cb1[26].z, cb1[27].z
 112  0x00000DB8:   movc r1.z, r2.w, r1.z, r1.w
 113  0x00000DDC:   mad r10.xyz, r1.zzzz, cb1[30].xywx, r6.xyzx
 114  0x00000E04:   add r10.xyz, r10.xyzx, cb1[31].xywx
 115  0x00000E24:   mad r11.xyz, r1.zzzz, cb1[30].xywx, r8.xyzx
 116  0x00000E4C:   add r11.xyz, r11.xyzx, cb1[31].xywx
 117  0x00000E6C:   div r1.zw, r7.xxxy, r7.zzzz
 118  0x00000E88:   div r7.xy, r10.xyxx, r10.zzzz
 119  0x00000EA4:   min r2.xy, r1.zwzz, r7.xyxx
 120  0x00000EC0:   div r1.zw, r9.xxxy, r9.zzzz
 121  0x00000EDC:   div r7.xy, r11.xyxx, r11.zzzz
 122  0x00000EF8:   max r5.xy, r1.zwzz, r7.xyxx
 123  0x00000F14:   add r1.z, r4.z, cb1[53].w
 124  0x00000F34:   mul r1.z, r1.z, cb1[53].z
 125  0x00000F54:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
 126  0x00000F7C:   mad r1.w, r4.z, cb1[26].z, cb1[27].z
 127  0x00000FA8:   movc r1.z, r2.w, r1.z, r1.w
 128  0x00000FCC:   mad r7.xyz, r1.zzzz, cb1[30].xywx, r6.xyzx
 129  0x00000FF4:   add r7.xyz, r7.xyzx, cb1[31].xywx
 130  0x00001014:   mad r9.xyz, r1.zzzz, cb1[30].xywx, r8.xyzx
 131  0x0000103C:   add r9.xyz, r9.xyzx, cb1[31].xywx
 132  0x0000105C:   add r1.z, r3.z, cb1[53].w
 133  0x0000107C:   mul r1.z, r1.z, cb1[53].z
 134  0x0000109C:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
 135  0x000010C4:   mad r1.w, r3.z, cb1[26].z, cb1[27].z
 136  0x000010F0:   movc r1.z, r2.w, r1.z, r1.w
 137  0x00001114:   mad r6.xyz, r1.zzzz, cb1[30].xywx, r6.xyzx
 138  0x0000113C:   add r6.xyz, r6.xyzx, cb1[31].xywx
 139  0x0000115C:   mad r8.xyz, r1.zzzz, cb1[30].xywx, r8.xyzx
 140  0x00001184:   add r8.xyz, r8.xyzx, cb1[31].xywx
 141  0x000011A4:   div r1.zw, r7.xxxy, r7.zzzz
 142  0x000011C0:   div r6.xy, r6.xyxx, r6.zzzz
 143  0x000011DC:   min r4.xy, r1.zwzz, r6.xyxx
 144  0x000011F8:   div r1.zw, r9.xxxy, r9.zzzz
 145  0x00001214:   div r6.xy, r8.xyxx, r8.zzzz
 146  0x00001230:   max r3.xy, r1.zwzz, r6.xyxx
 147  0x0000124C: endif 
 148  0x00001250: if_z r0.w
 149  0x0000125C:   mad r0.yz, r0.yyzy, cb1[119].zzwz, -cb1[54].wwzw
 150  0x0000128C:   div r0.yz, r0.yyzy, cb1[54].xxyx
 151  0x000012AC:   mul r0.yz, r1.yyyy, r0.yyzy
 152  0x000012C8:   mul r6.xyzw, r0.zzzz, cb1[41].xyzw
 153  0x000012E8:   mad r6.xyzw, r0.yyyy, cb1[40].xyzw, r6.xyzw
 154  0x00001310:   mad r6.xyzw, r1.yyyy, cb1[42].xyzw, r6.xyzw
 155  0x00001338:   add r6.xyzw, r6.xyzw, cb1[43].xyzw
 156  0x00001358:   div r0.yzw, r6.xxyz, r6.wwww
 157  0x00001374:   add r2.xyz, r2.xyzx, r5.xyzx
 158  0x00001390:   mul r6.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 159  0x000013B8:   mul r7.xyz, r6.yyyy, cb1[13].xyzx
 160  0x000013D8:   mad r6.xyw, r6.xxxx, cb1[12].xyxz, r7.xyxz
 161  0x00001400:   mad r6.xyz, r6.zzzz, cb1[14].xyzx, r6.xywx
 162  0x00001428:   add r6.xyz, r6.xyzx, cb1[15].xyzx
 163  0x00001448:   add r6.xyz, r6.xyzx, -cb1[58].xyzx
 164  0x0000146C:   mad r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -r5.xyzx
 165  0x000014A0:   dp3 r1.z, r2.xyzx, r2.xyzx
 166  0x000014BC:   add r2.xyz, r3.xyzx, r4.xyzx
 167  0x000014D8:   mul r4.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 168  0x00001500:   mul r5.xyw, r4.yyyy, cb1[13].xyxz
 169  0x00001520:   mad r4.xyw, r4.xxxx, cb1[12].xyxz, r5.xyxw
 170  0x00001548:   mad r4.xyz, r4.zzzz, cb1[14].xyzx, r4.xywx
 171  0x00001570:   add r4.xyz, r4.xyzx, cb1[15].xyzx
 172  0x00001590:   add r4.xyz, r4.xyzx, -cb1[58].xyzx
 173  0x000015B4:   mad r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -r3.xyzx
 174  0x000015E8:   dp3 r1.w, r2.xyzx, r2.xyzx
 175  0x00001604:   sqrt r1.zw, r1.zzzw
 176  0x00001618:   lt r2.x, r5.z, r1.y
 177  0x00001634:   mov r3.y, l(0)
 178  0x00001648:   mov r5.x, l(0)
 179  0x0000165C:   mov r2.y, r0.x
 180  0x00001670:   loop 
 181  0x00001674:     uge r2.z, r2.y, cb0[8].x
 182  0x00001694:     breakc_nz r2.z
 183  0x000016A0:     ld_indexable(buffer)(float,float,float,float) r7.xyzw, r2.yyyy, t2.xyzw
 184  0x000016C4:     f16tof32 r2.z, r7.w
 185  0x000016D8:     sincos r8.x, r9.x, r2.z
 186  0x000016F4:     ishl r2.z, r2.y, l(1)
 187  0x00001710:     ld_indexable(buffer)(float,float,float,float) r10.xyzw, r2.zzzz, t1.xyzw
 188  0x00001734:     bfi r2.z, l(31), l(1), r2.y, l(1)
 189  0x00001760:     ld_indexable(buffer)(float,float,float,float) r11.xyzw, r2.zzzz, t1.xyzw
 190  0x00001784:     lt r2.z, |r11.y|, |r11.x|
 191  0x000017A8:     dp2 r2.w, r11.xzxx, r11.xzxx
 192  0x000017C4:     sqrt r2.w, r2.w
 193  0x000017D8:     div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
 194  0x00001800:     mul r3.x, r2.w, -r11.z
 195  0x00001820:     mul r3.z, r2.w, r11.x
 196  0x0000183C:     dp2 r2.w, r11.yzyy, r11.yzyy
 197  0x00001858:     sqrt r2.w, r2.w
 198  0x0000186C:     div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
 199  0x00001894:     mul r5.y, r2.w, r11.z
 200  0x000018B0:     mul r5.z, r2.w, -r11.y
 201  0x000018D0:     movc r3.xzw, r2.zzzz, r3.xxyz, r5.xxyz
 202  0x000018F4:     mul r5.yzw, r3.zzwx, r11.zzxy
 203  0x00001910:     mad r5.yzw, r11.yyzx, r3.wwxz, -r5.yyzw
 204  0x00001938:     mad r2.z, r11.w, l(0.500000), r10.w
 205  0x0000195C:     div r2.z, r10.w, r2.z
 206  0x00001978:     mul r8.yzw, r2.zzzz, r11.xxyz
 207  0x00001994:     add r9.yzw, r6.xxyz, -r10.xxyz
 208  0x000019B4:     dp3 r11.x, r9.yzwy, r3.xzwx
 209  0x000019D0:     dp3 r11.y, r9.yzwy, r5.yzwy
 210  0x000019EC:     dp3 r11.z, r9.yzwy, r8.yzwy
 211  0x00001A08:     add r9.yzw, r4.xxyz, -r10.xxyz
 212  0x00001A28:     dp3 r10.x, r9.yzwy, r3.xzwx
 213  0x00001A44:     dp3 r10.y, r9.yzwy, r5.yzwy
 214  0x00001A60:     dp3 r10.z, r9.yzwy, r8.yzwy
 215  0x00001A7C:     dp3 r12.x, r7.xyzx, r3.xzwx
 216  0x00001A98:     dp3 r12.y, r7.xyzx, r5.yzwy
 217  0x00001AB4:     dp3 r12.z, r7.xyzx, r8.yzwy
 218  0x00001AD0:     dp3 r2.z, r12.xyzx, r12.xyzx
 219  0x00001AEC:     rsq r2.z, r2.z
 220  0x00001B00:     mul r3.xzw, r2.zzzz, r12.xxyz
 221  0x00001B1C:     add r2.z, r10.w, cb0[12].z
 222  0x00001B3C:     add r2.w, r1.z, r2.z
 223  0x00001B58:     dp3 r4.w, -r11.xyzx, -r11.xyzx
 224  0x00001B7C:     mul r2.w, r2.w, r2.w
 225  0x00001B98:     lt r2.w, r4.w, r2.w
 226  0x00001BB4:     add r5.y, r1.z, r10.w
 227  0x00001BD0:     div r5.z, r5.y, r8.x
 228  0x00001BEC:     mad r7.xyz, -r5.zzzz, r3.xzwx, r11.xyzx
 229  0x00001C14:     dp3 r5.z, -r7.xyzx, -r7.xyzx
 230  0x00001C38:     dp3 r5.w, r3.xzwx, -r7.xyzx
 231  0x00001C58:     lt r6.w, l(0.000000), r5.w
 232  0x00001C74:     mul r5.w, r5.w, r5.w
 233  0x00001C90:     mul r7.x, r9.x, r9.x
 234  0x00001CAC:     mul r5.z, r5.z, r7.x
 235  0x00001CC8:     ge r5.z, r5.w, r5.z
 236  0x00001CE4:     and r5.z, r5.z, r6.w
 237  0x00001D00:     dp3 r5.w, r3.xzwx, -r11.xyzx
 238  0x00001D20:     lt r6.w, l(0.000000), -r5.w
 239  0x00001D40:     mul r7.y, r5.w, r5.w
 240  0x00001D5C:     mul r7.z, r8.x, r8.x
 241  0x00001D78:     mul r7.w, r4.w, r7.z
 242  0x00001D94:     ge r7.y, r7.y, r7.w
 243  0x00001DB0:     and r6.w, r6.w, r7.y
 244  0x00001DCC:     mul r7.y, r5.y, r5.y
 245  0x00001DE8:     ge r4.w, r7.y, r4.w
 246  0x00001E04:     movc r4.w, r6.w, r4.w, l(-1)
 247  0x00001E28:     and r4.w, r4.w, r5.z
 248  0x00001E44:     add r5.y, -r5.y, r5.w
 249  0x00001E64:     lt r5.y, r5.y, cb0[12].z
 250  0x00001E84:     and r4.w, r4.w, r5.y
 251  0x00001EA0:     and r2.w, r2.w, r4.w
 252  0x00001EBC:     if_nz r2.w
 253  0x00001EC8:       imm_atomic_iadd r9.x, g0, l(0), l(1)
 254  0x00001EEC:       umin r2.w, r9.x, l(511)
 255  0x00001F08:       store_structured g2.x, r2.w, l(0), r2.y
 256  0x00001F2C:     endif 
 257  0x00001F30:     add r2.z, r1.w, r2.z
 258  0x00001F4C:     dp3 r2.w, -r10.xyzx, -r10.xyzx
 259  0x00001F70:     mul r2.z, r2.z, r2.z
 260  0x00001F8C:     lt r2.z, r2.w, r2.z
 261  0x00001FA8:     add r4.w, r1.w, r10.w
 262  0x00001FC4:     div r5.y, r4.w, r8.x
 263  0x00001FE0:     mad r5.yzw, -r5.yyyy, r3.xxzw, r10.xxyz
 264  0x00002008:     dp3 r6.w, -r5.yzwy, -r5.yzwy
 265  0x0000202C:     dp3 r5.y, r3.xzwx, -r5.yzwy
 266  0x0000204C:     lt r5.z, l(0.000000), r5.y
 267  0x00002068:     mul r5.y, r5.y, r5.y
 268  0x00002084:     mul r5.w, r6.w, r7.x
 269  0x000020A0:     ge r5.y, r5.y, r5.w
 270  0x000020BC:     and r5.y, r5.y, r5.z
 271  0x000020D8:     dp3 r3.x, r3.xzwx, -r10.xyzx
 272  0x000020F8:     lt r3.z, l(0.000000), -r3.x
 273  0x00002118:     mul r3.w, r3.x, r3.x
 274  0x00002134:     mul r5.z, r2.w, r7.z
 275  0x00002150:     ge r3.w, r3.w, r5.z
 276  0x0000216C:     and r3.z, r3.w, r3.z
 277  0x00002188:     mul r3.w, r4.w, r4.w
 278  0x000021A4:     ge r2.w, r3.w, r2.w
 279  0x000021C0:     movc r2.w, r3.z, r2.w, l(-1)
 280  0x000021E4:     and r2.w, r2.w, r5.y
 281  0x00002200:     add r3.x, -r4.w, r3.x
 282  0x00002220:     lt r3.x, r3.x, cb0[12].z
 283  0x00002240:     and r2.w, r2.w, r3.x
 284  0x0000225C:     and r2.z, r2.w, r2.z
 285  0x00002278:     if_nz r2.z
 286  0x00002284:       imm_atomic_iadd r7.x, g1, l(0), l(1)
 287  0x000022A8:       umin r2.z, r7.x, l(511)
 288  0x000022C4:       iadd r2.z, r2.z, l(512)
 289  0x000022E0:       store_structured g2.x, r2.z, l(0), r2.y
 290  0x00002304:     endif 
 291  0x00002308:     iadd r2.y, r2.y, l(64)
 292  0x00002324:   endloop 
 293  0x00002328:   sync_g_t
 294  0x0000232C:   ld_raw r0.x, l(0), g0.xxxx
 295  0x00002348:   ld_raw r1.z, l(0), g1.xxxx
 296  0x00002364:   movc r1.w, r2.x, r1.z, r0.x
 297  0x00002388:   umin r1.w, r1.w, l(512)
 298  0x000023A4:   iadd r0.x, r0.x, r1.z
 299  0x000023C0:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[12].z
 300  0x000023EC:   bfi r2.x, l(1), l(9), r2.x, l(0)
 301  0x00002418:   mov r3.y, l(0)
 302  0x0000242C:   mov r4.x, l(0)
 303  0x00002440:   mov r1.x, l(1.000000)
 304  0x00002454:   mov r2.y, l(0)
 305  0x00002468:   loop 
 306  0x0000246C:     uge r2.z, r2.y, r1.w
 307  0x00002488:     breakc_nz r2.z
 308  0x00002494:     iadd r2.z, r2.y, r2.x
 309  0x000024B0:     ld_structured r2.z, r2.z, l(0), g2.xxxx
 310  0x000024D4:     ld_indexable(buffer)(float,float,float,float) r5.xyzw, r2.zzzz, t2.xyzw
 311  0x000024F8:     f16tof32 r2.w, r5.w
 312  0x0000250C:     ushr r3.w, r5.w, l(16)
 313  0x00002528:     f16tof32 r3.w, r3.w
 314  0x0000253C:     sincos null, r4.w, r2.w
 315  0x00002554:     mad r4.w, -r4.w, l(6.283185), l(6.283185)
 316  0x0000257C:     ishl r5.w, r2.z, l(1)
 317  0x00002598:     ld_indexable(buffer)(float,float,float,float) r6.xyzw, r5.wwww, t1.xyzw
 318  0x000025BC:     add r5.w, -r5.z, -cb0[11].z
 319  0x000025E4:     dp2_sat r5.w, cb0[11].wwww, r5.wwww
 320  0x00002604:     add r5.w, -r5.w, l(1.000000)
 321  0x00002624:     mul r5.w, r5.w, r6.w
 322  0x00002640:     bfi r2.z, l(31), l(1), r2.z, l(1)
 323  0x0000266C:     ld_indexable(buffer)(float,float,float,float) r7.xyzw, r2.zzzz, t1.xyzw
 324  0x00002690:     lt r2.z, l(0.000000), r7.w
 325  0x000026AC:     if_nz r2.z
 326  0x000026B8:       lt r2.z, |r7.y|, |r7.x|
 327  0x000026DC:       dp2 r6.w, r7.xzxx, r7.xzxx
 328  0x000026F8:       sqrt r6.w, r6.w
 329  0x0000270C:       div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 330  0x00002734:       mul r3.x, r6.w, -r7.z
 331  0x00002754:       mul r3.z, r6.w, r7.x
 332  0x00002770:       dp2 r6.w, r7.yzyy, r7.yzyy
 333  0x0000278C:       sqrt r6.w, r6.w
 334  0x000027A0:       div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 335  0x000027C8:       mul r4.y, r6.w, r7.z
 336  0x000027E4:       mul r4.z, r6.w, -r7.y
 337  0x00002804:       movc r8.xyz, r2.zzzz, r3.xyzx, r4.xyzx
 338  0x00002828:       mul r9.xyz, r7.zxyz, r8.yzxy
 339  0x00002844:       mad r9.xyz, r7.yzxy, r8.zxyz, -r9.xyzx
 340  0x0000286C:       mad r2.z, r7.w, l(0.500000), r5.w
 341  0x00002890:       div r2.z, r5.w, r2.z
 342  0x000028AC:       mul r7.xyz, r2.zzzz, r7.xyzx
 343  0x000028C8:       add r10.xyz, r0.yzwy, -r6.xyzx
 344  0x000028E8:       dp3 r11.x, r10.xyzx, r8.xyzx
 345  0x00002904:       dp3 r11.y, r10.xyzx, r9.xyzx
 346  0x00002920:       dp3 r11.z, r10.xyzx, r7.xyzx
 347  0x0000293C:       dp3 r8.x, r5.xyzx, r8.xyzx
 348  0x00002958:       dp3 r8.y, r5.xyzx, r9.xyzx
 349  0x00002974:       dp3 r8.z, r5.xyzx, r7.xyzx
 350  0x00002990:       dp3 r2.z, r11.xyzx, r11.xyzx
 351  0x000029AC:       sqrt r2.z, r2.z
 352  0x000029C0:       div r7.xyz, -r11.xyzx, r2.zzzz
 353  0x000029E0:       dp3 r3.x, r8.xyzx, r8.xyzx
 354  0x000029FC:       rsq r3.x, r3.x
 355  0x00002A10:       mul r5.xyz, r3.xxxx, r8.xyzx
 356  0x00002A2C:     else 
 357  0x00002A30:       add r6.xyz, -r0.yzwy, r6.xyzx
 358  0x00002A50:       dp3 r3.x, r6.xyzx, r6.xyzx
 359  0x00002A6C:       sqrt r2.z, r3.x
 360  0x00002A80:       div r7.xyz, r6.xyzx, r2.zzzz
 361  0x00002A9C:     endif 
 362  0x00002AA0:     dp3 r3.x, r7.xyzx, r5.xyzx
 363  0x00002ABC:     mad r3.z, |r3.x|, l(-0.156583), l(1.570796)
 364  0x00002AE4:     add r4.y, -|r3.x|, l(1.000000)
 365  0x00002B04:     sqrt r4.y, r4.y
 366  0x00002B18:     mul r4.z, r3.z, r4.y
 367  0x00002B34:     ge r3.x, r3.x, l(0.000000)
 368  0x00002B50:     mad r3.z, -r3.z, r4.y, l(3.141593)
 369  0x00002B78:     movc r3.x, r3.x, r4.z, r3.z
 370  0x00002B9C:     div r3.z, r5.w, r2.z
 371  0x00002BB8:     lt r4.y, r3.z, l(1.000000)
 372  0x00002BD4:     div r4.z, l(1.000000, 1.000000, 1.000000, 1.000000), r3.z
 373  0x00002BFC:     movc r3.z, r4.y, r3.z, r4.z
 374  0x00002C20:     mul r4.z, r3.z, r3.z
 375  0x00002C3C:     mad r5.x, r4.z, l(0.087293), l(-0.301895)
 376  0x00002C60:     mad r4.z, r5.x, r4.z, l(1.000000)
 377  0x00002C84:     mul r5.x, r3.z, r4.z
 378  0x00002CA0:     mad r3.z, -r4.z, r3.z, l(1.570796)
 379  0x00002CC8:     movc r3.z, r4.y, r5.x, r3.z
 380  0x00002CEC:     max r4.y, r2.w, r3.z
 381  0x00002D08:     min r4.z, r2.w, r3.z
 382  0x00002D24:     add r4.y, -r4.z, r4.y
 383  0x00002D44:     ge r4.y, r4.y, r3.x
 384  0x00002D60:     sincos null, r4.z, r4.z
 385  0x00002D78:     mad r4.z, -r4.z, l(6.283185), l(6.283185)
 386  0x00002DA0:     add r5.x, r2.w, r3.z
 387  0x00002DBC:     ge r5.y, r3.x, r5.x
 388  0x00002DD8:     add r2.w, r2.w, -r3.z
 389  0x00002DF8:     add r3.x, -|r2.w|, r3.x
 390  0x00002E18:     add r2.w, -|r2.w|, r5.x
 391  0x00002E38:     div_sat r2.w, r3.x, r2.w
 392  0x00002E54:     add r2.w, -r2.w, l(1.000000)
 393  0x00002E74:     mad r3.x, r2.w, l(-2.000000), l(3.000000)
 394  0x00002E98:     mul r2.w, r2.w, r2.w
 395  0x00002EB4:     mul r2.w, r2.w, r3.x
 396  0x00002ED0:     mul r2.w, r4.z, r2.w
 397  0x00002EEC:     movc r2.w, r5.y, l(0), r2.w
 398  0x00002F10:     movc r2.w, r4.y, r4.z, r2.w
 399  0x00002F34:     div r2.w, r2.w, r4.w
 400  0x00002F50:     min r2.w, r2.w, l(1.000000)
 401  0x00002F6C:     add r2.w, -r2.w, l(1.000000)
 402  0x00002F8C:     mul r2.z, r1.z, r2.z
 403  0x00002FA8:     mad_sat r2.z, r2.z, l(3.000000), l(-2.000000)
 404  0x00002FCC:     add r3.x, -r2.w, l(1.000000)
 405  0x00002FEC:     mad r2.z, r2.z, r3.x, r2.w
 406  0x00003010:     add r2.w, -r3.w, l(1.000000)
 407  0x00003030:     mad r2.z, r2.z, r2.w, r3.w
 408  0x00003054:     mul r1.x, r1.x, r2.z
 409  0x00003070:     iadd r2.y, r2.y, l(1)
 410  0x0000308C:   endloop 
 411  0x00003090:   ieq r0.yz, vThreadIDInGroup.xxyx, l(0, 0, 0, 0)
 412  0x000030B4:   and r0.y, r0.z, r0.y
 413  0x000030D0:   ult r0.zw, vThreadGroupID.xxxy, cb0[13].xxxy
 414  0x000030EC:   and r0.z, r0.w, r0.z
 415  0x00003108:   and r0.y, r0.z, r0.y
 416  0x00003124:   if_nz r0.y
 417  0x00003130:     imad r0.y, vThreadGroupID.y, cb0[13].x, vThreadGroupID.x
 418  0x00003150:     store_uav_typed u1.xyzw, r0.yyyy, r0.xxxx
 419  0x0000316C:   endif 
 420  0x00003170: else 
 421  0x00003174:   mov r1.x, l(1.000000)
 422  0x00003188: endif 
 423  0x0000318C: store_uav_typed u0.xyzw, vThreadID.xyyy, r1.xyxx
 424  0x000031A4: ret 
// Approximately 0 instruction slots used
