//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      0x00000000: cs_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[20], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[119], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_resource_texture2d (float,float,float,float) t0
      0x00000048: dcl_resource_buffer (float,float,float,float) t1
      0x00000058: dcl_uav_typed_texture2d (float,float,float,float) u0
      0x00000068: dcl_uav_typed_buffer (uint,uint,uint,uint) u1
      0x00000078: dcl_input vThreadGroupID.xy
      0x00000080: dcl_input vThreadIDInGroup.xy
      0x00000088: dcl_input vThreadID.xy
      0x00000090: dcl_temps 12
      0x00000098: dcl_tgsm_raw g0, 4
      0x000000A8: dcl_tgsm_raw g1, 4
      0x000000B8: dcl_tgsm_structured g2, 4, 1024
      0x000000CC: dcl_tgsm_raw g3, 4
      0x000000DC: dcl_tgsm_raw g4, 4
      0x000000EC: dcl_tgsm_raw g5, 4
      0x000000FC: dcl_tgsm_raw g6, 4
      0x0000010C: dcl_thread_group 8, 8, 1
   0  0x0000011C: imad r0.x, vThreadIDInGroup.y, l(8), vThreadIDInGroup.x
   1  0x00000138: imad r0.yz, vThreadID.xxyx, cb0[18].wwww, cb0[17].xxyx
   2  0x00000160: utof r0.yz, r0.yyzy
   3  0x00000174: add r0.yz, r0.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
   4  0x0000019C: mul r1.xy, r0.yzyy, cb1[118].zwzz
   5  0x000001BC: sample_l_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t0.yzwx, s0, l(0.000000)
   6  0x000001F0: mad r1.x, r0.w, cb1[53].x, cb1[53].y
   7  0x0000021C: mad r0.w, r0.w, cb1[53].z, -cb1[53].w
   8  0x0000024C: div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
   9  0x00000274: add r1.y, r0.w, r1.x
  10  0x00000290: if_z r0.x
  11  0x0000029C:   store_raw g3.x, l(0), l(340282346638528859811704183484516925440.000000)
  12  0x000002B8:   store_raw g4.x, l(0), l(0)
  13  0x000002D4:   store_raw g5.x, l(0), l(340282346638528859811704183484516925440.000000)
  14  0x000002F0:   store_raw g6.x, l(0), l(0)
  15  0x0000030C:   store_raw g0.x, l(0), l(0)
  16  0x00000328:   store_raw g1.x, l(0), l(0)
  17  0x00000344: endif 
  18  0x00000348: sync_g_t
  19  0x0000034C: lt r0.w, r1.y, l(20000.000000)
  20  0x00000368: if_nz r0.w
  21  0x00000374:   atomic_umin g3, l(0), r1.y
  22  0x00000390:   atomic_umax g4, l(0), r1.y
  23  0x000003AC: endif 
  24  0x000003B0: sync_g_t
  25  0x000003B4: ld_raw r2.z, l(0), g3.xxxx
  26  0x000003D0: ld_raw r3.z, l(0), g4.xxxx
  27  0x000003EC: if_nz r0.w
  28  0x000003F8:   add r0.w, r2.z, r3.z
  29  0x00000414:   mul r0.w, r0.w, l(0.500000)
  30  0x00000430:   ge r1.z, r1.y, r0.w
  31  0x0000044C:   if_nz r1.z
  32  0x00000458:     atomic_umin g5, l(0), r1.y
  33  0x00000474:   endif 
  34  0x00000478:   ge r0.w, r0.w, r1.y
  35  0x00000494:   if_nz r0.w
  36  0x000004A0:     atomic_umax g6, l(0), r1.y
  37  0x000004BC:   endif 
  38  0x000004C0: endif 
  39  0x000004C4: sync_g_t
  40  0x000004C8: ld_raw r4.z, l(0), g5.xxxx
  41  0x000004E4: ld_raw r5.z, l(0), g6.xxxx
  42  0x00000500: ieq r0.w, r2.z, l(0x7f7fffff)
  43  0x0000051C: ieq r1.z, r3.z, l(0)
  44  0x00000538: and r0.w, r0.w, r1.z
  45  0x00000554: lt r1.z, |cb1[25].x|, l(0.000010)
  46  0x00000578: lt r1.w, |cb1[26].x|, l(0.000010)
  47  0x0000059C: and r1.z, r1.w, r1.z
  48  0x000005B8: if_nz r1.z
  49  0x000005C4:   mov r6.x, cb1[28].x
  50  0x000005DC:   mov r6.y, cb1[29].y
  51  0x000005F4:   add r1.zw, r6.xxxy, r6.xxxy
  52  0x00000610:   utof r7.xyzw, cb0[17].zwxy
  53  0x00000628:   mul r6.zw, r1.zzzw, r7.xxxy
  54  0x00000644:   mul r7.xy, cb0[18].xyxx, cb1[117].xyxx
  55  0x00000668:   div r6.zw, r6.zzzw, r7.xxxy
  56  0x00000684:   add r7.xy, r7.zwzz, -cb1[116].xyxx
  57  0x000006A8:   mul r1.zw, r1.zzzw, r7.xxxy
  58  0x000006C4:   mad r1.zw, r1.zzzw, cb1[117].zzzw, -r6.xxxy
  59  0x000006F0:   utof r6.xy, vThreadGroupID.xyxx
  60  0x00000700:   mad r6.xy, r6.xyxx, r6.zwzz, r1.zwzz
  61  0x00000724:   mul r6.xy, r6.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000)
  62  0x0000074C:   iadd r7.xy, vThreadGroupID.xyxx, l(1, 1, 0, 0)
  63  0x00000770:   utof r7.xy, r7.xyxx
  64  0x00000784:   mad r1.zw, r7.xxxy, r6.zzzw, r1.zzzw
  65  0x000007A8:   mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 1.000000, -1.000000)
  66  0x000007D0:   mul r6.zw, r2.zzzz, r6.xxxy
  67  0x000007EC:   mul r7.xy, r5.zzzz, r6.xyxx
  68  0x00000808:   min r2.xy, r6.zwzz, r7.xyxx
  69  0x00000824:   mul r6.zw, r1.zzzw, r2.zzzz
  70  0x00000840:   mul r7.xy, r1.zwzz, r5.zzzz
  71  0x0000085C:   max r5.xy, r6.zwzz, r7.xyxx
  72  0x00000878:   mul r6.zw, r4.zzzz, r6.xxxy
  73  0x00000894:   mul r6.xy, r3.zzzz, r6.xyxx
  74  0x000008B0:   min r4.xy, r6.xyxx, r6.zwzz
  75  0x000008CC:   mul r6.xy, r1.zwzz, r4.zzzz
  76  0x000008E8:   mul r1.zw, r1.zzzw, r3.zzzz
  77  0x00000904:   max r3.xy, r1.zwzz, r6.xyxx
  78  0x00000920: else 
  79  0x00000924:   ishl r1.zw, cb0[17].zzzw, l(0, 0, 1, 1)
  80  0x00000950:   utof r1.zw, r1.zzzw
  81  0x00000964:   mul r6.xy, cb0[18].xyxx, cb1[117].xyxx
  82  0x00000988:   div r1.zw, r1.zzzw, r6.xxxy
  83  0x000009A4:   utof r6.xy, cb0[17].xyxx
  84  0x000009BC:   add r6.xy, r6.xyxx, -cb1[116].xyxx
  85  0x000009E0:   mul r6.xy, r6.xyxx, cb1[117].zwzz
  86  0x00000A00:   mad r6.xy, r6.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  87  0x00000A3C:   utof r6.zw, vThreadGroupID.xxxy
  88  0x00000A4C:   mad r6.zw, r6.zzzw, r1.zzzw, r6.xxxy
  89  0x00000A70:   mul r6.zw, r6.zzzw, l(0.000000, 0.000000, 1.000000, -1.000000)
  90  0x00000A98:   iadd r7.xy, vThreadGroupID.xyxx, l(1, 1, 0, 0)
  91  0x00000ABC:   utof r7.xy, r7.xyxx
  92  0x00000AD0:   mad r1.zw, r7.xxxy, r1.zzzw, r6.xxxy
  93  0x00000AF4:   mul r1.zw, r1.zzzw, l(0.000000, 0.000000, 1.000000, -1.000000)
  94  0x00000B1C:   lt r2.w, cb1[27].w, l(1.000000)
  95  0x00000B3C:   add r3.w, r2.z, cb1[53].w
  96  0x00000B5C:   mul r3.w, r3.w, cb1[53].z
  97  0x00000B7C:   div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  98  0x00000BA4:   mad r4.w, r2.z, cb1[26].z, cb1[27].z
  99  0x00000BD0:   movc r3.w, r2.w, r3.w, r4.w
 100  0x00000BF4:   mul r6.xyw, r6.wwww, cb1[29].xyxw
 101  0x00000C14:   mad r6.xyz, r6.zzzz, cb1[28].xywx, r6.xywx
 102  0x00000C3C:   mad r7.xyz, r3.wwww, cb1[30].xywx, r6.xyzx
 103  0x00000C64:   add r7.xyz, r7.xyzx, cb1[31].xywx
 104  0x00000C84:   mul r8.xyz, r1.wwww, cb1[29].xywx
 105  0x00000CA4:   mad r8.xyz, r1.zzzz, cb1[28].xywx, r8.xyzx
 106  0x00000CCC:   mad r9.xyz, r3.wwww, cb1[30].xywx, r8.xyzx
 107  0x00000CF4:   add r9.xyz, r9.xyzx, cb1[31].xywx
 108  0x00000D14:   add r1.z, r5.z, cb1[53].w
 109  0x00000D34:   mul r1.z, r1.z, cb1[53].z
 110  0x00000D54:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
 111  0x00000D7C:   mad r1.w, r5.z, cb1[26].z, cb1[27].z
 112  0x00000DA8:   movc r1.z, r2.w, r1.z, r1.w
 113  0x00000DCC:   mad r10.xyz, r1.zzzz, cb1[30].xywx, r6.xyzx
 114  0x00000DF4:   add r10.xyz, r10.xyzx, cb1[31].xywx
 115  0x00000E14:   mad r11.xyz, r1.zzzz, cb1[30].xywx, r8.xyzx
 116  0x00000E3C:   add r11.xyz, r11.xyzx, cb1[31].xywx
 117  0x00000E5C:   div r1.zw, r7.xxxy, r7.zzzz
 118  0x00000E78:   div r7.xy, r10.xyxx, r10.zzzz
 119  0x00000E94:   min r2.xy, r1.zwzz, r7.xyxx
 120  0x00000EB0:   div r1.zw, r9.xxxy, r9.zzzz
 121  0x00000ECC:   div r7.xy, r11.xyxx, r11.zzzz
 122  0x00000EE8:   max r5.xy, r1.zwzz, r7.xyxx
 123  0x00000F04:   add r1.z, r4.z, cb1[53].w
 124  0x00000F24:   mul r1.z, r1.z, cb1[53].z
 125  0x00000F44:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
 126  0x00000F6C:   mad r1.w, r4.z, cb1[26].z, cb1[27].z
 127  0x00000F98:   movc r1.z, r2.w, r1.z, r1.w
 128  0x00000FBC:   mad r7.xyz, r1.zzzz, cb1[30].xywx, r6.xyzx
 129  0x00000FE4:   add r7.xyz, r7.xyzx, cb1[31].xywx
 130  0x00001004:   mad r9.xyz, r1.zzzz, cb1[30].xywx, r8.xyzx
 131  0x0000102C:   add r9.xyz, r9.xyzx, cb1[31].xywx
 132  0x0000104C:   add r1.z, r3.z, cb1[53].w
 133  0x0000106C:   mul r1.z, r1.z, cb1[53].z
 134  0x0000108C:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.z
 135  0x000010B4:   mad r1.w, r3.z, cb1[26].z, cb1[27].z
 136  0x000010E0:   movc r1.z, r2.w, r1.z, r1.w
 137  0x00001104:   mad r6.xyz, r1.zzzz, cb1[30].xywx, r6.xyzx
 138  0x0000112C:   add r6.xyz, r6.xyzx, cb1[31].xywx
 139  0x0000114C:   mad r8.xyz, r1.zzzz, cb1[30].xywx, r8.xyzx
 140  0x00001174:   add r8.xyz, r8.xyzx, cb1[31].xywx
 141  0x00001194:   div r1.zw, r7.xxxy, r7.zzzz
 142  0x000011B0:   div r6.xy, r6.xyxx, r6.zzzz
 143  0x000011CC:   min r4.xy, r1.zwzz, r6.xyxx
 144  0x000011E8:   div r1.zw, r9.xxxy, r9.zzzz
 145  0x00001204:   div r6.xy, r8.xyxx, r8.zzzz
 146  0x00001220:   max r3.xy, r1.zwzz, r6.xyxx
 147  0x0000123C: endif 
 148  0x00001240: if_z r0.w
 149  0x0000124C:   mad r0.yz, r0.yyzy, cb1[118].zzwz, -cb1[54].wwzw
 150  0x0000127C:   div r0.yz, r0.yyzy, cb1[54].xxyx
 151  0x0000129C:   mul r0.yz, r1.yyyy, r0.yyzy
 152  0x000012B8:   mul r6.xyzw, r0.zzzz, cb1[41].xyzw
 153  0x000012D8:   mad r6.xyzw, r0.yyyy, cb1[40].xyzw, r6.xyzw
 154  0x00001300:   mad r6.xyzw, r1.yyyy, cb1[42].xyzw, r6.xyzw
 155  0x00001328:   add r6.xyzw, r6.xyzw, cb1[43].xyzw
 156  0x00001348:   div r0.yzw, r6.xxyz, r6.wwww
 157  0x00001364:   add r2.xyz, r2.xyzx, r5.xyzx
 158  0x00001380:   mul r6.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 159  0x000013A8:   mul r7.xyz, r6.yyyy, cb1[13].xyzx
 160  0x000013C8:   mad r6.xyw, r6.xxxx, cb1[12].xyxz, r7.xyxz
 161  0x000013F0:   mad r6.xyz, r6.zzzz, cb1[14].xyzx, r6.xywx
 162  0x00001418:   add r6.xyz, r6.xyzx, cb1[15].xyzx
 163  0x00001438:   add r6.xyz, r6.xyzx, -cb1[58].xyzx
 164  0x0000145C:   mad r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -r5.xyzx
 165  0x00001490:   dp3 r1.z, r2.xyzx, r2.xyzx
 166  0x000014AC:   add r2.xyz, r3.xyzx, r4.xyzx
 167  0x000014C8:   mul r4.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 168  0x000014F0:   mul r5.xyw, r4.yyyy, cb1[13].xyxz
 169  0x00001510:   mad r4.xyw, r4.xxxx, cb1[12].xyxz, r5.xyxw
 170  0x00001538:   mad r4.xyz, r4.zzzz, cb1[14].xyzx, r4.xywx
 171  0x00001560:   add r4.xyz, r4.xyzx, cb1[15].xyzx
 172  0x00001580:   add r4.xyz, r4.xyzx, -cb1[58].xyzx
 173  0x000015A4:   mad r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -r3.xyzx
 174  0x000015D8:   dp3 r1.w, r2.xyzx, r2.xyzx
 175  0x000015F4:   sqrt r1.zw, r1.zzzw
 176  0x00001608:   sincos r2.x, r3.x, cb0[16].x
 177  0x00001628:   lt r2.y, r5.z, r1.y
 178  0x00001644:   mul r2.z, r3.x, r3.x
 179  0x00001660:   mul r2.w, r2.x, r2.x
 180  0x0000167C:   mov r3.y, r0.x
 181  0x00001690:   loop 
 182  0x00001694:     uge r3.z, r3.y, cb0[12].x
 183  0x000016B4:     breakc_nz r3.z
 184  0x000016C0:     ishl r3.z, r3.y, l(1)
 185  0x000016DC:     ld_indexable(buffer)(float,float,float,float) r5.xyzw, r3.zzzz, t1.xyzw
 186  0x00001700:     bfi r3.z, l(31), l(1), r3.y, l(1)
 187  0x0000172C:     ld_indexable(buffer)(float,float,float,float) r3.z, r3.zzzz, t1.xywz
 188  0x00001750:     mad r3.z, r3.z, l(0.500000), r5.w
 189  0x00001774:     add r3.w, r3.z, cb0[19].x
 190  0x00001794:     add r4.w, r1.z, r3.w
 191  0x000017B0:     add r7.xyz, -r6.xyzx, r5.xyzx
 192  0x000017D0:     dp3 r5.w, r7.xyzx, r7.xyzx
 193  0x000017EC:     mul r4.w, r4.w, r4.w
 194  0x00001808:     lt r4.w, r5.w, r4.w
 195  0x00001824:     add r6.w, r1.z, r3.z
 196  0x00001840:     div r7.w, r6.w, r2.x
 197  0x0000185C:     mad r8.xyz, -r7.wwww, cb0[13].xyzx, r6.xyzx
 198  0x00001888:     add r8.xyz, r5.xyzx, -r8.xyzx
 199  0x000018A8:     dp3 r7.w, r8.xyzx, r8.xyzx
 200  0x000018C4:     dp3 r8.x, cb0[13].xyzx, r8.xyzx
 201  0x000018E4:     lt r8.y, l(0.000000), r8.x
 202  0x00001900:     mul r8.x, r8.x, r8.x
 203  0x0000191C:     mul r7.w, r2.z, r7.w
 204  0x00001938:     ge r7.w, r8.x, r7.w
 205  0x00001954:     and r7.w, r7.w, r8.y
 206  0x00001970:     dp3 r7.x, cb0[13].xyzx, r7.xyzx
 207  0x00001990:     lt r7.y, l(0.000000), -r7.x
 208  0x000019B0:     mul r7.z, r7.x, r7.x
 209  0x000019CC:     mul r8.x, r2.w, r5.w
 210  0x000019E8:     ge r7.z, r7.z, r8.x
 211  0x00001A04:     and r7.y, r7.z, r7.y
 212  0x00001A20:     mul r7.z, r6.w, r6.w
 213  0x00001A3C:     ge r5.w, r7.z, r5.w
 214  0x00001A58:     movc r5.w, r7.y, r5.w, l(-1)
 215  0x00001A7C:     and r5.w, r5.w, r7.w
 216  0x00001A98:     add r6.w, -r6.w, r7.x
 217  0x00001AB8:     lt r6.w, r6.w, cb0[19].x
 218  0x00001AD8:     and r5.w, r5.w, r6.w
 219  0x00001AF4:     and r4.w, r4.w, r5.w
 220  0x00001B10:     if_nz r4.w
 221  0x00001B1C:       imm_atomic_iadd r7.x, g0, l(0), l(1)
 222  0x00001B40:       umin r4.w, r7.x, l(511)
 223  0x00001B5C:       store_structured g2.x, r4.w, l(0), r3.y
 224  0x00001B80:     endif 
 225  0x00001B84:     add r3.zw, r1.wwww, r3.zzzw
 226  0x00001BA0:     add r7.xyz, -r4.xyzx, r5.xyzx
 227  0x00001BC0:     dp3 r4.w, r7.xyzx, r7.xyzx
 228  0x00001BDC:     mul r3.w, r3.w, r3.w
 229  0x00001BF8:     lt r3.w, r4.w, r3.w
 230  0x00001C14:     div r5.w, r3.z, r2.x
 231  0x00001C30:     mad r8.xyz, -r5.wwww, cb0[13].xyzx, r4.xyzx
 232  0x00001C5C:     add r5.xyz, r5.xyzx, -r8.xyzx
 233  0x00001C7C:     dp3 r5.w, r5.xyzx, r5.xyzx
 234  0x00001C98:     dp3 r5.x, cb0[13].xyzx, r5.xyzx
 235  0x00001CB8:     lt r5.y, l(0.000000), r5.x
 236  0x00001CD4:     mul r5.x, r5.x, r5.x
 237  0x00001CF0:     mul r5.z, r2.z, r5.w
 238  0x00001D0C:     ge r5.x, r5.x, r5.z
 239  0x00001D28:     and r5.x, r5.x, r5.y
 240  0x00001D44:     dp3 r5.y, cb0[13].xyzx, r7.xyzx
 241  0x00001D64:     lt r5.z, l(0.000000), -r5.y
 242  0x00001D84:     mul r5.w, r5.y, r5.y
 243  0x00001DA0:     mul r6.w, r2.w, r4.w
 244  0x00001DBC:     ge r5.w, r5.w, r6.w
 245  0x00001DD8:     and r5.z, r5.w, r5.z
 246  0x00001DF4:     mul r5.w, r3.z, r3.z
 247  0x00001E10:     ge r4.w, r5.w, r4.w
 248  0x00001E2C:     movc r4.w, r5.z, r4.w, l(-1)
 249  0x00001E50:     and r4.w, r4.w, r5.x
 250  0x00001E6C:     add r3.z, -r3.z, r5.y
 251  0x00001E8C:     lt r3.z, r3.z, cb0[19].x
 252  0x00001EAC:     and r3.z, r3.z, r4.w
 253  0x00001EC8:     and r3.z, r3.z, r3.w
 254  0x00001EE4:     if_nz r3.z
 255  0x00001EF0:       imm_atomic_iadd r5.x, g1, l(0), l(1)
 256  0x00001F14:       umin r3.z, r5.x, l(511)
 257  0x00001F30:       iadd r3.z, r3.z, l(512)
 258  0x00001F4C:       store_structured g2.x, r3.z, l(0), r3.y
 259  0x00001F70:     endif 
 260  0x00001F74:     iadd r3.y, r3.y, l(64)
 261  0x00001F90:   endloop 
 262  0x00001F94:   sync_g_t
 263  0x00001F98:   ld_raw r0.x, l(0), g0.xxxx
 264  0x00001FB4:   ld_raw r1.z, l(0), g1.xxxx
 265  0x00001FD0:   movc r1.w, r2.y, r1.z, r0.x
 266  0x00001FF4:   umin r1.w, r1.w, l(512)
 267  0x00002010:   iadd r0.x, r0.x, r1.z
 268  0x0000202C:   div r1.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[19].x
 269  0x00002058:   mad r2.x, -r3.x, l(6.283185), l(6.283185)
 270  0x00002080:   bfi r2.y, l(1), l(9), r2.y, l(0)
 271  0x000020AC:   mov r1.x, l(1.000000)
 272  0x000020C0:   mov r2.z, l(0)
 273  0x000020D4:   loop 
 274  0x000020D8:     uge r2.w, r2.z, r1.w
 275  0x000020F4:     breakc_nz r2.w
 276  0x00002100:     iadd r2.w, r2.z, r2.y
 277  0x0000211C:     ld_structured r2.w, r2.w, l(0), g2.xxxx
 278  0x00002140:     ishl r3.x, r2.w, l(1)
 279  0x0000215C:     ld_indexable(buffer)(float,float,float,float) r3.xyzw, r3.xxxx, t1.xyzw
 280  0x00002180:     bfi r2.w, l(31), l(1), r2.w, l(1)
 281  0x000021AC:     ld_indexable(buffer)(float,float,float,float) r4.xyzw, r2.wwww, t1.xyzw
 282  0x000021D0:     lt r2.w, l(0.000000), r4.w
 283  0x000021EC:     if_nz r2.w
 284  0x000021F8:       add r5.xyz, -r0.yzwy, r3.xyzx
 285  0x00002218:       mul r4.xyzw, r4.wwww, r4.xyzw
 286  0x00002234:       mad r6.xyz, -r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r5.xyzx
 287  0x00002268:       mad r5.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r5.xyzx
 288  0x00002298:       dp3 r2.w, cb0[13].xyzx, r4.xyzx
 289  0x000022B8:       mad r7.xyz, r2.wwww, cb0[13].xyzx, -r4.xyzx
 290  0x000022E4:       mad r2.w, -r2.w, r2.w, r4.w
 291  0x0000230C:       dp3 r4.w, r6.xyzx, r7.xyzx
 292  0x00002328:       div_sat r2.w, r4.w, r2.w
 293  0x00002344:       mad r4.xyz, r2.wwww, r4.xyzx, r6.xyzx
 294  0x00002368:       dp3 r2.w, r4.xyzx, r4.xyzx
 295  0x00002384:       sqrt r2.w, r2.w
 296  0x00002398:       div r4.xyz, r4.xyzx, r2.wwww
 297  0x000023B4:       dp3 r4.w, r6.xyzx, r6.xyzx
 298  0x000023D0:       sqrt r4.w, r4.w
 299  0x000023E4:       min r2.w, r2.w, r4.w
 300  0x00002400:       dp3 r4.w, r5.xyzx, r5.xyzx
 301  0x0000241C:       sqrt r4.w, r4.w
 302  0x00002430:       min r2.w, r2.w, r4.w
 303  0x0000244C:     else 
 304  0x00002450:       add r3.xyz, -r0.yzwy, r3.xyzx
 305  0x00002470:       dp3 r4.w, r3.xyzx, r3.xyzx
 306  0x0000248C:       sqrt r2.w, r4.w
 307  0x000024A0:       div r4.xyz, r3.xyzx, r2.wwww
 308  0x000024BC:     endif 
 309  0x000024C0:     dp3 r3.x, r4.xyzx, cb0[13].xyzx
 310  0x000024E0:     mad r3.y, |r3.x|, l(-0.156583), l(1.570796)
 311  0x00002508:     add r3.z, -|r3.x|, l(1.000000)
 312  0x00002528:     sqrt r3.z, r3.z
 313  0x0000253C:     mul r4.x, r3.z, r3.y
 314  0x00002558:     ge r3.x, r3.x, l(0.000000)
 315  0x00002574:     mad r3.y, -r3.y, r3.z, l(3.141593)
 316  0x0000259C:     movc r3.x, r3.x, r4.x, r3.y
 317  0x000025C0:     div r3.y, r3.w, r2.w
 318  0x000025DC:     lt r3.z, r3.y, l(1.000000)
 319  0x000025F8:     div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.y
 320  0x00002620:     movc r3.y, r3.z, r3.y, r3.w
 321  0x00002644:     mul r3.w, r3.y, r3.y
 322  0x00002660:     mad r4.x, r3.w, l(0.087293), l(-0.301895)
 323  0x00002684:     mad r3.w, r4.x, r3.w, l(1.000000)
 324  0x000026A8:     mul r4.x, r3.y, r3.w
 325  0x000026C4:     mad r3.y, -r3.w, r3.y, l(1.570796)
 326  0x000026EC:     movc r3.y, r3.z, r4.x, r3.y
 327  0x00002710:     max r3.z, r3.y, cb0[16].x
 328  0x00002730:     min r3.w, r3.y, cb0[16].x
 329  0x00002750:     add r3.z, -r3.w, r3.z
 330  0x00002770:     ge r3.z, r3.z, r3.x
 331  0x0000278C:     sincos null, r3.w, r3.w
 332  0x000027A4:     mad r3.w, -r3.w, l(6.283185), l(6.283185)
 333  0x000027CC:     add r4.x, r3.y, cb0[16].x
 334  0x000027EC:     ge r4.y, r3.x, r4.x
 335  0x00002808:     add r3.y, -r3.y, cb0[16].x
 336  0x0000282C:     add r3.x, -|r3.y|, r3.x
 337  0x0000284C:     add r3.y, -|r3.y|, r4.x
 338  0x0000286C:     div_sat r3.x, r3.x, r3.y
 339  0x00002888:     add r3.x, -r3.x, l(1.000000)
 340  0x000028A8:     mad r3.y, r3.x, l(-2.000000), l(3.000000)
 341  0x000028CC:     mul r3.x, r3.x, r3.x
 342  0x000028E8:     mul r3.x, r3.x, r3.y
 343  0x00002904:     mul r3.x, r3.w, r3.x
 344  0x00002920:     movc r3.x, r4.y, l(0), r3.x
 345  0x00002944:     movc r3.x, r3.z, r3.w, r3.x
 346  0x00002968:     div r3.x, r3.x, r2.x
 347  0x00002984:     min r3.x, r3.x, l(1.000000)
 348  0x000029A0:     add r3.x, -r3.x, l(1.000000)
 349  0x000029C0:     mul r2.w, r1.z, r2.w
 350  0x000029DC:     mad_sat r2.w, r2.w, l(3.000000), l(-2.000000)
 351  0x00002A00:     add r3.y, -r3.x, l(1.000000)
 352  0x00002A20:     mad r2.w, r2.w, r3.y, r3.x
 353  0x00002A44:     mul r1.x, r1.x, r2.w
 354  0x00002A60:     iadd r2.z, r2.z, l(1)
 355  0x00002A7C:   endloop 
 356  0x00002A80:   ieq r0.yz, vThreadIDInGroup.xxyx, l(0, 0, 0, 0)
 357  0x00002AA4:   and r0.y, r0.z, r0.y
 358  0x00002AC0:   ult r0.zw, vThreadGroupID.xxxy, cb0[19].yyyz
 359  0x00002ADC:   and r0.z, r0.w, r0.z
 360  0x00002AF8:   and r0.y, r0.z, r0.y
 361  0x00002B14:   if_nz r0.y
 362  0x00002B20:     imad r0.y, vThreadGroupID.y, cb0[19].y, vThreadGroupID.x
 363  0x00002B40:     store_uav_typed u1.xyzw, r0.yyyy, r0.xxxx
 364  0x00002B5C:   endif 
 365  0x00002B60: else 
 366  0x00002B64:   mov r1.x, l(1.000000)
 367  0x00002B78: endif 
 368  0x00002B7C: store_uav_typed u0.xyzw, vThreadID.xyyy, r1.xyxx
 369  0x00002B94: ret 
// Approximately 0 instruction slots used
