//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      0x00000000: cs_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[36], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[133], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_sampler s1, mode_default
      0x00000044: dcl_sampler s2, mode_default
      0x00000050: dcl_resource_texture2d (float,float,float,float) t0
      0x00000060: dcl_resource_texture2d (float,float,float,float) t1
      0x00000070: dcl_resource_texture2d (float,float,float,float) t2
      0x00000080: dcl_uav_typed_texture2d (float,float,float,float) u0
      0x00000090: dcl_input vThreadID.xy
      0x00000098: dcl_temps 14
      0x000000A0: dcl_thread_group 16, 16, 1
   0  0x000000B0: utof r0.xyzw, vThreadID.xyxy
   1  0x000000C0: add r0.xyzw, r0.xyzw, cb0[32].zwzw
   2  0x000000E0: ftoi r1.xyzw, r0.zwww
   3  0x000000F4: round_z r0.xyzw, r0.xyzw
   4  0x00000108: add r0.xyzw, r0.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
   5  0x00000130: mul r2.xy, r0.zwzz, cb0[29].xxxx
   6  0x00000150: mul r2.zw, r2.xxxy, cb1[132].zzzw
   7  0x00000170: sample_l_indexable(texture2d)(float,float,float,float) r3.x, r2.zwzz, t0.xyzw, s0, l(0.000000)
   8  0x000001A4: mad r3.y, r3.x, cb1[66].x, cb1[66].y
   9  0x000001D0: mad r3.z, r3.x, cb1[66].z, -cb1[66].w
  10  0x00000200: div r3.z, l(1.000000, 1.000000, 1.000000, 1.000000), r3.z
  11  0x00000228: add r4.z, r3.z, r3.y
  12  0x00000244: mad r3.y, r4.z, cb0[31].x, cb0[31].y
  13  0x00000270: lt r3.z, r3.y, l(1.000000)
  14  0x0000028C: if_nz r3.z
  15  0x00000298:   mad r3.zw, r0.zzzw, cb0[29].xxxx, -cb1[130].xxxy
  16  0x000002C8:   mad r3.zw, r3.zzzw, cb1[131].zzzw, l(0.000000, 0.000000, -0.500000, -0.500000)
  17  0x000002FC:   mul r3.zw, r4.zzzz, r3.zzzw
  18  0x00000318:   mul r5.y, cb0[28].w, cb0[30].w
  19  0x0000033C:   div r6.x, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[30].w
  20  0x00000368:   div r6.y, l(1.000000, 1.000000, 1.000000, 1.000000), r5.y
  21  0x00000390:   mov r6.z, l(1.000000)
  22  0x000003A4:   mad r7.xyzw, r0.zwzw, cb0[29].xxxx, l(-1.000000, 0.000000, 0.000000, -1.000000)
  23  0x000003D8:   mul r7.xyzw, r7.xyzw, cb1[132].zwzw
  24  0x000003F8:   sample_l_indexable(texture2d)(float,float,float,float) r4.w, r7.xyxx, t0.yzwx, s0, l(0.000000)
  25  0x0000042C:   sample_l_indexable(texture2d)(float,float,float,float) r5.w, r7.zwzz, t0.yzwx, s0, l(0.000000)
  26  0x00000460:   mad r0.xyzw, r0.xyzw, cb0[29].xxxx, l(1.000000, 0.000000, 0.000000, 1.000000)
  27  0x00000494:   mul r7.xyzw, r0.xyzw, cb1[132].zwzw
  28  0x000004B4:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r7.xyxx, t0.yzwx, s0, l(0.000000)
  29  0x000004E8:   sample_l_indexable(texture2d)(float,float,float,float) r7.x, r7.zwzz, t0.xyzw, s0, l(0.000000)
  30  0x0000051C:   add r4.w, r3.x, -r4.w
  31  0x0000053C:   add r6.w, -r3.x, r6.w
  32  0x0000055C:   lt r7.y, |r4.w|, |r6.w|
  33  0x00000580:   movc r4.w, r7.y, r4.w, r6.w
  34  0x000005A4:   add r5.w, r3.x, -r5.w
  35  0x000005C4:   add r6.w, -r3.x, r7.x
  36  0x000005E4:   lt r7.x, |r5.w|, |r6.w|
  37  0x00000608:   movc r5.w, r7.x, r5.w, r6.w
  38  0x0000062C:   mul r7.xyzw, r2.yyyy, cb1[46].xyzw
  39  0x0000064C:   mad r7.xyzw, r2.xxxx, cb1[45].xyzw, r7.xyzw
  40  0x00000674:   mad r7.xyzw, r3.xxxx, cb1[47].xyzw, r7.xyzw
  41  0x0000069C:   add r7.xyzw, r7.xyzw, cb1[48].xyzw
  42  0x000006BC:   div r7.xyz, r7.yzxy, r7.wwww
  43  0x000006D8:   add r2.x, r3.x, r4.w
  44  0x000006F4:   mul r8.xyzw, r0.yyyy, cb1[46].xyzw
  45  0x00000714:   mad r8.xyzw, r0.xxxx, cb1[45].xyzw, r8.xyzw
  46  0x0000073C:   mad r8.xyzw, r2.xxxx, cb1[47].xyzw, r8.xyzw
  47  0x00000764:   add r8.xyzw, r8.xyzw, cb1[48].xyzw
  48  0x00000784:   div r8.xyz, r8.zxyz, r8.wwww
  49  0x000007A0:   add r8.xyz, -r7.yzxy, r8.xyzx
  50  0x000007C0:   add r0.x, r3.x, r5.w
  51  0x000007DC:   mul r9.xyzw, r0.wwww, cb1[46].xyzw
  52  0x000007FC:   mad r9.xyzw, r0.zzzz, cb1[45].xyzw, r9.xyzw
  53  0x00000824:   mad r0.xyzw, r0.xxxx, cb1[47].xyzw, r9.xyzw
  54  0x0000084C:   add r0.xyzw, r0.xyzw, cb1[48].xyzw
  55  0x0000086C:   div r0.xyz, r0.yzxy, r0.wwww
  56  0x00000888:   add r0.xyz, -r7.xyzx, r0.xyzx
  57  0x000008A8:   mul r7.xyz, r0.xyzx, r8.xyzx
  58  0x000008C4:   mad r0.xyz, r8.zxyz, r0.yzxy, -r7.xyzx
  59  0x000008EC:   mul r7.xyz, r0.yyyy, cb1[14].xyzx
  60  0x0000090C:   mad r0.xyw, r0.xxxx, cb1[13].xyxz, r7.xyxz
  61  0x00000934:   mad r0.xyz, r0.zzzz, cb1[15].xyzx, r0.xywx
  62  0x0000095C:   dp3 r0.w, r0.xyzx, r0.xyzx
  63  0x00000978:   rsq r0.w, r0.w
  64  0x0000098C:   mul r0.xyz, r0.wwww, r0.xyzx
  65  0x000009A8:   mul r4.xy, r3.zwzz, l(2.000000, -2.000000, 0.000000, 0.000000)
  66  0x000009D0:   add r2.xy, -r4.zzzz, l(1.000000, 1000.000000, 0.000000, 0.000000)
  67  0x000009FC:   mad r2.xy, cb0[29].zzzz, r2.xyxx, r4.zzzz
  68  0x00000A24:   mul r0.w, r2.x, cb0[28].z
  69  0x00000A44:   mul r2.x, r4.z, cb0[27].y
  70  0x00000A64:   mul r2.x, r2.x, cb0[29].x
  71  0x00000A84:   mov r5.x, cb0[30].w
  72  0x00000A9C:   mov r5.z, l(1.000000)
  73  0x00000AB0:   mul r3.xzw, r0.xxyz, r5.xxyz
  74  0x00000ACC:   mad r3.xzw, r2.xxxx, r3.xxzw, r4.xxyz
  75  0x00000AF0:   mad r2.xz, r2.zzwz, cb0[28].xxyx, cb0[30].xxyx
  76  0x00000B1C:   sample_l_indexable(texture2d)(float,float,float,float) r2.xz, r2.xzxx, t2.xzyw, s2, l(0.000000)
  77  0x00000B50:   mad r2.xzw, r2.xxxz, l(2.000000, 0.000000, 2.000000, 2.000000), l(-1.000000, 0.000000, -1.000000, -1.000000)
  78  0x00000B8C:   mul r4.yzw, r0.wwww, r2.xxzw
  79  0x00000BA8:   div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  80  0x00000BD0:   mul r5.xyzw, r0.wwww, r5.xyxy
  81  0x00000BEC:   mov r4.x, -r4.w
  82  0x00000C04:   mul r4.xyzw, r4.xyzw, r5.xyzw
  83  0x00000C20:   div r2.xz, r3.xxzx, r3.wwww
  84  0x00000C3C:   mul r0.w, r2.y, l(0.080000)
  85  0x00000C58:   mul r0.xyz, r0.wwww, r0.xyzx
  86  0x00000C74:   mul r5.xyzw, cb0[31].zzzz, l(0.027778, 0.055556, 0.083333, 0.166667)
  87  0x00000CA0:   log r5.xyzw, r5.xyzw
  88  0x00000CB4:   max r5.xyzw, r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
  89  0x00000CDC:   mad r7.xyzw, r4.xyxy, l(0.066667, 0.066667, 0.200000, 0.200000), r2.xzxz
  90  0x00000D0C:   mad r8.xyzw, -r4.xyxy, l(0.066667, 0.066667, 0.200000, 0.200000), r2.xzxz
  91  0x00000D40:   mad r9.xyzw, cb0[35].xyxy, r7.xyzw, cb0[35].zwzw
  92  0x00000D6C:   sample_l_indexable(texture2d)(float,float,float,float) r0.w, r9.xyxx, t1.yzwx, s1, r5.x
  93  0x00000DA0:   mad r10.xyzw, cb0[35].xyxy, r8.xyzw, cb0[35].zwzw
  94  0x00000DCC:   sample_l_indexable(texture2d)(float,float,float,float) r2.y, r10.xyxx, t1.yxzw, s1, r5.x
  95  0x00000E00:   mad r2.w, r0.w, cb1[66].x, cb1[66].y
  96  0x00000E2C:   mad r0.w, r0.w, cb1[66].z, -cb1[66].w
  97  0x00000E5C:   div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
  98  0x00000E84:   add r11.z, r0.w, r2.w
  99  0x00000EA0:   mad r0.w, r2.y, cb1[66].x, cb1[66].y
 100  0x00000ECC:   mad r2.y, r2.y, cb1[66].z, -cb1[66].w
 101  0x00000EFC:   div r2.y, l(1.000000, 1.000000, 1.000000, 1.000000), r2.y
 102  0x00000F24:   add r12.z, r0.w, r2.y
 103  0x00000F40:   mul r11.xy, r7.xyxx, r11.zzzz
 104  0x00000F5C:   mul r12.xy, r8.xyxx, r12.zzzz
 105  0x00000F78:   add r11.xyz, -r3.xzwx, r11.xyzx
 106  0x00000F98:   mul r11.xyz, r6.xyzx, r11.xyzx
 107  0x00000FB4:   add r12.xyz, -r3.xzwx, r12.xyzx
 108  0x00000FD4:   mul r12.xyz, r6.xyzx, r12.xyzx
 109  0x00000FF0:   dp3 r0.w, r11.xyzx, r0.xyzx
 110  0x0000100C:   dp3 r2.y, r11.xyzx, r11.xyzx
 111  0x00001028:   div_sat r7.x, r0.w, r2.y
 112  0x00001044:   dp3 r0.w, r12.xyzx, r0.xyzx
 113  0x00001060:   dp3 r2.y, r12.xyzx, r12.xyzx
 114  0x0000107C:   div_sat r7.y, r0.w, r2.y
 115  0x00001098:   mad r2.yw, r4.xxxy, l(0.000000, 0.133333, 0.000000, 0.133333), r2.xxxz
 116  0x000010C8:   mad r8.xy, -r4.xyxx, l(0.133333, 0.133333, 0.000000, 0.000000), r2.xzxx
 117  0x000010FC:   mad r9.xy, cb0[35].xyxx, r2.ywyy, cb0[35].zwzz
 118  0x00001128:   sample_l_indexable(texture2d)(float,float,float,float) r0.w, r9.xyxx, t1.yzwx, s1, r5.y
 119  0x0000115C:   mad r9.xy, cb0[35].xyxx, r8.xyxx, cb0[35].zwzz
 120  0x00001188:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r9.xyxx, t1.xyzw, s1, r5.y
 121  0x000011BC:   mad r5.y, r0.w, cb1[66].x, cb1[66].y
 122  0x000011E8:   mad r0.w, r0.w, cb1[66].z, -cb1[66].w
 123  0x00001218:   div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
 124  0x00001240:   add r11.z, r0.w, r5.y
 125  0x0000125C:   mad r0.w, r5.x, cb1[66].x, cb1[66].y
 126  0x00001288:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 127  0x000012B8:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 128  0x000012E0:   add r12.z, r0.w, r5.x
 129  0x000012FC:   mul r11.xy, r2.ywyy, r11.zzzz
 130  0x00001318:   mul r12.xy, r8.xyxx, r12.zzzz
 131  0x00001334:   add r11.xyz, -r3.xzwx, r11.xyzx
 132  0x00001354:   mul r11.xyz, r6.xyzx, r11.xyzx
 133  0x00001370:   add r12.xyz, -r3.xzwx, r12.xyzx
 134  0x00001390:   mul r12.xyz, r6.xyzx, r12.xyzx
 135  0x000013AC:   dp3 r0.w, r11.xyzx, r0.xyzx
 136  0x000013C8:   dp3 r2.y, r11.xyzx, r11.xyzx
 137  0x000013E4:   div_sat r5.x, r0.w, r2.y
 138  0x00001400:   dp3 r0.w, r12.xyzx, r0.xyzx
 139  0x0000141C:   dp3 r2.y, r12.xyzx, r12.xyzx
 140  0x00001438:   div_sat r5.y, r0.w, r2.y
 141  0x00001454:   max r2.yw, r5.xxxy, r7.xxxy
 142  0x00001470:   sample_l_indexable(texture2d)(float,float,float,float) r0.w, r9.zwzz, t1.yzwx, s1, r5.z
 143  0x000014A4:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r10.zwzz, t1.xyzw, s1, r5.z
 144  0x000014D8:   mad r5.y, r0.w, cb1[66].x, cb1[66].y
 145  0x00001504:   mad r0.w, r0.w, cb1[66].z, -cb1[66].w
 146  0x00001534:   div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
 147  0x0000155C:   add r9.z, r0.w, r5.y
 148  0x00001578:   mad r0.w, r5.x, cb1[66].x, cb1[66].y
 149  0x000015A4:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 150  0x000015D4:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 151  0x000015FC:   add r10.z, r0.w, r5.x
 152  0x00001618:   mul r9.xy, r7.zwzz, r9.zzzz
 153  0x00001634:   mul r10.xy, r8.zwzz, r10.zzzz
 154  0x00001650:   add r7.xyz, -r3.xzwx, r9.xyzx
 155  0x00001670:   mul r7.xyz, r6.xyzx, r7.xyzx
 156  0x0000168C:   add r8.xyz, -r3.xzwx, r10.xyzx
 157  0x000016AC:   mul r8.xyz, r6.xyzx, r8.xyzx
 158  0x000016C8:   dp3 r0.w, r7.xyzx, r0.xyzx
 159  0x000016E4:   dp3 r5.x, r7.xyzx, r7.xyzx
 160  0x00001700:   div_sat r5.x, r0.w, r5.x
 161  0x0000171C:   dp3 r0.w, r8.xyzx, r0.xyzx
 162  0x00001738:   dp3 r6.w, r8.xyzx, r8.xyzx
 163  0x00001754:   div_sat r5.y, r0.w, r6.w
 164  0x00001770:   max r2.yw, r2.yyyw, r5.xxxy
 165  0x0000178C:   add r2.yw, -r2.yyyw, l(0.000000, 1.000000, 0.000000, 1.000000)
 166  0x000017B8:   mad r0.w, r2.y, r2.y, l(0.000100)
 167  0x000017DC:   mad r0.w, r2.w, r2.w, r0.w
 168  0x00001800:   mul r2.yw, r4.xxxy, l(0.000000, 0.101000, 0.000000, 0.101000)
 169  0x00001828:   mad r2.yw, r4.zzzw, l(0.000000, 0.325000, 0.000000, 0.325000), r2.yyyw
 170  0x00001858:   mad r7.xyzw, r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 171  0x00001888:   mad r8.xyzw, -r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 172  0x000018BC:   mad r9.xyzw, cb0[35].xyxy, r7.xyzw, cb0[35].zwzw
 173  0x000018E8:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r9.xyxx, t1.xyzw, s1, r5.z
 174  0x0000191C:   mad r10.xyzw, cb0[35].xyxy, r8.xyzw, cb0[35].zwzw
 175  0x00001948:   sample_l_indexable(texture2d)(float,float,float,float) r5.y, r10.xyxx, t1.yxzw, s1, r5.z
 176  0x0000197C:   mad r5.z, r5.x, cb1[66].x, cb1[66].y
 177  0x000019A8:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 178  0x000019D8:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 179  0x00001A00:   add r11.z, r5.x, r5.z
 180  0x00001A1C:   mad r5.x, r5.y, cb1[66].x, cb1[66].y
 181  0x00001A48:   mad r5.y, r5.y, cb1[66].z, -cb1[66].w
 182  0x00001A78:   div r5.y, l(1.000000, 1.000000, 1.000000, 1.000000), r5.y
 183  0x00001AA0:   add r5.z, r5.y, r5.x
 184  0x00001ABC:   mul r11.xy, r7.xyxx, r11.zzzz
 185  0x00001AD8:   mul r5.xy, r5.zzzz, r8.xyxx
 186  0x00001AF4:   add r11.xyz, -r3.xzwx, r11.xyzx
 187  0x00001B14:   mul r11.xyz, r6.xyzx, r11.xyzx
 188  0x00001B30:   add r5.xyz, -r3.xzwx, r5.xyzx
 189  0x00001B50:   mul r5.xyz, r6.xyzx, r5.xyzx
 190  0x00001B6C:   dp3 r6.w, r11.xyzx, r0.xyzx
 191  0x00001B88:   dp3 r7.x, r11.xyzx, r11.xyzx
 192  0x00001BA4:   div_sat r7.x, r6.w, r7.x
 193  0x00001BC0:   dp3 r6.w, r5.xyzx, r0.xyzx
 194  0x00001BDC:   dp3 r5.x, r5.xyzx, r5.xyzx
 195  0x00001BF8:   div_sat r7.y, r6.w, r5.x
 196  0x00001C14:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r9.zwzz, t1.xyzw, s1, r5.w
 197  0x00001C48:   sample_l_indexable(texture2d)(float,float,float,float) r5.y, r10.zwzz, t1.yxzw, s1, r5.w
 198  0x00001C7C:   mad r5.z, r5.x, cb1[66].x, cb1[66].y
 199  0x00001CA8:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 200  0x00001CD8:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 201  0x00001D00:   add r9.z, r5.x, r5.z
 202  0x00001D1C:   mad r5.x, r5.y, cb1[66].x, cb1[66].y
 203  0x00001D48:   mad r5.y, r5.y, cb1[66].z, -cb1[66].w
 204  0x00001D78:   div r5.y, l(1.000000, 1.000000, 1.000000, 1.000000), r5.y
 205  0x00001DA0:   add r5.z, r5.y, r5.x
 206  0x00001DBC:   mul r9.xy, r7.zwzz, r9.zzzz
 207  0x00001DD8:   mul r5.xy, r5.zzzz, r8.zwzz
 208  0x00001DF4:   add r8.xyz, -r3.xzwx, r9.xyzx
 209  0x00001E14:   mul r8.xyz, r6.xyzx, r8.xyzx
 210  0x00001E30:   add r5.xyz, -r3.xzwx, r5.xyzx
 211  0x00001E50:   mul r5.xyz, r6.xyzx, r5.xyzx
 212  0x00001E6C:   dp3 r5.w, r8.xyzx, r0.xyzx
 213  0x00001E88:   dp3 r6.w, r8.xyzx, r8.xyzx
 214  0x00001EA4:   div_sat r8.x, r5.w, r6.w
 215  0x00001EC0:   dp3 r5.w, r5.xyzx, r0.xyzx
 216  0x00001EDC:   dp3 r5.x, r5.xyzx, r5.xyzx
 217  0x00001EF8:   div_sat r8.y, r5.w, r5.x
 218  0x00001F14:   max r5.xy, r7.xyxx, r8.xyxx
 219  0x00001F30:   mul r7.xyzw, cb0[31].zzzz, l(0.250000, 0.138889, 0.277778, 0.416667)
 220  0x00001F5C:   log r7.xyzw, r7.xyzw
 221  0x00001F70:   max r7.xyzw, r7.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 222  0x00001F98:   add r5.zw, r2.yyyw, r2.xxxz
 223  0x00001FB4:   add r2.yw, -r2.yyyw, r2.xxxz
 224  0x00001FD4:   mad r8.xy, cb0[35].xyxx, r5.zwzz, cb0[35].zwzz
 225  0x00002000:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r8.xyxx, t1.yzwx, s1, r7.x
 226  0x00002034:   mad r8.xy, cb0[35].xyxx, r2.ywyy, cb0[35].zwzz
 227  0x00002060:   sample_l_indexable(texture2d)(float,float,float,float) r8.x, r8.xyxx, t1.xyzw, s1, r7.x
 228  0x00002094:   mad r8.y, r6.w, cb1[66].x, cb1[66].y
 229  0x000020C0:   mad r6.w, r6.w, cb1[66].z, -cb1[66].w
 230  0x000020F0:   div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 231  0x00002118:   add r9.z, r6.w, r8.y
 232  0x00002134:   mad r6.w, r8.x, cb1[66].x, cb1[66].y
 233  0x00002160:   mad r8.x, r8.x, cb1[66].z, -cb1[66].w
 234  0x00002190:   div r8.x, l(1.000000, 1.000000, 1.000000, 1.000000), r8.x
 235  0x000021B8:   add r8.z, r6.w, r8.x
 236  0x000021D4:   mul r9.xy, r5.zwzz, r9.zzzz
 237  0x000021F0:   mul r8.xy, r2.ywyy, r8.zzzz
 238  0x0000220C:   add r9.xyz, -r3.xzwx, r9.xyzx
 239  0x0000222C:   mul r9.xyz, r6.xyzx, r9.xyzx
 240  0x00002248:   add r8.xyz, -r3.xzwx, r8.xyzx
 241  0x00002268:   mul r8.xyz, r6.xyzx, r8.xyzx
 242  0x00002284:   dp3 r2.y, r9.xyzx, r0.xyzx
 243  0x000022A0:   dp3 r2.w, r9.xyzx, r9.xyzx
 244  0x000022BC:   div_sat r9.x, r2.y, r2.w
 245  0x000022D8:   dp3 r2.y, r8.xyzx, r0.xyzx
 246  0x000022F4:   dp3 r2.w, r8.xyzx, r8.xyzx
 247  0x00002310:   div_sat r9.y, r2.y, r2.w
 248  0x0000232C:   max r2.yw, r5.xxxy, r9.xxxy
 249  0x00002348:   add r2.yw, -r2.yyyw, l(0.000000, 1.000000, 0.000000, 1.000000)
 250  0x00002374:   mad r0.w, r2.y, r2.y, r0.w
 251  0x00002398:   mad r0.w, r2.w, r2.w, r0.w
 252  0x000023BC:   mul r2.yw, r4.xxxy, l(0.000000, -0.396000, 0.000000, -0.396000)
 253  0x000023E4:   mad r2.yw, r4.zzzw, l(0.000000, 0.272000, 0.000000, 0.272000), r2.yyyw
 254  0x00002414:   mad r5.xyzw, r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 255  0x00002444:   mad r8.xyzw, -r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 256  0x00002478:   mad r9.xyzw, cb0[35].xyxy, r5.xyzw, cb0[35].zwzw
 257  0x000024A4:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r9.xyxx, t1.yzwx, s1, r7.y
 258  0x000024D8:   mad r10.xyzw, cb0[35].xyxy, r8.xyzw, cb0[35].zwzw
 259  0x00002504:   sample_l_indexable(texture2d)(float,float,float,float) r7.y, r10.xyxx, t1.yxzw, s1, r7.y
 260  0x00002538:   mad r9.x, r6.w, cb1[66].x, cb1[66].y
 261  0x00002564:   mad r6.w, r6.w, cb1[66].z, -cb1[66].w
 262  0x00002594:   div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 263  0x000025BC:   add r11.z, r6.w, r9.x
 264  0x000025D8:   mad r6.w, r7.y, cb1[66].x, cb1[66].y
 265  0x00002604:   mad r7.y, r7.y, cb1[66].z, -cb1[66].w
 266  0x00002634:   div r7.y, l(1.000000, 1.000000, 1.000000, 1.000000), r7.y
 267  0x0000265C:   add r12.z, r6.w, r7.y
 268  0x00002678:   mul r11.xy, r5.xyxx, r11.zzzz
 269  0x00002694:   mul r12.xy, r8.xyxx, r12.zzzz
 270  0x000026B0:   add r11.xyz, -r3.xzwx, r11.xyzx
 271  0x000026D0:   mul r11.xyz, r6.xyzx, r11.xyzx
 272  0x000026EC:   add r12.xyz, -r3.xzwx, r12.xyzx
 273  0x0000270C:   mul r12.xyz, r6.xyzx, r12.xyzx
 274  0x00002728:   dp3 r5.x, r11.xyzx, r0.xyzx
 275  0x00002744:   dp3 r5.y, r11.xyzx, r11.xyzx
 276  0x00002760:   div_sat r5.x, r5.x, r5.y
 277  0x0000277C:   dp3 r6.w, r12.xyzx, r0.xyzx
 278  0x00002798:   dp3 r7.y, r12.xyzx, r12.xyzx
 279  0x000027B4:   div_sat r5.y, r6.w, r7.y
 280  0x000027D0:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r9.zwzz, t1.yzwx, s1, r7.z
 281  0x00002804:   sample_l_indexable(texture2d)(float,float,float,float) r7.y, r10.zwzz, t1.yxzw, s1, r7.z
 282  0x00002838:   mad r7.z, r6.w, cb1[66].x, cb1[66].y
 283  0x00002864:   mad r6.w, r6.w, cb1[66].z, -cb1[66].w
 284  0x00002894:   div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 285  0x000028BC:   add r9.z, r6.w, r7.z
 286  0x000028D8:   mad r6.w, r7.y, cb1[66].x, cb1[66].y
 287  0x00002904:   mad r7.y, r7.y, cb1[66].z, -cb1[66].w
 288  0x00002934:   div r7.y, l(1.000000, 1.000000, 1.000000, 1.000000), r7.y
 289  0x0000295C:   add r10.z, r6.w, r7.y
 290  0x00002978:   mul r9.xy, r5.zwzz, r9.zzzz
 291  0x00002994:   mul r10.xy, r8.zwzz, r10.zzzz
 292  0x000029B0:   add r8.xyz, -r3.xzwx, r9.xyzx
 293  0x000029D0:   mul r8.xyz, r6.xyzx, r8.xyzx
 294  0x000029EC:   add r9.xyz, -r3.xzwx, r10.xyzx
 295  0x00002A0C:   mul r9.xyz, r6.xyzx, r9.xyzx
 296  0x00002A28:   dp3 r5.z, r8.xyzx, r0.xyzx
 297  0x00002A44:   dp3 r5.w, r8.xyzx, r8.xyzx
 298  0x00002A60:   div_sat r8.x, r5.z, r5.w
 299  0x00002A7C:   dp3 r5.z, r9.xyzx, r0.xyzx
 300  0x00002A98:   dp3 r5.w, r9.xyzx, r9.xyzx
 301  0x00002AB4:   div_sat r8.y, r5.z, r5.w
 302  0x00002AD0:   max r5.xy, r5.xyxx, r8.xyxx
 303  0x00002AEC:   add r5.zw, r2.yyyw, r2.xxxz
 304  0x00002B08:   add r2.yw, -r2.yyyw, r2.xxxz
 305  0x00002B28:   mad r7.yz, cb0[35].xxyx, r5.zzwz, cb0[35].zzwz
 306  0x00002B54:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r7.yzyy, t1.yzwx, s1, r7.w
 307  0x00002B88:   mad r7.yz, cb0[35].xxyx, r2.yywy, cb0[35].zzwz
 308  0x00002BB4:   sample_l_indexable(texture2d)(float,float,float,float) r7.y, r7.yzyy, t1.yxzw, s1, r7.w
 309  0x00002BE8:   mad r7.z, r6.w, cb1[66].x, cb1[66].y
 310  0x00002C14:   mad r6.w, r6.w, cb1[66].z, -cb1[66].w
 311  0x00002C44:   div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 312  0x00002C6C:   add r8.z, r6.w, r7.z
 313  0x00002C88:   mad r6.w, r7.y, cb1[66].x, cb1[66].y
 314  0x00002CB4:   mad r7.y, r7.y, cb1[66].z, -cb1[66].w
 315  0x00002CE4:   div r7.y, l(1.000000, 1.000000, 1.000000, 1.000000), r7.y
 316  0x00002D0C:   add r9.z, r6.w, r7.y
 317  0x00002D28:   mul r8.xy, r5.zwzz, r8.zzzz
 318  0x00002D44:   mul r9.xy, r2.ywyy, r9.zzzz
 319  0x00002D60:   add r7.yzw, -r3.xxzw, r8.xxyz
 320  0x00002D80:   mul r7.yzw, r6.xxyz, r7.yyzw
 321  0x00002D9C:   add r8.xyz, -r3.xzwx, r9.xyzx
 322  0x00002DBC:   mul r8.xyz, r6.xyzx, r8.xyzx
 323  0x00002DD8:   dp3 r2.y, r7.yzwy, r0.xyzx
 324  0x00002DF4:   dp3 r2.w, r7.yzwy, r7.yzwy
 325  0x00002E10:   div_sat r9.x, r2.y, r2.w
 326  0x00002E2C:   dp3 r2.y, r8.xyzx, r0.xyzx
 327  0x00002E48:   dp3 r2.w, r8.xyzx, r8.xyzx
 328  0x00002E64:   div_sat r9.y, r2.y, r2.w
 329  0x00002E80:   max r2.yw, r5.xxxy, r9.xxxy
 330  0x00002E9C:   add r2.yw, -r2.yyyw, l(0.000000, 1.000000, 0.000000, 1.000000)
 331  0x00002EC8:   mad r0.w, r2.y, r2.y, r0.w
 332  0x00002EEC:   mad r0.w, r2.w, r2.w, r0.w
 333  0x00002F10:   mul r2.yw, r4.xxxy, l(0.000000, -0.488000, 0.000000, -0.488000)
 334  0x00002F38:   mad r2.yw, r4.zzzw, l(0.000000, -0.385000, 0.000000, -0.385000), r2.yyyw
 335  0x00002F68:   mul r5.xyzw, cb0[31].zzzz, l(0.194444, 0.388889, 0.583333, 0.500000)
 336  0x00002F94:   log r5.xyzw, r5.xyzw
 337  0x00002FA8:   max r5.xyzw, r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 338  0x00002FD0:   mad r8.xyzw, r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 339  0x00003000:   mad r9.xyzw, -r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 340  0x00003034:   mad r10.xyzw, cb0[35].xyxy, r8.xyzw, cb0[35].zwzw
 341  0x00003060:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r10.xyxx, t1.yzwx, s1, r5.x
 342  0x00003094:   mad r11.xyzw, cb0[35].xyxy, r9.xyzw, cb0[35].zwzw
 343  0x000030C0:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r11.xyxx, t1.xyzw, s1, r5.x
 344  0x000030F4:   mad r7.y, r6.w, cb1[66].x, cb1[66].y
 345  0x00003120:   mad r6.w, r6.w, cb1[66].z, -cb1[66].w
 346  0x00003150:   div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 347  0x00003178:   add r12.z, r6.w, r7.y
 348  0x00003194:   mad r6.w, r5.x, cb1[66].x, cb1[66].y
 349  0x000031C0:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 350  0x000031F0:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 351  0x00003218:   add r13.z, r5.x, r6.w
 352  0x00003234:   mul r12.xy, r8.xyxx, r12.zzzz
 353  0x00003250:   mul r13.xy, r9.xyxx, r13.zzzz
 354  0x0000326C:   add r7.yzw, -r3.xxzw, r12.xxyz
 355  0x0000328C:   mul r7.yzw, r6.xxyz, r7.yyzw
 356  0x000032A8:   add r12.xyz, -r3.xzwx, r13.xyzx
 357  0x000032C8:   mul r12.xyz, r6.xyzx, r12.xyzx
 358  0x000032E4:   dp3 r5.x, r7.yzwy, r0.xyzx
 359  0x00003300:   dp3 r6.w, r7.yzwy, r7.yzwy
 360  0x0000331C:   div_sat r8.x, r5.x, r6.w
 361  0x00003338:   dp3 r5.x, r12.xyzx, r0.xyzx
 362  0x00003354:   dp3 r6.w, r12.xyzx, r12.xyzx
 363  0x00003370:   div_sat r8.y, r5.x, r6.w
 364  0x0000338C:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r10.zwzz, t1.xyzw, s1, r5.y
 365  0x000033C0:   sample_l_indexable(texture2d)(float,float,float,float) r5.y, r11.zwzz, t1.yxzw, s1, r5.y
 366  0x000033F4:   mad r6.w, r5.x, cb1[66].x, cb1[66].y
 367  0x00003420:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 368  0x00003450:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 369  0x00003478:   add r10.z, r5.x, r6.w
 370  0x00003494:   mad r5.x, r5.y, cb1[66].x, cb1[66].y
 371  0x000034C0:   mad r5.y, r5.y, cb1[66].z, -cb1[66].w
 372  0x000034F0:   div r5.y, l(1.000000, 1.000000, 1.000000, 1.000000), r5.y
 373  0x00003518:   add r11.z, r5.y, r5.x
 374  0x00003534:   mul r10.xy, r8.zwzz, r10.zzzz
 375  0x00003550:   mul r11.xy, r9.zwzz, r11.zzzz
 376  0x0000356C:   add r7.yzw, -r3.xxzw, r10.xxyz
 377  0x0000358C:   mul r7.yzw, r6.xxyz, r7.yyzw
 378  0x000035A8:   add r9.xyz, -r3.xzwx, r11.xyzx
 379  0x000035C8:   mul r9.xyz, r6.xyzx, r9.xyzx
 380  0x000035E4:   dp3 r5.x, r7.yzwy, r0.xyzx
 381  0x00003600:   dp3 r5.y, r7.yzwy, r7.yzwy
 382  0x0000361C:   div_sat r5.x, r5.x, r5.y
 383  0x00003638:   dp3 r6.w, r9.xyzx, r0.xyzx
 384  0x00003654:   dp3 r7.y, r9.xyzx, r9.xyzx
 385  0x00003670:   div_sat r5.y, r6.w, r7.y
 386  0x0000368C:   max r5.xy, r5.xyxx, r8.xyxx
 387  0x000036A8:   add r7.yz, r2.yywy, r2.xxzx
 388  0x000036C4:   add r2.yw, -r2.yyyw, r2.xxxz
 389  0x000036E4:   mad r8.xy, cb0[35].xyxx, r7.yzyy, cb0[35].zwzz
 390  0x00003710:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r8.xyxx, t1.yzwx, s1, r5.z
 391  0x00003744:   mad r8.xy, cb0[35].xyxx, r2.ywyy, cb0[35].zwzz
 392  0x00003770:   sample_l_indexable(texture2d)(float,float,float,float) r5.z, r8.xyxx, t1.yzxw, s1, r5.z
 393  0x000037A4:   mad r7.w, r6.w, cb1[66].x, cb1[66].y
 394  0x000037D0:   mad r6.w, r6.w, cb1[66].z, -cb1[66].w
 395  0x00003800:   div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 396  0x00003828:   add r8.z, r6.w, r7.w
 397  0x00003844:   mad r6.w, r5.z, cb1[66].x, cb1[66].y
 398  0x00003870:   mad r5.z, r5.z, cb1[66].z, -cb1[66].w
 399  0x000038A0:   div r5.z, l(1.000000, 1.000000, 1.000000, 1.000000), r5.z
 400  0x000038C8:   add r9.z, r5.z, r6.w
 401  0x000038E4:   mul r8.xy, r7.yzyy, r8.zzzz
 402  0x00003900:   mul r9.xy, r2.ywyy, r9.zzzz
 403  0x0000391C:   add r7.yzw, -r3.xxzw, r8.xxyz
 404  0x0000393C:   mul r7.yzw, r6.xxyz, r7.yyzw
 405  0x00003958:   add r8.xyz, -r3.xzwx, r9.xyzx
 406  0x00003978:   mul r8.xyz, r6.xyzx, r8.xyzx
 407  0x00003994:   dp3 r2.y, r7.yzwy, r0.xyzx
 408  0x000039B0:   dp3 r2.w, r7.yzwy, r7.yzwy
 409  0x000039CC:   div_sat r9.x, r2.y, r2.w
 410  0x000039E8:   dp3 r2.y, r8.xyzx, r0.xyzx
 411  0x00003A04:   dp3 r2.w, r8.xyzx, r8.xyzx
 412  0x00003A20:   div_sat r9.y, r2.y, r2.w
 413  0x00003A3C:   max r2.yw, r5.xxxy, r9.xxxy
 414  0x00003A58:   add r2.yw, -r2.yyyw, l(0.000000, 1.000000, 0.000000, 1.000000)
 415  0x00003A84:   mad r0.w, r2.y, r2.y, r0.w
 416  0x00003AA8:   mad r0.w, r2.w, r2.w, r0.w
 417  0x00003ACC:   mul r8.xyzw, r4.xyzw, l(0.274000, 0.274000, 0.060000, 0.060000)
 418  0x00003AF4:   mad r2.yw, r4.zzzw, l(0.000000, -0.711000, 0.000000, -0.711000), r8.xxxy
 419  0x00003B24:   mad r9.xyzw, r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 420  0x00003B54:   mad r10.xyzw, -r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 421  0x00003B88:   mad r11.xyzw, cb0[35].xyxy, r9.xyzw, cb0[35].zwzw
 422  0x00003BB4:   sample_l_indexable(texture2d)(float,float,float,float) r4.z, r11.xyxx, t1.yzxw, s1, r7.x
 423  0x00003BE8:   mad r12.xyzw, cb0[35].xyxy, r10.xyzw, cb0[35].zwzw
 424  0x00003C14:   sample_l_indexable(texture2d)(float,float,float,float) r4.w, r12.xyxx, t1.yzwx, s1, r7.x
 425  0x00003C48:   mad r5.x, r4.z, cb1[66].x, cb1[66].y
 426  0x00003C74:   mad r4.z, r4.z, cb1[66].z, -cb1[66].w
 427  0x00003CA4:   div r4.z, l(1.000000, 1.000000, 1.000000, 1.000000), r4.z
 428  0x00003CCC:   add r5.z, r4.z, r5.x
 429  0x00003CE8:   mad r4.z, r4.w, cb1[66].x, cb1[66].y
 430  0x00003D14:   mad r4.w, r4.w, cb1[66].z, -cb1[66].w
 431  0x00003D44:   div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 432  0x00003D6C:   add r7.z, r4.w, r4.z
 433  0x00003D88:   mul r5.xy, r5.zzzz, r9.xyxx
 434  0x00003DA4:   mul r7.xy, r7.zzzz, r10.xyxx
 435  0x00003DC0:   add r5.xyz, -r3.xzwx, r5.xyzx
 436  0x00003DE0:   mul r5.xyz, r6.xyzx, r5.xyzx
 437  0x00003DFC:   add r7.xyz, -r3.xzwx, r7.xyzx
 438  0x00003E1C:   mul r7.xyz, r6.xyzx, r7.xyzx
 439  0x00003E38:   dp3 r4.z, r5.xyzx, r0.xyzx
 440  0x00003E54:   dp3 r4.w, r5.xyzx, r5.xyzx
 441  0x00003E70:   div_sat r5.x, r4.z, r4.w
 442  0x00003E8C:   dp3 r4.z, r7.xyzx, r0.xyzx
 443  0x00003EA8:   dp3 r4.w, r7.xyzx, r7.xyzx
 444  0x00003EC4:   div_sat r5.y, r4.z, r4.w
 445  0x00003EE0:   sample_l_indexable(texture2d)(float,float,float,float) r4.z, r11.zwzz, t1.yzxw, s1, r5.w
 446  0x00003F14:   sample_l_indexable(texture2d)(float,float,float,float) r4.w, r12.zwzz, t1.yzwx, s1, r5.w
 447  0x00003F48:   mad r5.z, r4.z, cb1[66].x, cb1[66].y
 448  0x00003F74:   mad r4.z, r4.z, cb1[66].z, -cb1[66].w
 449  0x00003FA4:   div r4.z, l(1.000000, 1.000000, 1.000000, 1.000000), r4.z
 450  0x00003FCC:   add r7.z, r4.z, r5.z
 451  0x00003FE8:   mad r4.z, r4.w, cb1[66].x, cb1[66].y
 452  0x00004014:   mad r4.w, r4.w, cb1[66].z, -cb1[66].w
 453  0x00004044:   div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 454  0x0000406C:   add r11.z, r4.w, r4.z
 455  0x00004088:   mul r7.xy, r7.zzzz, r9.zwzz
 456  0x000040A4:   mul r11.xy, r10.zwzz, r11.zzzz
 457  0x000040C0:   add r7.xyz, -r3.xzwx, r7.xyzx
 458  0x000040E0:   mul r7.xyz, r6.xyzx, r7.xyzx
 459  0x000040FC:   add r9.xyz, -r3.xzwx, r11.xyzx
 460  0x0000411C:   mul r9.xyz, r6.xyzx, r9.xyzx
 461  0x00004138:   dp3 r4.z, r7.xyzx, r0.xyzx
 462  0x00004154:   dp3 r4.w, r7.xyzx, r7.xyzx
 463  0x00004170:   div_sat r7.x, r4.z, r4.w
 464  0x0000418C:   dp3 r4.z, r9.xyzx, r0.xyzx
 465  0x000041A8:   dp3 r4.w, r9.xyzx, r9.xyzx
 466  0x000041C4:   div_sat r7.y, r4.z, r4.w
 467  0x000041E0:   max r4.zw, r5.xxxy, r7.xxxy
 468  0x000041FC:   mul r5.xyzw, cb0[31].zzzz, l(0.750000, 0.305556, 0.611111, 0.916667)
 469  0x00004228:   log r5.xyzw, r5.xyzw
 470  0x0000423C:   max r5.xyzw, r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
 471  0x00004264:   add r7.xy, r2.ywyy, r2.xzxx
 472  0x00004280:   add r2.yw, -r2.yyyw, r2.xxxz
 473  0x000042A0:   mad r7.zw, cb0[35].xxxy, r7.xxxy, cb0[35].zzzw
 474  0x000042CC:   sample_l_indexable(texture2d)(float,float,float,float) r6.w, r7.zwzz, t1.yzwx, s1, r5.x
 475  0x00004300:   mad r7.zw, cb0[35].xxxy, r2.yyyw, cb0[35].zzzw
 476  0x0000432C:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r7.zwzz, t1.xyzw, s1, r5.x
 477  0x00004360:   mad r7.z, r6.w, cb1[66].x, cb1[66].y
 478  0x0000438C:   mad r6.w, r6.w, cb1[66].z, -cb1[66].w
 479  0x000043BC:   div r6.w, l(1.000000, 1.000000, 1.000000, 1.000000), r6.w
 480  0x000043E4:   add r9.z, r6.w, r7.z
 481  0x00004400:   mad r6.w, r5.x, cb1[66].x, cb1[66].y
 482  0x0000442C:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 483  0x0000445C:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 484  0x00004484:   add r10.z, r5.x, r6.w
 485  0x000044A0:   mul r9.xy, r7.xyxx, r9.zzzz
 486  0x000044BC:   mul r10.xy, r2.ywyy, r10.zzzz
 487  0x000044D8:   add r7.xyz, -r3.xzwx, r9.xyzx
 488  0x000044F8:   mul r7.xyz, r6.xyzx, r7.xyzx
 489  0x00004514:   add r9.xyz, -r3.xzwx, r10.xyzx
 490  0x00004534:   mul r9.xyz, r6.xyzx, r9.xyzx
 491  0x00004550:   dp3 r2.y, r7.xyzx, r0.xyzx
 492  0x0000456C:   dp3 r2.w, r7.xyzx, r7.xyzx
 493  0x00004588:   div_sat r7.x, r2.y, r2.w
 494  0x000045A4:   dp3 r2.y, r9.xyzx, r0.xyzx
 495  0x000045C0:   dp3 r2.w, r9.xyzx, r9.xyzx
 496  0x000045DC:   div_sat r7.y, r2.y, r2.w
 497  0x000045F8:   max r2.yw, r4.zzzw, r7.xxxy
 498  0x00004614:   add r2.yw, -r2.yyyw, l(0.000000, 1.000000, 0.000000, 1.000000)
 499  0x00004640:   mad r0.w, r2.y, r2.y, r0.w
 500  0x00004664:   mad r0.w, r2.w, r2.w, r0.w
 501  0x00004688:   mad r2.yw, r4.xxxy, l(0.000000, 0.900000, 0.000000, 0.900000), r8.zzzw
 502  0x000046B8:   mad r4.xyzw, r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 503  0x000046E8:   mad r7.xyzw, -r2.ywyw, l(0.333333, 0.333333, 0.666667, 0.666667), r2.xzxz
 504  0x0000471C:   mad r8.xyzw, cb0[35].xyxy, r4.xyzw, cb0[35].zwzw
 505  0x00004748:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r8.xyxx, t1.xyzw, s1, r5.y
 506  0x0000477C:   mad r9.xyzw, cb0[35].xyxy, r7.xyzw, cb0[35].zwzw
 507  0x000047A8:   sample_l_indexable(texture2d)(float,float,float,float) r5.y, r9.xyxx, t1.yxzw, s1, r5.y
 508  0x000047DC:   mad r6.w, r5.x, cb1[66].x, cb1[66].y
 509  0x00004808:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 510  0x00004838:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 511  0x00004860:   add r10.z, r5.x, r6.w
 512  0x0000487C:   mad r5.x, r5.y, cb1[66].x, cb1[66].y
 513  0x000048A8:   mad r5.y, r5.y, cb1[66].z, -cb1[66].w
 514  0x000048D8:   div r5.y, l(1.000000, 1.000000, 1.000000, 1.000000), r5.y
 515  0x00004900:   add r11.z, r5.y, r5.x
 516  0x0000491C:   mul r10.xy, r4.xyxx, r10.zzzz
 517  0x00004938:   mul r11.xy, r7.xyxx, r11.zzzz
 518  0x00004954:   add r10.xyz, -r3.xzwx, r10.xyzx
 519  0x00004974:   mul r10.xyz, r6.xyzx, r10.xyzx
 520  0x00004990:   add r11.xyz, -r3.xzwx, r11.xyzx
 521  0x000049B0:   mul r11.xyz, r6.xyzx, r11.xyzx
 522  0x000049CC:   dp3 r4.x, r10.xyzx, r0.xyzx
 523  0x000049E8:   dp3 r4.y, r10.xyzx, r10.xyzx
 524  0x00004A04:   div_sat r4.x, r4.x, r4.y
 525  0x00004A20:   dp3 r5.x, r11.xyzx, r0.xyzx
 526  0x00004A3C:   dp3 r5.y, r11.xyzx, r11.xyzx
 527  0x00004A58:   div_sat r4.y, r5.x, r5.y
 528  0x00004A74:   sample_l_indexable(texture2d)(float,float,float,float) r5.x, r8.zwzz, t1.xyzw, s1, r5.z
 529  0x00004AA8:   sample_l_indexable(texture2d)(float,float,float,float) r5.y, r9.zwzz, t1.yxzw, s1, r5.z
 530  0x00004ADC:   mad r5.z, r5.x, cb1[66].x, cb1[66].y
 531  0x00004B08:   mad r5.x, r5.x, cb1[66].z, -cb1[66].w
 532  0x00004B38:   div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
 533  0x00004B60:   add r8.z, r5.x, r5.z
 534  0x00004B7C:   mad r5.x, r5.y, cb1[66].x, cb1[66].y
 535  0x00004BA8:   mad r5.y, r5.y, cb1[66].z, -cb1[66].w
 536  0x00004BD8:   div r5.y, l(1.000000, 1.000000, 1.000000, 1.000000), r5.y
 537  0x00004C00:   add r5.z, r5.y, r5.x
 538  0x00004C1C:   mul r8.xy, r4.zwzz, r8.zzzz
 539  0x00004C38:   mul r5.xy, r5.zzzz, r7.zwzz
 540  0x00004C54:   add r7.xyz, -r3.xzwx, r8.xyzx
 541  0x00004C74:   mul r7.xyz, r6.xyzx, r7.xyzx
 542  0x00004C90:   add r5.xyz, -r3.xzwx, r5.xyzx
 543  0x00004CB0:   mul r5.xyz, r6.xyzx, r5.xyzx
 544  0x00004CCC:   dp3 r4.z, r7.xyzx, r0.xyzx
 545  0x00004CE8:   dp3 r4.w, r7.xyzx, r7.xyzx
 546  0x00004D04:   div_sat r7.x, r4.z, r4.w
 547  0x00004D20:   dp3 r4.z, r5.xyzx, r0.xyzx
 548  0x00004D3C:   dp3 r4.w, r5.xyzx, r5.xyzx
 549  0x00004D58:   div_sat r7.y, r4.z, r4.w
 550  0x00004D74:   max r4.xy, r4.xyxx, r7.xyxx
 551  0x00004D90:   add r4.zw, r2.yyyw, r2.xxxz
 552  0x00004DAC:   add r2.xy, -r2.ywyy, r2.xzxx
 553  0x00004DCC:   mad r2.zw, cb0[35].xxxy, r4.zzzw, cb0[35].zzzw
 554  0x00004DF8:   sample_l_indexable(texture2d)(float,float,float,float) r2.z, r2.zwzz, t1.yzxw, s1, r5.w
 555  0x00004E2C:   mad r5.xy, cb0[35].xyxx, r2.xyxx, cb0[35].zwzz
 556  0x00004E58:   sample_l_indexable(texture2d)(float,float,float,float) r2.w, r5.xyxx, t1.yzwx, s1, r5.w
 557  0x00004E8C:   mad r5.x, r2.z, cb1[66].x, cb1[66].y
 558  0x00004EB8:   mad r2.z, r2.z, cb1[66].z, -cb1[66].w
 559  0x00004EE8:   div r2.z, l(1.000000, 1.000000, 1.000000, 1.000000), r2.z
 560  0x00004F10:   add r5.z, r2.z, r5.x
 561  0x00004F2C:   mad r2.z, r2.w, cb1[66].x, cb1[66].y
 562  0x00004F58:   mad r2.w, r2.w, cb1[66].z, -cb1[66].w
 563  0x00004F88:   div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
 564  0x00004FB0:   add r7.z, r2.w, r2.z
 565  0x00004FCC:   mul r5.xy, r4.zwzz, r5.zzzz
 566  0x00004FE8:   mul r7.xy, r2.xyxx, r7.zzzz
 567  0x00005004:   add r2.xyz, -r3.xzwx, r5.xyzx
 568  0x00005024:   mul r2.xyz, r6.xyzx, r2.xyzx
 569  0x00005040:   add r3.xzw, -r3.xxzw, r7.xxyz
 570  0x00005060:   mul r3.xzw, r6.xxyz, r3.xxzw
 571  0x0000507C:   dp3 r2.w, r2.xyzx, r0.xyzx
 572  0x00005098:   dp3 r2.x, r2.xyzx, r2.xyzx
 573  0x000050B4:   div_sat r2.x, r2.w, r2.x
 574  0x000050D0:   dp3 r0.x, r3.xzwx, r0.xyzx
 575  0x000050EC:   dp3 r0.y, r3.xzwx, r3.xzwx
 576  0x00005108:   div_sat r2.y, r0.x, r0.y
 577  0x00005124:   max r0.xy, r2.xyxx, r4.xyxx
 578  0x00005140:   add r0.xy, -r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 579  0x0000516C:   mad r0.x, r0.x, r0.x, r0.w
 580  0x00005190:   mad r0.x, r0.y, r0.y, r0.x
 581  0x000051B4:   mul r0.y, r0.x, l(0.083333)
 582  0x000051D0:   mov_sat r3.y, r3.y
 583  0x000051E4:   mad r0.x, -r0.x, l(0.083333), l(1.000000)
 584  0x0000520C:   mad r0.x, r3.y, r0.x, r0.y
 585  0x00005230:   log r0.x, r0.x
 586  0x00005244:   mul r0.x, r0.x, cb0[27].x
 587  0x00005264:   exp r0.x, r0.x
 588  0x00005278:   add r0.x, -r0.x, l(1.000000)
 589  0x00005298:   mad r0.x, -r0.x, cb0[27].w, l(1.000000)
 590  0x000052C4: else 
 591  0x000052C8:   mov r0.x, l(1.000000)
 592  0x000052DC: endif 
 593  0x000052E0: store_uav_typed u0.xyzw, r1.xyzw, r0.xxxx
 594  0x000052FC: ret 
// Approximately 0 instruction slots used
