//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float       
// SV_POSITION              0   xyzw        1      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[21], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[140], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_resource_texture3d (float,float,float,float) t0
      0x00000048: dcl_resource_texture2d (float,float,float,float) t1
      0x00000058: dcl_resource_texture2d (float,float,float,float) t2
      0x00000068: dcl_resource_texture2d (float,float,float,float) t3
      0x00000078: dcl_resource_texture2d (float,float,float,float) t4
      0x00000088: dcl_resource_texture2d (float,float,float,float) t5
      0x00000098: dcl_input_ps_siv linear noperspective v1.xy, position
      0x000000A8: dcl_output o0.xyzw
      0x000000B4: dcl_temps 13
   0  0x000000BC: ftoi r0.xy, v1.xyxx
   1  0x000000D0: round_z r1.xy, v1.xyxx
   2  0x000000E4: add r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
   3  0x0000010C: add r1.xy, r1.xyxx, -cb1[121].xyxx
   4  0x00000130: mul r1.xy, r1.xyxx, cb1[122].zwzz
   5  0x00000150: mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
   6  0x0000018C: mul r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, -1.000000)
   7  0x000001B4: ishl r0.z, cb1[139].w, l(1)
   8  0x000001D4: and r2.xyz, r0.xyzx, l(63, 63, 63, 0)
   9  0x000001FC: mov r2.w, l(0)
  10  0x00000210: ld_indexable(texture3d)(float,float,float,float) r2.xy, r2.xyzw, t0.yzxw
  11  0x00000234: mov r0.w, l(0)
  12  0x00000248: ld_indexable(texture2d)(float,float,float,float) r0.z, r0.xyww, t2.yzxw
  13  0x0000026C: mad r2.z, r0.z, cb1[57].x, cb1[57].y
  14  0x00000298: mad r2.w, r0.z, cb1[57].z, -cb1[57].w
  15  0x000002C8: rcp r2.w, r2.w
  16  0x000002DC: add r3.z, r2.w, r2.z
  17  0x000002F8: ld_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyww, t1.xyzw
  18  0x0000031C: mad r4.xyz, r4.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
  19  0x00000358: dp3 r2.z, r4.xyzx, r4.xyzx
  20  0x00000374: rsq r2.z, r2.z
  21  0x00000388: mul r4.xyz, r2.zzzz, r4.xyzx
  22  0x000003A4: mul r5.xyz, r4.yyyy, cb1[9].xyzx
  23  0x000003C4: mad r4.xyw, r4.xxxx, cb1[8].xyxz, r5.xyxz
  24  0x000003EC: mad r4.xyz, r4.zzzz, cb1[10].xyzx, r4.xywx
  25  0x00000414: mul r2.yz, r2.yyxy, l(0.000000, 1.570796, 0.500000, 0.000000)
  26  0x0000043C: sincos r5.x, r6.x, r2.y
  27  0x00000458: mul r2.y, cb1[122].x, l(0.125000)
  28  0x00000478: rcp r2.w, cb0[20].x
  29  0x00000490: mul r2.w, r2.w, cb0[3].z
  30  0x000004B0: mul r2.w, r2.w, l(1.414214)
  31  0x000004CC: mul r3.w, cb0[18].w, l(500.000000)
  32  0x000004EC: rcp r4.w, r3.z
  33  0x00000500: mul r3.w, r3.w, r4.w
  34  0x0000051C: min r3.w, r3.w, l(0.750000)
  35  0x00000538: mul r5.yz, r1.zzwz, r3.zzzz
  36  0x00000554: mov r7.xz, l(1.000000,0,1.000000,0)
  37  0x00000574: mov r7.yw, cb0[19].zzzw
  38  0x0000058C: mul r3.xy, r5.yzyy, r7.xyxx
  39  0x000005A8: mul r2.z, r2.z, r2.z
  40  0x000005C4: mul r2.z, r3.w, r2.z
  41  0x000005E0: max r2.z, r2.z, r2.w
  42  0x000005FC: mul r4.w, r2.y, r2.z
  43  0x00000618: log r4.w, r4.w
  44  0x0000062C: min r4.w, r4.w, l(4.000000)
  45  0x00000648: mov r6.y, r5.x
  46  0x0000065C: mul r5.yz, r6.xxyx, r7.zzwz
  47  0x00000678: mad r8.xy, r5.yzyy, r2.zzzz, r1.zwzz
  48  0x0000069C: lt r8.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r8.xxxy
  49  0x000006C4: lt r9.xy, r8.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  50  0x000006EC: iadd r8.zw, -r8.zzzw, r9.xxxy
  51  0x0000070C: ishl r8.zw, r8.zzzw, l(0, 0, 1, 1)
  52  0x00000734: itof r8.zw, r8.zzzw
  53  0x00000748: add r9.xy, |r8.xyxx|, l(-1.000000, -1.000000, 0.000000, 0.000000)
  54  0x00000774: max r9.xy, r9.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
  55  0x0000079C: mad r8.zw, -r8.zzzw, r9.xxxy, r8.xxxy
  56  0x000007C4: mad r8.zw, r8.zzzw, cb0[20].xxxy, cb0[20].zzzw
  57  0x000007F0: sample_l_indexable(texture2d)(float,float,float,float) r5.w, r8.zwzz, t5.yzwx, s0, r4.w
  58  0x00000824: mad r8.z, r5.w, cb1[57].x, cb1[57].y
  59  0x00000850: mad r5.w, r5.w, cb1[57].z, -cb1[57].w
  60  0x00000880: rcp r5.w, r5.w
  61  0x00000894: add r9.z, r5.w, r8.z
  62  0x000008B0: mul r8.xy, r8.xyxx, r9.zzzz
  63  0x000008CC: mul r9.xy, r7.xyxx, r8.xyxx
  64  0x000008E8: add r8.xyz, -r3.xyzx, r9.xyzx
  65  0x00000908: mul r9.xy, r8.xyxx, cb0[18].zzzz
  66  0x00000928: mul r8.xy, r9.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  67  0x00000950: dp3 r5.w, r8.xyzx, r8.xyzx
  68  0x0000096C: sqrt r5.w, r5.w
  69  0x00000980: max r5.w, r5.w, l(0.000100)
  70  0x0000099C: div r8.x, -r8.z, r5.w
  71  0x000009BC: max r8.x, r8.x, l(-1.000000)
  72  0x000009D8: min r8.x, r8.x, l(1.000000)
  73  0x000009F4: mul r8.y, r8.x, r8.x
  74  0x00000A10: mul r8.y, r8.y, r8.y
  75  0x00000A2C: mad r8.y, r8.y, l(-0.570320), l(-1.000480)
  76  0x00000A50: add r5.w, r5.w, l(-500.000000)
  77  0x00000A6C: mul_sat r5.w, r5.w, l(-0.010000)
  78  0x00000A88: mad r8.x, r8.y, r8.x, l(-1.570793)
  79  0x00000AAC: mad r5.w, r5.w, r8.x, l(3.141593)
  80  0x00000AD0: min r5.w, r5.w, l(3.141593)
  81  0x00000AEC: add r8.x, -r8.z, l(-250.000000)
  82  0x00000B0C: mul_sat r8.x, r8.x, l(-0.004000)
  83  0x00000B28: add r5.w, r5.w, l(-3.141593)
  84  0x00000B44: mad r5.w, r8.x, r5.w, l(3.141593)
  85  0x00000B68: mov r6.z, -r6.x
  86  0x00000B80: mul r8.xy, r6.yzyy, r7.zwzz
  87  0x00000B9C: mad r8.zw, r8.xxxy, r2.zzzz, r1.zzzw
  88  0x00000BC0: lt r9.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r8.zwzz
  89  0x00000BE8: lt r9.zw, r8.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  90  0x00000C10: iadd r9.xy, -r9.xyxx, r9.zwzz
  91  0x00000C30: ishl r9.xy, r9.xyxx, l(1, 1, 0, 0)
  92  0x00000C58: itof r9.xy, r9.xyxx
  93  0x00000C6C: add r9.zw, |r8.zzzw|, l(0.000000, 0.000000, -1.000000, -1.000000)
  94  0x00000C98: max r9.zw, r9.zzzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  95  0x00000CC0: mad r9.xy, -r9.xyxx, r9.zwzz, r8.zwzz
  96  0x00000CE8: mad r9.xy, r9.xyxx, cb0[20].xyxx, cb0[20].zwzz
  97  0x00000D14: sample_l_indexable(texture2d)(float,float,float,float) r9.x, r9.xyxx, t5.xyzw, s0, r4.w
  98  0x00000D48: mad r9.y, r9.x, cb1[57].x, cb1[57].y
  99  0x00000D74: mad r9.x, r9.x, cb1[57].z, -cb1[57].w
 100  0x00000DA4: rcp r9.x, r9.x
 101  0x00000DB8: add r9.z, r9.x, r9.y
 102  0x00000DD4: mul r8.zw, r8.zzzw, r9.zzzz
 103  0x00000DF0: mul r9.xy, r7.xyxx, r8.zwzz
 104  0x00000E0C: add r9.xyz, -r3.xyzx, r9.xyzx
 105  0x00000E2C: mul r8.zw, r9.xxxy, cb0[18].zzzz
 106  0x00000E4C: mul r9.xy, r8.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
 107  0x00000E74: dp3 r8.z, r9.xyzx, r9.xyzx
 108  0x00000E90: sqrt r8.z, r8.z
 109  0x00000EA4: max r8.z, r8.z, l(0.000100)
 110  0x00000EC0: div r8.w, -r9.z, r8.z
 111  0x00000EE0: max r8.w, r8.w, l(-1.000000)
 112  0x00000EFC: min r8.w, r8.w, l(1.000000)
 113  0x00000F18: mul r9.x, r8.w, r8.w
 114  0x00000F34: mul r9.x, r9.x, r9.x
 115  0x00000F50: mad r9.x, r9.x, l(-0.570320), l(-1.000480)
 116  0x00000F74: add r8.z, r8.z, l(-500.000000)
 117  0x00000F90: mul_sat r8.z, r8.z, l(-0.010000)
 118  0x00000FAC: mad r8.w, r9.x, r8.w, l(-1.570793)
 119  0x00000FD0: mad r8.z, r8.z, r8.w, l(3.141593)
 120  0x00000FF4: min r8.z, r8.z, l(3.141593)
 121  0x00001010: add r8.w, -r9.z, l(-250.000000)
 122  0x00001030: mul_sat r8.w, r8.w, l(-0.004000)
 123  0x0000104C: add r8.z, r8.z, l(-3.141593)
 124  0x00001068: mad r8.z, r8.w, r8.z, l(3.141593)
 125  0x0000108C: mov r6.w, -r5.x
 126  0x000010A4: mul r9.xyzw, r6.zwwx, r7.zwzw
 127  0x000010C0: mad r10.xyzw, r9.xyzw, r2.zzzz, r1.zwzw
 128  0x000010E4: lt r11.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r10.xyzw
 129  0x0000110C: lt r12.xyzw, r10.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
 130  0x00001134: iadd r11.xyzw, -r11.xyzw, r12.xyzw
 131  0x00001154: ishl r11.xyzw, r11.xyzw, l(1, 1, 1, 1)
 132  0x0000117C: itof r11.xyzw, r11.xyzw
 133  0x00001190: add r12.xyzw, |r10.xyzw|, l(-1.000000, -1.000000, -1.000000, -1.000000)
 134  0x000011BC: max r12.xyzw, r12.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
 135  0x000011E4: mad r11.xyzw, -r11.xyzw, r12.xyzw, r10.xyzw
 136  0x0000120C: mad r11.xyzw, r11.xyzw, cb0[20].xyxy, cb0[20].zwzw
 137  0x00001238: sample_l_indexable(texture2d)(float,float,float,float) r2.z, r11.xyxx, t5.yzxw, s0, r4.w
 138  0x0000126C: mad r6.z, r2.z, cb1[57].x, cb1[57].y
 139  0x00001298: mad r2.z, r2.z, cb1[57].z, -cb1[57].w
 140  0x000012C8: rcp r2.z, r2.z
 141  0x000012DC: add r12.z, r2.z, r6.z
 142  0x000012F8: mul r7.zw, r10.xxxy, r12.zzzz
 143  0x00001314: mul r12.xy, r7.xyxx, r7.zwzz
 144  0x00001330: add r12.xyz, -r3.xyzx, r12.xyzx
 145  0x00001350: mul r7.zw, r12.xxxy, cb0[18].zzzz
 146  0x00001370: mul r12.xy, r7.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
 147  0x00001398: dp3 r2.z, r12.xyzx, r12.xyzx
 148  0x000013B4: sqrt r2.z, r2.z
 149  0x000013C8: max r2.z, r2.z, l(0.000100)
 150  0x000013E4: div r6.z, -r12.z, r2.z
 151  0x00001404: max r6.z, r6.z, l(-1.000000)
 152  0x00001420: min r6.z, r6.z, l(1.000000)
 153  0x0000143C: mul r7.z, r6.z, r6.z
 154  0x00001458: mul r7.z, r7.z, r7.z
 155  0x00001474: mad r7.z, r7.z, l(-0.570320), l(-1.000480)
 156  0x00001498: add r2.z, r2.z, l(-500.000000)
 157  0x000014B4: mul_sat r2.z, r2.z, l(-0.010000)
 158  0x000014D0: mad r6.z, r7.z, r6.z, l(-1.570793)
 159  0x000014F4: mad r2.z, r2.z, r6.z, l(3.141593)
 160  0x00001518: min r2.z, r2.z, l(3.141593)
 161  0x00001534: add r6.z, -r12.z, l(-250.000000)
 162  0x00001554: mul_sat r6.z, r6.z, l(-0.004000)
 163  0x00001570: add r2.z, r2.z, l(-3.141593)
 164  0x0000158C: mad r2.z, r6.z, r2.z, l(3.141593)
 165  0x000015B0: sample_l_indexable(texture2d)(float,float,float,float) r4.w, r11.zwzz, t5.yzwx, s0, r4.w
 166  0x000015E4: mad r6.z, r4.w, cb1[57].x, cb1[57].y
 167  0x00001610: mad r4.w, r4.w, cb1[57].z, -cb1[57].w
 168  0x00001640: rcp r4.w, r4.w
 169  0x00001654: add r11.z, r4.w, r6.z
 170  0x00001670: mul r7.zw, r10.zzzw, r11.zzzz
 171  0x0000168C: mul r11.xy, r7.xyxx, r7.zwzz
 172  0x000016A8: add r10.xyz, -r3.xyzx, r11.xyzx
 173  0x000016C8: mul r7.zw, r10.xxxy, cb0[18].zzzz
 174  0x000016E8: mul r10.xy, r7.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
 175  0x00001710: dp3 r4.w, r10.xyzx, r10.xyzx
 176  0x0000172C: sqrt r4.w, r4.w
 177  0x00001740: max r4.w, r4.w, l(0.000100)
 178  0x0000175C: div r6.z, -r10.z, r4.w
 179  0x0000177C: max r6.z, r6.z, l(-1.000000)
 180  0x00001798: min r6.z, r6.z, l(1.000000)
 181  0x000017B4: mul r7.z, r6.z, r6.z
 182  0x000017D0: mul r7.z, r7.z, r7.z
 183  0x000017EC: mad r7.z, r7.z, l(-0.570320), l(-1.000480)
 184  0x00001810: add r4.w, r4.w, l(-500.000000)
 185  0x0000182C: mul_sat r4.w, r4.w, l(-0.010000)
 186  0x00001848: mad r6.z, r7.z, r6.z, l(-1.570793)
 187  0x0000186C: mad r4.w, r4.w, r6.z, l(3.141593)
 188  0x00001890: min r4.w, r4.w, l(3.141593)
 189  0x000018AC: add r6.z, -r10.z, l(-250.000000)
 190  0x000018CC: mul_sat r6.z, r6.z, l(-0.004000)
 191  0x000018E8: add r4.w, r4.w, l(-3.141593)
 192  0x00001904: mad r4.w, r6.z, r4.w, l(3.141593)
 193  0x00001928: add r2.x, r2.x, l(1.000000)
 194  0x00001944: mul r2.x, r2.x, l(0.500000)
 195  0x00001960: mul r2.x, r2.x, r2.x
 196  0x0000197C: mul r2.x, r3.w, r2.x
 197  0x00001998: max r2.x, r2.x, r2.w
 198  0x000019B4: mul r2.y, r2.y, r2.x
 199  0x000019D0: log r2.y, r2.y
 200  0x000019E4: min r2.y, r2.y, l(4.000000)
 201  0x00001A00: mad r5.yz, r5.yyzy, r2.xxxx, r1.zzwz
 202  0x00001A24: lt r7.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r5.yyyz
 203  0x00001A4C: lt r10.xy, r5.yzyy, l(0.000000, 0.000000, 0.000000, 0.000000)
 204  0x00001A74: iadd r7.zw, -r7.zzzw, r10.xxxy
 205  0x00001A94: ishl r7.zw, r7.zzzw, l(0, 0, 1, 1)
 206  0x00001ABC: itof r7.zw, r7.zzzw
 207  0x00001AD0: add r10.xy, |r5.yzyy|, l(-1.000000, -1.000000, 0.000000, 0.000000)
 208  0x00001AFC: max r10.xy, r10.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
 209  0x00001B24: mad r7.zw, -r7.zzzw, r10.xxxy, r5.yyyz
 210  0x00001B4C: mad r7.zw, r7.zzzw, cb0[20].xxxy, cb0[20].zzzw
 211  0x00001B78: sample_l_indexable(texture2d)(float,float,float,float) r2.w, r7.zwzz, t5.yzwx, s0, r2.y
 212  0x00001BAC: mad r3.w, r2.w, cb1[57].x, cb1[57].y
 213  0x00001BD8: mad r2.w, r2.w, cb1[57].z, -cb1[57].w
 214  0x00001C08: rcp r2.w, r2.w
 215  0x00001C1C: add r10.z, r2.w, r3.w
 216  0x00001C38: mul r5.yz, r5.yyzy, r10.zzzz
 217  0x00001C54: mul r10.xy, r7.xyxx, r5.yzyy
 218  0x00001C70: add r10.xyz, -r3.xyzx, r10.xyzx
 219  0x00001C90: mul r5.yz, r10.xxyx, cb0[18].zzzz
 220  0x00001CB0: mul r10.xy, r5.yzyy, l(0.500000, 0.500000, 0.000000, 0.000000)
 221  0x00001CD8: dp3 r2.w, r10.xyzx, r10.xyzx
 222  0x00001CF4: sqrt r2.w, r2.w
 223  0x00001D08: max r2.w, r2.w, l(0.000100)
 224  0x00001D24: div r3.w, -r10.z, r2.w
 225  0x00001D44: max r3.w, r3.w, l(-1.000000)
 226  0x00001D60: min r3.w, r3.w, l(1.000000)
 227  0x00001D7C: mul r5.y, r3.w, r3.w
 228  0x00001D98: mul r5.y, r5.y, r5.y
 229  0x00001DB4: mad r5.y, r5.y, l(-0.570320), l(-1.000480)
 230  0x00001DD8: add r2.w, r2.w, l(-500.000000)
 231  0x00001DF4: mul_sat r2.w, r2.w, l(-0.010000)
 232  0x00001E10: mad r3.w, r5.y, r3.w, l(-1.570793)
 233  0x00001E34: mad r2.w, r2.w, r3.w, l(3.141593)
 234  0x00001E58: min r2.w, r5.w, r2.w
 235  0x00001E74: add r3.w, -r10.z, l(-250.000000)
 236  0x00001E94: mul_sat r3.w, r3.w, l(-0.004000)
 237  0x00001EB0: add r2.w, -r5.w, r2.w
 238  0x00001ED0: mad r2.w, r3.w, r2.w, r5.w
 239  0x00001EF4: mad r5.yz, r8.xxyx, r2.xxxx, r1.zzwz
 240  0x00001F18: lt r7.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r5.yyyz
 241  0x00001F40: lt r8.xy, r5.yzyy, l(0.000000, 0.000000, 0.000000, 0.000000)
 242  0x00001F68: iadd r7.zw, -r7.zzzw, r8.xxxy
 243  0x00001F88: ishl r7.zw, r7.zzzw, l(0, 0, 1, 1)
 244  0x00001FB0: itof r7.zw, r7.zzzw
 245  0x00001FC4: add r8.xy, |r5.yzyy|, l(-1.000000, -1.000000, 0.000000, 0.000000)
 246  0x00001FF0: max r8.xy, r8.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
 247  0x00002018: mad r7.zw, -r7.zzzw, r8.xxxy, r5.yyyz
 248  0x00002040: mad r7.zw, r7.zzzw, cb0[20].xxxy, cb0[20].zzzw
 249  0x0000206C: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r7.zwzz, t5.yzwx, s0, r2.y
 250  0x000020A0: mad r5.w, r3.w, cb1[57].x, cb1[57].y
 251  0x000020CC: mad r3.w, r3.w, cb1[57].z, -cb1[57].w
 252  0x000020FC: rcp r3.w, r3.w
 253  0x00002110: add r10.z, r3.w, r5.w
 254  0x0000212C: mul r5.yz, r5.yyzy, r10.zzzz
 255  0x00002148: mul r10.xy, r7.xyxx, r5.yzyy
 256  0x00002164: add r5.yzw, -r3.xxyz, r10.xxyz
 257  0x00002184: mul r7.zw, r5.yyyz, cb0[18].zzzz
 258  0x000021A4: mul r5.yz, r7.zzwz, l(0.000000, 0.500000, 0.500000, 0.000000)
 259  0x000021CC: dp3 r3.w, r5.yzwy, r5.yzwy
 260  0x000021E8: sqrt r3.w, r3.w
 261  0x000021FC: max r3.w, r3.w, l(0.000100)
 262  0x00002218: div r5.y, -r5.w, r3.w
 263  0x00002238: max r5.y, r5.y, l(-1.000000)
 264  0x00002254: min r5.y, r5.y, l(1.000000)
 265  0x00002270: mul r5.z, r5.y, r5.y
 266  0x0000228C: mul r5.z, r5.z, r5.z
 267  0x000022A8: mad r5.z, r5.z, l(-0.570320), l(-1.000480)
 268  0x000022CC: add r3.w, r3.w, l(-500.000000)
 269  0x000022E8: mul_sat r3.w, r3.w, l(-0.010000)
 270  0x00002304: mad r5.y, r5.z, r5.y, l(-1.570793)
 271  0x00002328: mad r3.w, r3.w, r5.y, l(3.141593)
 272  0x0000234C: min r3.w, r8.z, r3.w
 273  0x00002368: add r5.y, -r5.w, l(-250.000000)
 274  0x00002388: mul_sat r5.y, r5.y, l(-0.004000)
 275  0x000023A4: add r3.w, -r8.z, r3.w
 276  0x000023C4: mad r3.w, r5.y, r3.w, r8.z
 277  0x000023E8: mad r8.xyzw, r9.xyzw, r2.xxxx, r1.zwzw
 278  0x0000240C: lt r9.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000), r8.xyzw
 279  0x00002434: lt r10.xyzw, r8.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
 280  0x0000245C: iadd r9.xyzw, -r9.xyzw, r10.xyzw
 281  0x0000247C: ishl r9.xyzw, r9.xyzw, l(1, 1, 1, 1)
 282  0x000024A4: itof r9.xyzw, r9.xyzw
 283  0x000024B8: add r10.xyzw, |r8.xyzw|, l(-1.000000, -1.000000, -1.000000, -1.000000)
 284  0x000024E4: max r10.xyzw, r10.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
 285  0x0000250C: mad r9.xyzw, -r9.xyzw, r10.xyzw, r8.xyzw
 286  0x00002534: mad r9.xyzw, r9.xyzw, cb0[20].xyxy, cb0[20].zwzw
 287  0x00002560: sample_l_indexable(texture2d)(float,float,float,float) r2.x, r9.xyxx, t5.xyzw, s0, r2.y
 288  0x00002594: mad r5.y, r2.x, cb1[57].x, cb1[57].y
 289  0x000025C0: mad r2.x, r2.x, cb1[57].z, -cb1[57].w
 290  0x000025F0: rcp r2.x, r2.x
 291  0x00002604: add r10.z, r2.x, r5.y
 292  0x00002620: mul r5.yz, r8.xxyx, r10.zzzz
 293  0x0000263C: mul r10.xy, r7.xyxx, r5.yzyy
 294  0x00002658: add r5.yzw, -r3.xxyz, r10.xxyz
 295  0x00002678: mul r7.zw, r5.yyyz, cb0[18].zzzz
 296  0x00002698: mul r5.yz, r7.zzwz, l(0.000000, 0.500000, 0.500000, 0.000000)
 297  0x000026C0: dp3 r2.x, r5.yzwy, r5.yzwy
 298  0x000026DC: sqrt r2.x, r2.x
 299  0x000026F0: max r2.x, r2.x, l(0.000100)
 300  0x0000270C: div r5.y, -r5.w, r2.x
 301  0x0000272C: max r5.y, r5.y, l(-1.000000)
 302  0x00002748: min r5.y, r5.y, l(1.000000)
 303  0x00002764: mul r5.z, r5.y, r5.y
 304  0x00002780: mul r5.z, r5.z, r5.z
 305  0x0000279C: mad r5.z, r5.z, l(-0.570320), l(-1.000480)
 306  0x000027C0: add r2.x, r2.x, l(-500.000000)
 307  0x000027DC: mul_sat r2.x, r2.x, l(-0.010000)
 308  0x000027F8: mad r5.y, r5.z, r5.y, l(-1.570793)
 309  0x0000281C: mad r2.x, r2.x, r5.y, l(3.141593)
 310  0x00002840: min r2.x, r2.z, r2.x
 311  0x0000285C: add r5.y, -r5.w, l(-250.000000)
 312  0x0000287C: mul_sat r5.y, r5.y, l(-0.004000)
 313  0x00002898: add r2.x, -r2.z, r2.x
 314  0x000028B8: mad r2.x, r5.y, r2.x, r2.z
 315  0x000028DC: sample_l_indexable(texture2d)(float,float,float,float) r2.y, r9.zwzz, t5.yxzw, s0, r2.y
 316  0x00002910: mad r2.z, r2.y, cb1[57].x, cb1[57].y
 317  0x0000293C: mad r2.y, r2.y, cb1[57].z, -cb1[57].w
 318  0x0000296C: rcp r2.y, r2.y
 319  0x00002980: add r9.z, r2.y, r2.z
 320  0x0000299C: mul r2.yz, r8.zzwz, r9.zzzz
 321  0x000029B8: mul r9.xy, r7.xyxx, r2.yzyy
 322  0x000029D4: add r5.yzw, -r3.xxyz, r9.xxyz
 323  0x000029F4: mul r2.yz, r5.yyzy, cb0[18].zzzz
 324  0x00002A14: mul r5.yz, r2.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
 325  0x00002A3C: dp3 r2.y, r5.yzwy, r5.yzwy
 326  0x00002A58: sqrt r2.y, r2.y
 327  0x00002A6C: max r2.y, r2.y, l(0.000100)
 328  0x00002A88: div r2.z, -r5.w, r2.y
 329  0x00002AA8: max r2.z, r2.z, l(-1.000000)
 330  0x00002AC4: min r2.z, r2.z, l(1.000000)
 331  0x00002AE0: mul r3.x, r2.z, r2.z
 332  0x00002AFC: mul r3.x, r3.x, r3.x
 333  0x00002B18: mad r3.x, r3.x, l(-0.570320), l(-1.000480)
 334  0x00002B3C: add r2.y, r2.y, l(-500.000000)
 335  0x00002B58: mul_sat r2.y, r2.y, l(-0.010000)
 336  0x00002B74: mad r2.z, r3.x, r2.z, l(-1.570793)
 337  0x00002B98: mad r2.y, r2.y, r2.z, l(3.141593)
 338  0x00002BBC: min r2.y, r4.w, r2.y
 339  0x00002BD8: add r2.z, -r5.w, l(-250.000000)
 340  0x00002BF8: mul_sat r2.z, r2.z, l(-0.004000)
 341  0x00002C14: add r2.y, -r4.w, r2.y
 342  0x00002C34: mad r2.y, r2.z, r2.y, r4.w
 343  0x00002C58: mul r3.xy, r4.yxyy, r5.xxxx
 344  0x00002C74: mad r2.z, r4.x, r6.x, r3.x
 345  0x00002C98: mad r3.x, r4.y, r6.x, -r3.y
 346  0x00002CC0: mad r5.xy, -r6.wxww, r3.xxxx, r4.xyxx
 347  0x00002CE8: mov r5.z, r4.z
 348  0x00002CFC: dp3 r3.y, r5.xyzx, r5.xyzx
 349  0x00002D18: sqrt r3.y, r3.y
 350  0x00002D2C: max r3.y, r3.y, l(0.000100)
 351  0x00002D48: div r4.w, -r4.z, r3.y
 352  0x00002D68: max r4.w, r4.w, l(-1.000000)
 353  0x00002D84: min r4.w, r4.w, l(1.000000)
 354  0x00002DA0: lt r5.w, l(0.000000), r2.z
 355  0x00002DBC: lt r6.z, r2.z, l(0.000000)
 356  0x00002DD8: iadd r5.w, -r5.w, r6.z
 357  0x00002DF8: itof r5.w, r5.w
 358  0x00002E0C: mul r6.z, r4.w, r4.w
 359  0x00002E28: mad r6.w, -r4.w, r4.w, l(1.000000)
 360  0x00002E50: sqrt r6.w, r6.w
 361  0x00002E64: mul r6.w, r5.w, r6.w
 362  0x00002E80: mul r6.z, r6.z, r6.z
 363  0x00002E9C: mad r6.z, r6.z, l(-0.570320), l(-1.000480)
 364  0x00002EC0: mad r4.w, r6.z, r4.w, l(1.570800)
 365  0x00002EE4: mul r6.z, r4.w, r5.w
 366  0x00002F00: mad r2.w, -r5.w, r4.w, r2.w
 367  0x00002F28: min r2.w, r2.w, l(1.570796)
 368  0x00002F44: mad r2.x, -r5.w, r4.w, -r2.x
 369  0x00002F70: max r2.x, r2.x, l(-1.570796)
 370  0x00002F8C: mad r4.w, r6.z, l(2.000000), r2.w
 371  0x00002FB0: add r4.w, r2.x, r4.w
 372  0x00002FCC: mad r2.w, r2.w, l(2.000000), r6.z
 373  0x00002FF0: mad r2.x, r2.x, l(2.000000), r6.z
 374  0x00003014: sincos null, r2.xw, r2.xxxw
 375  0x0000302C: add r2.x, r2.x, r2.w
 376  0x00003048: mul r2.x, r2.x, l(0.500000)
 377  0x00003064: mad r2.x, r4.w, r6.w, -r2.x
 378  0x0000308C: mad r5.xy, -r6.xyxx, r2.zzzz, r4.xyxx
 379  0x000030B4: dp3 r2.z, r5.xyzx, r5.xyzx
 380  0x000030D0: sqrt r2.z, r2.z
 381  0x000030E4: max r2.z, r2.z, l(0.000100)
 382  0x00003100: div r2.w, -r4.z, r2.z
 383  0x00003120: max r2.w, r2.w, l(-1.000000)
 384  0x0000313C: min r2.w, r2.w, l(1.000000)
 385  0x00003158: lt r4.x, l(0.000000), r3.x
 386  0x00003174: lt r3.x, r3.x, l(0.000000)
 387  0x00003190: iadd r3.x, -r4.x, r3.x
 388  0x000031B0: itof r3.x, r3.x
 389  0x000031C4: mul r4.x, r2.w, r2.w
 390  0x000031E0: mad r4.y, -r2.w, r2.w, l(1.000000)
 391  0x00003208: sqrt r4.y, r4.y
 392  0x0000321C: mul r4.y, r3.x, r4.y
 393  0x00003238: mul r4.x, r4.x, r4.x
 394  0x00003254: mad r4.x, r4.x, l(-0.570320), l(-1.000480)
 395  0x00003278: mad r2.w, r4.x, r2.w, l(1.570800)
 396  0x0000329C: mul r4.x, r2.w, r3.x
 397  0x000032B8: mad r2.y, -r3.x, r2.w, r2.y
 398  0x000032E0: min r2.y, r2.y, l(1.570796)
 399  0x000032FC: mad r2.w, -r3.x, r2.w, -r3.w
 400  0x00003328: max r2.w, r2.w, l(-1.570796)
 401  0x00003344: mad r3.x, r4.x, l(2.000000), r2.y
 402  0x00003368: add r3.x, r2.w, r3.x
 403  0x00003384: mad r2.y, r2.y, l(2.000000), r4.x
 404  0x000033A8: mad r2.w, r2.w, l(2.000000), r4.x
 405  0x000033CC: sincos null, r2.yw, r2.yyyw
 406  0x000033E4: add r2.y, r2.w, r2.y
 407  0x00003400: mul r2.y, r2.y, l(0.500000)
 408  0x0000341C: mad r2.y, r3.x, r4.y, -r2.y
 409  0x00003444: mul r2.y, r2.y, r2.z
 410  0x00003460: mad r2.x, r3.y, r2.x, r2.y
 411  0x00003484: mul r2.y, r5.z, l(0.500000)
 412  0x000034A0: mad r2.x, r2.x, l(0.250000), -r2.y
 413  0x000034C8: max r2.w, r2.x, l(0.000000)
 414  0x000034E4: mul r3.xyw, r1.wwww, cb1[115].xyxw
 415  0x00003504: mad r3.xyw, r1.zzzz, cb1[114].xyxw, r3.xyxw
 416  0x0000352C: mad r3.xyw, r0.zzzz, cb1[116].xyxw, r3.xyxw
 417  0x00003554: add r3.xyw, r3.xyxw, cb1[117].xyxw
 418  0x00003574: div r3.xy, r3.xyxx, r3.wwww
 419  0x00003590: mad r3.xy, r1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), -r3.xyxx
 420  0x000035C4: ld_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyww, t4.xyzw
 421  0x000035E8: dp2 r0.z, r0.xyxx, r0.xyxx
 422  0x00003604: lt r0.z, l(0.000000), r0.z
 423  0x00003620: add r0.xy, r0.xyxx, l(-0.499992, -0.499992, 0.000000, 0.000000)
 424  0x00003648: mul r0.xy, r0.xyxx, l(4.008016, 4.008016, 0.000000, 0.000000)
 425  0x00003670: movc r0.xy, r0.zzzz, r0.xyxx, r3.xyxx
 426  0x00003694: mad r0.xy, r1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), -r0.xyxx
 427  0x000036C8: mul r1.xy, r0.xyxx, cb1[125].xyxx
 428  0x000036E8: mad r1.xy, r1.zwzz, cb1[122].xyxx, -r1.xyxx
 429  0x00003714: dp2 r0.w, r1.xyxx, r1.xyxx
 430  0x00003730: sqrt r0.w, r0.w
 431  0x00003744: mul r0.w, r0.w, l(0.012500)
 432  0x00003760: min r2.y, r0.w, l(1.000000)
 433  0x0000377C: max r0.w, |r0.y|, |r0.x|
 434  0x000037A0: lt r0.w, r0.w, l(1.000000)
 435  0x000037BC: if_nz r0.w
 436  0x000037C8:   mad r0.xy, r0.xyxx, cb1[123].xyxx, cb1[123].wzww
 437  0x000037F4:   mul r0.xy, r0.xyxx, cb1[126].xyxx
 438  0x00003814:   add r1.xy, cb1[124].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
 439  0x00003840:   add r1.zw, cb1[124].xxxy, cb1[125].xxxy
 440  0x00003864:   add r1.zw, r1.zzzw, l(0.000000, 0.000000, -0.500000, -0.500000)
 441  0x0000388C:   max r0.xy, r0.xyxx, r1.xyxx
 442  0x000038A8:   min r0.xy, r1.zwzz, r0.xyxx
 443  0x000038C4:   mul r0.xy, r0.xyxx, cb0[1].zwzz
 444  0x000038E4:   sample_l_indexable(texture2d)(float,float,float,float) r0.xyw, r0.xyxx, t3.xywz, s0, l(0.000000)
 445  0x00003918:   ne r1.x, r0.y, l(0.000000)
 446  0x00003934:   mad r0.y, r0.w, l(0.800000), r2.y
 447  0x00003958:   not r0.w, r0.z
 448  0x0000396C:   and r0.w, r1.x, r0.w
 449  0x00003988:   mov r2.x, l(1.000000)
 450  0x0000399C:   movc r2.xy, r0.wwww, r2.wxww, r0.xyxx
 451  0x000039C0: else 
 452  0x000039C4:   mov r2.xy, r2.wyww
 453  0x000039D8: endif 
 454  0x000039DC: movc r2.z, r0.z, -r3.z, r3.z
 455  0x00003A04: mov o0.xyzw, r2.wxyz
 456  0x00003A18: ret 
// Approximately 0 instruction slots used
