//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// SV_POSITION              0   xyzw        1      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[28], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[58], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_sampler s1, mode_default
      0x00000044: dcl_sampler s2, mode_default
      0x00000050: dcl_resource_texture2d (float,float,float,float) t0
      0x00000060: dcl_resource_texture2d (float,float,float,float) t1
      0x00000070: dcl_resource_texture2d (float,float,float,float) t2
      0x00000080: dcl_input_ps linear noperspective v0.xyzw
      0x0000008C: dcl_input_ps_siv linear noperspective v1.xy, position
      0x0000009C: dcl_output o0.xyzw
      0x000000A8: dcl_temps 10
   0  0x000000B0: mad r0.xy, v0.xyxx, cb0[20].xyxx, cb0[22].xyxx
   1  0x000000DC: sample_indexable(texture2d)(float,float,float,float) r0.xy, r0.xyxx, t2.xyzw, s2
   2  0x00000108: mad r0.xyz, r0.xyxx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
   3  0x00000144: sample_indexable(texture2d)(float,float,float,float) r0.w, v0.xyxx, t0.xyzw, s0
   4  0x00000170: mad r1.xy, -r0.wwww, l(131072.000000, 131072.000000, 0.000000, 0.000000), l(1.000000, 1000.000000, 0.000000, 0.000000)
   5  0x000001B0: mul r2.z, r0.w, l(131072.000000)
   6  0x000001CC: mad r1.xy, cb0[21].zzzz, r1.xyxx, r2.zzzz
   7  0x000001F4: mul r0.w, r1.x, cb0[20].z
   8  0x00000214: mul r1.x, r1.y, l(0.080000)
   9  0x00000230: mul r0.xyw, r0.wwww, r0.xyxz
  10  0x0000024C: mov r0.z, -r0.y
  11  0x00000264: mov r3.x, cb0[22].w
  12  0x0000027C: mul r3.y, cb0[20].w, cb0[22].w
  13  0x000002A0: mul r1.y, r2.z, cb0[19].y
  14  0x000002C0: mul r1.y, r1.y, cb0[21].x
  15  0x000002E0: mul r2.xy, r2.zzzz, v0.zwzz
  16  0x000002FC: mov r3.z, l(1.000000)
  17  0x00000310: frc r1.zw, v0.xxxy
  18  0x00000324: sample_indexable(texture2d)(float,float,float,float) r4.xyz, r1.zwzz, t0.xyzw, s0
  19  0x00000350: mad r4.xyz, r4.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
  20  0x0000038C: mul r5.xyz, r4.yyyy, cb1[9].xyzx
  21  0x000003AC: mad r4.xyw, r4.xxxx, cb1[8].xyxz, r5.xyxz
  22  0x000003D4: mad r4.xyz, r4.zzzz, cb1[10].xyzx, r4.xywx
  23  0x000003FC: dp3 r1.z, r4.xyzx, r4.xyzx
  24  0x00000418: rsq r1.z, r1.z
  25  0x0000042C: mul r4.yzw, r1.zzzz, r4.xxyz
  26  0x00000448: mul r5.xyz, r3.xyzx, r4.yzwy
  27  0x00000464: mad r1.yzw, r1.yyyy, r5.xxyz, r2.xxyz
  28  0x00000488: div r2.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.w
  29  0x000004B0: mul r2.xyzw, r2.xxxx, r3.xyxy
  30  0x000004CC: div r3.y, l(1.000000, 1.000000, 1.000000, 1.000000), r3.y
  31  0x000004F4: mul r0.xyzw, r0.xyzw, r2.xyzw
  32  0x00000510: mul r2.xyzw, r0.xyzw, l(0.325000, 0.325000, 0.101000, 0.101000)
  33  0x00000538: add r2.xy, r2.zwzz, r2.xyxx
  34  0x00000554: div r2.zw, r1.yyyz, r1.wwww
  35  0x00000570: mad r5.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.zwzz
  36  0x000005A0: mad r5.zw, cb0[27].xxxy, r5.xxxy, cb0[27].zzzw
  37  0x000005CC: mul r6.xyzw, cb0[23].zzzz, l(0.041667, 0.083333, 0.125000, 0.250000)
  38  0x000005F8: log r6.xyzw, r6.xyzw
  39  0x0000060C: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.z
  40  0x00000640: mad r5.z, r3.w, cb1[57].z, -cb1[57].w
  41  0x00000670: mad r3.w, r3.w, cb1[57].x, cb1[57].y
  42  0x0000069C: div r5.z, l(1.000000, 1.000000, 1.000000, 1.000000), r5.z
  43  0x000006C4: add r7.z, r3.w, r5.z
  44  0x000006E0: mul r7.xy, r5.xyxx, r7.zzzz
  45  0x000006FC: add r5.xyz, -r1.yzwy, r7.xyzx
  46  0x0000071C: div r3.x, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[22].w
  47  0x00000748: mov r3.z, l(1.000000)
  48  0x0000075C: mul r5.xyz, r3.xyzx, r5.xyzx
  49  0x00000778: dp3 r3.w, r5.xyzx, r5.xyzx
  50  0x00000794: mul r7.xyz, r1.xxxx, r4.yzwy
  51  0x000007B0: dp3 r1.x, r5.xyzx, r7.xyzx
  52  0x000007CC: div_sat r5.x, r1.x, r3.w
  53  0x000007E8: mad r5.zw, -r2.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000), r2.zzzw
  54  0x0000081C: mad r8.xy, cb0[27].xyxx, r5.zwzz, cb0[27].zwzz
  55  0x00000848: sample_l_indexable(texture2d)(float,float,float,float) r1.x, r8.xyxx, t1.xyzw, s1, r6.z
  56  0x0000087C: mad r3.w, r1.x, cb1[57].z, -cb1[57].w
  57  0x000008AC: mad r1.x, r1.x, cb1[57].x, cb1[57].y
  58  0x000008D8: div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  59  0x00000900: add r8.z, r1.x, r3.w
  60  0x0000091C: mul r8.xy, r5.zwzz, r8.zzzz
  61  0x00000938: add r8.xyz, -r1.yzwy, r8.xyzx
  62  0x00000958: mul r8.xyz, r3.xyzx, r8.xyzx
  63  0x00000974: dp3 r1.x, r8.xyzx, r8.xyzx
  64  0x00000990: dp3 r3.w, r8.xyzx, r7.xyzx
  65  0x000009AC: div_sat r5.y, r3.w, r1.x
  66  0x000009C8: add r5.zw, r2.xxxy, r2.zzzw
  67  0x000009E4: add r2.xy, -r2.xyxx, r2.zwzz
  68  0x00000A04: mad r8.xy, cb0[27].xyxx, r5.zwzz, cb0[27].zwzz
  69  0x00000A30: sample_l_indexable(texture2d)(float,float,float,float) r1.x, r8.xyxx, t1.xyzw, s1, r6.w
  70  0x00000A64: mad r3.w, r1.x, cb1[57].z, -cb1[57].w
  71  0x00000A94: mad r1.x, r1.x, cb1[57].x, cb1[57].y
  72  0x00000AC0: div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  73  0x00000AE8: add r8.z, r1.x, r3.w
  74  0x00000B04: mul r8.xy, r5.zwzz, r8.zzzz
  75  0x00000B20: add r8.xyz, -r1.yzwy, r8.xyzx
  76  0x00000B40: mul r8.xyz, r3.xyzx, r8.xyzx
  77  0x00000B5C: dp3 r1.x, r8.xyzx, r8.xyzx
  78  0x00000B78: dp3 r3.w, r8.xyzx, r7.xyzx
  79  0x00000B94: div_sat r8.x, r3.w, r1.x
  80  0x00000BB0: mad r5.zw, cb0[27].xxxy, r2.xxxy, cb0[27].zzzw
  81  0x00000BDC: sample_l_indexable(texture2d)(float,float,float,float) r1.x, r5.zwzz, t1.xyzw, s1, r6.w
  82  0x00000C10: mad r3.w, r1.x, cb1[57].z, -cb1[57].w
  83  0x00000C40: mad r1.x, r1.x, cb1[57].x, cb1[57].y
  84  0x00000C6C: div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
  85  0x00000C94: add r9.z, r1.x, r3.w
  86  0x00000CB0: mul r9.xy, r2.xyxx, r9.zzzz
  87  0x00000CCC: add r9.xyz, -r1.yzwy, r9.xyzx
  88  0x00000CEC: mul r9.xyz, r3.xyzx, r9.xyzx
  89  0x00000D08: dp3 r1.x, r9.xyzx, r9.xyzx
  90  0x00000D24: dp3 r2.x, r9.xyzx, r7.xyzx
  91  0x00000D40: div_sat r8.y, r2.x, r1.x
  92  0x00000D5C: max r2.xy, r5.xyxx, r8.xyxx
  93  0x00000D78: add r2.xy, -r2.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
  94  0x00000DA4: mad r5.xyzw, r0.zwzw, l(0.100000, 0.100000, 0.200000, 0.200000), r2.zwzw
  95  0x00000DD4: mad r8.xyzw, cb0[27].xyxy, r5.xyzw, cb0[27].zwzw
  96  0x00000E00: sample_l_indexable(texture2d)(float,float,float,float) r1.x, r8.xyxx, t1.xyzw, s1, r6.x
  97  0x00000E34: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r8.zwzz, t1.yzwx, s1, r6.y
  98  0x00000E68: mad r4.w, r1.x, cb1[57].z, -cb1[57].w
  99  0x00000E98: mad r1.x, r1.x, cb1[57].x, cb1[57].y
 100  0x00000EC4: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 101  0x00000EEC: add r8.z, r1.x, r4.w
 102  0x00000F08: mul r8.xy, r5.xyxx, r8.zzzz
 103  0x00000F24: add r8.xyz, -r1.yzwy, r8.xyzx
 104  0x00000F44: mul r8.xyz, r3.xyzx, r8.xyzx
 105  0x00000F60: dp3 r1.x, r8.xyzx, r8.xyzx
 106  0x00000F7C: dp3 r4.w, r8.xyzx, r7.xyzx
 107  0x00000F98: div_sat r5.x, r4.w, r1.x
 108  0x00000FB4: mad r8.xyzw, -r0.zwzw, l(0.100000, 0.100000, 0.200000, 0.200000), r2.zwzw
 109  0x00000FE8: mad r9.xyzw, cb0[27].xyxy, r8.xyzw, cb0[27].zwzw
 110  0x00001014: sample_l_indexable(texture2d)(float,float,float,float) r1.x, r9.xyxx, t1.xyzw, s1, r6.x
 111  0x00001048: sample_l_indexable(texture2d)(float,float,float,float) r4.w, r9.zwzz, t1.yzwx, s1, r6.y
 112  0x0000107C: mad r6.x, r1.x, cb1[57].z, -cb1[57].w
 113  0x000010AC: mad r1.x, r1.x, cb1[57].x, cb1[57].y
 114  0x000010D8: div r6.x, l(1.000000, 1.000000, 1.000000, 1.000000), r6.x
 115  0x00001100: add r6.z, r1.x, r6.x
 116  0x0000111C: mul r6.xy, r6.zzzz, r8.xyxx
 117  0x00001138: add r6.xyz, -r1.yzwy, r6.xyzx
 118  0x00001158: mul r6.xyz, r3.xyzx, r6.xyzx
 119  0x00001174: dp3 r1.x, r6.xyzx, r6.xyzx
 120  0x00001190: dp3 r6.x, r6.xyzx, r7.xyzx
 121  0x000011AC: div_sat r5.y, r6.x, r1.x
 122  0x000011C8: mad r1.x, r3.w, cb1[57].z, -cb1[57].w
 123  0x000011F8: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 124  0x00001224: div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
 125  0x0000124C: add r6.z, r1.x, r3.w
 126  0x00001268: mul r6.xy, r5.zwzz, r6.zzzz
 127  0x00001284: add r6.xyz, -r1.yzwy, r6.xyzx
 128  0x000012A4: mul r6.xyz, r3.xyzx, r6.xyzx
 129  0x000012C0: dp3 r1.x, r6.xyzx, r6.xyzx
 130  0x000012DC: dp3 r3.w, r6.xyzx, r7.xyzx
 131  0x000012F8: div_sat r6.x, r3.w, r1.x
 132  0x00001314: mad r1.x, r4.w, cb1[57].z, -cb1[57].w
 133  0x00001344: mad r3.w, r4.w, cb1[57].x, cb1[57].y
 134  0x00001370: div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
 135  0x00001398: add r9.z, r1.x, r3.w
 136  0x000013B4: mul r9.xy, r8.zwzz, r9.zzzz
 137  0x000013D0: add r8.xyz, -r1.yzwy, r9.xyzx
 138  0x000013F0: mul r8.xyz, r3.xyzx, r8.xyzx
 139  0x0000140C: dp3 r1.x, r8.xyzx, r8.xyzx
 140  0x00001428: dp3 r3.w, r8.xyzx, r7.xyzx
 141  0x00001444: div_sat r6.y, r3.w, r1.x
 142  0x00001460: max r5.xy, r5.xyxx, r6.xyxx
 143  0x0000147C: add r5.xy, -r5.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 144  0x000014A8: mad r1.x, r5.x, r5.x, l(0.000100)
 145  0x000014CC: mad r1.x, r5.y, r5.y, r1.x
 146  0x000014F0: mad r1.x, r2.x, r2.x, r1.x
 147  0x00001514: mad r1.x, r2.y, r2.y, r1.x
 148  0x00001538: mul r5.xyzw, r0.xyzw, l(0.272000, 0.272000, -0.396000, -0.396000)
 149  0x00001560: add r2.xy, r5.zwzz, r5.xyxx
 150  0x0000157C: mad r5.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.zwzz
 151  0x000015AC: mad r5.zw, cb0[27].xxxy, r5.xxxy, cb0[27].zzzw
 152  0x000015D8: mul r6.xyzw, cb0[23].zzzz, l(0.208333, 0.416667, 0.291667, 0.583333)
 153  0x00001604: log r6.xyzw, r6.xyzw
 154  0x00001618: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.x
 155  0x0000164C: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 156  0x0000167C: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 157  0x000016A8: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 158  0x000016D0: add r8.z, r3.w, r4.w
 159  0x000016EC: mul r8.xy, r5.xyxx, r8.zzzz
 160  0x00001708: add r5.xyz, -r1.yzwy, r8.xyzx
 161  0x00001728: mul r5.xyz, r3.xyzx, r5.xyzx
 162  0x00001744: dp3 r3.w, r5.xyzx, r5.xyzx
 163  0x00001760: dp3 r4.w, r5.xyzx, r7.xyzx
 164  0x0000177C: div_sat r5.x, r4.w, r3.w
 165  0x00001798: mad r5.zw, -r2.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000), r2.zzzw
 166  0x000017CC: mad r8.xy, cb0[27].xyxx, r5.zwzz, cb0[27].zwzz
 167  0x000017F8: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r8.xyxx, t1.yzwx, s1, r6.x
 168  0x0000182C: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 169  0x0000185C: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 170  0x00001888: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 171  0x000018B0: add r8.z, r3.w, r4.w
 172  0x000018CC: mul r8.xy, r5.zwzz, r8.zzzz
 173  0x000018E8: add r8.xyz, -r1.yzwy, r8.xyzx
 174  0x00001908: mul r8.xyz, r3.xyzx, r8.xyzx
 175  0x00001924: dp3 r3.w, r8.xyzx, r8.xyzx
 176  0x00001940: dp3 r4.w, r8.xyzx, r7.xyzx
 177  0x0000195C: div_sat r5.y, r4.w, r3.w
 178  0x00001978: add r5.zw, r2.xxxy, r2.zzzw
 179  0x00001994: add r2.xy, -r2.xyxx, r2.zwzz
 180  0x000019B4: mad r8.xy, cb0[27].xyxx, r5.zwzz, cb0[27].zwzz
 181  0x000019E0: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r8.xyxx, t1.yzwx, s1, r6.y
 182  0x00001A14: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 183  0x00001A44: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 184  0x00001A70: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 185  0x00001A98: add r8.z, r3.w, r4.w
 186  0x00001AB4: mul r8.xy, r5.zwzz, r8.zzzz
 187  0x00001AD0: add r8.xyz, -r1.yzwy, r8.xyzx
 188  0x00001AF0: mul r8.xyz, r3.xyzx, r8.xyzx
 189  0x00001B0C: dp3 r3.w, r8.xyzx, r8.xyzx
 190  0x00001B28: dp3 r4.w, r8.xyzx, r7.xyzx
 191  0x00001B44: div_sat r8.x, r4.w, r3.w
 192  0x00001B60: mad r5.zw, cb0[27].xxxy, r2.xxxy, cb0[27].zzzw
 193  0x00001B8C: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.y
 194  0x00001BC0: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 195  0x00001BF0: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 196  0x00001C1C: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 197  0x00001C44: add r9.z, r3.w, r4.w
 198  0x00001C60: mul r9.xy, r2.xyxx, r9.zzzz
 199  0x00001C7C: add r9.xyz, -r1.yzwy, r9.xyzx
 200  0x00001C9C: mul r9.xyz, r3.xyzx, r9.xyzx
 201  0x00001CB8: dp3 r2.x, r9.xyzx, r9.xyzx
 202  0x00001CD4: dp3 r2.y, r9.xyzx, r7.xyzx
 203  0x00001CF0: div_sat r8.y, r2.y, r2.x
 204  0x00001D0C: max r2.xy, r5.xyxx, r8.xyxx
 205  0x00001D28: add r2.xy, -r2.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 206  0x00001D54: mad r1.x, r2.x, r2.x, r1.x
 207  0x00001D78: mad r1.x, r2.y, r2.y, r1.x
 208  0x00001D9C: mul r5.xyzw, r0.xyzw, l(-0.385000, -0.385000, -0.488000, -0.488000)
 209  0x00001DC4: add r2.xy, r5.zwzz, r5.xyxx
 210  0x00001DE0: mad r5.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.zwzz
 211  0x00001E10: mad r5.zw, cb0[27].xxxy, r5.xxxy, cb0[27].zzzw
 212  0x00001E3C: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.z
 213  0x00001E70: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 214  0x00001EA0: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 215  0x00001ECC: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 216  0x00001EF4: add r8.z, r3.w, r4.w
 217  0x00001F10: mul r8.xy, r5.xyxx, r8.zzzz
 218  0x00001F2C: add r5.xyz, -r1.yzwy, r8.xyzx
 219  0x00001F4C: mul r5.xyz, r3.xyzx, r5.xyzx
 220  0x00001F68: dp3 r3.w, r5.xyzx, r5.xyzx
 221  0x00001F84: dp3 r4.w, r5.xyzx, r7.xyzx
 222  0x00001FA0: div_sat r5.x, r4.w, r3.w
 223  0x00001FBC: mad r5.zw, -r2.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000), r2.zzzw
 224  0x00001FF0: mad r6.xy, cb0[27].xyxx, r5.zwzz, cb0[27].zwzz
 225  0x0000201C: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r6.xyxx, t1.yzwx, s1, r6.z
 226  0x00002050: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 227  0x00002080: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 228  0x000020AC: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 229  0x000020D4: add r6.z, r3.w, r4.w
 230  0x000020F0: mul r6.xy, r5.zwzz, r6.zzzz
 231  0x0000210C: add r6.xyz, -r1.yzwy, r6.xyzx
 232  0x0000212C: mul r6.xyz, r3.xyzx, r6.xyzx
 233  0x00002148: dp3 r3.w, r6.xyzx, r6.xyzx
 234  0x00002164: dp3 r4.w, r6.xyzx, r7.xyzx
 235  0x00002180: div_sat r5.y, r4.w, r3.w
 236  0x0000219C: add r5.zw, r2.xxxy, r2.zzzw
 237  0x000021B8: add r2.xy, -r2.xyxx, r2.zwzz
 238  0x000021D8: mad r6.xy, cb0[27].xyxx, r5.zwzz, cb0[27].zwzz
 239  0x00002204: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r6.xyxx, t1.yzwx, s1, r6.w
 240  0x00002238: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 241  0x00002268: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 242  0x00002294: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 243  0x000022BC: add r6.z, r3.w, r4.w
 244  0x000022D8: mul r6.xy, r5.zwzz, r6.zzzz
 245  0x000022F4: add r6.xyz, -r1.yzwy, r6.xyzx
 246  0x00002314: mul r6.xyz, r3.xyzx, r6.xyzx
 247  0x00002330: dp3 r3.w, r6.xyzx, r6.xyzx
 248  0x0000234C: dp3 r4.w, r6.xyzx, r7.xyzx
 249  0x00002368: div_sat r6.x, r4.w, r3.w
 250  0x00002384: mad r5.zw, cb0[27].xxxy, r2.xxxy, cb0[27].zzzw
 251  0x000023B0: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.w
 252  0x000023E4: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 253  0x00002414: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 254  0x00002440: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 255  0x00002468: add r8.z, r3.w, r4.w
 256  0x00002484: mul r8.xy, r2.xyxx, r8.zzzz
 257  0x000024A0: add r8.xyz, -r1.yzwy, r8.xyzx
 258  0x000024C0: mul r8.xyz, r3.xyzx, r8.xyzx
 259  0x000024DC: dp3 r2.x, r8.xyzx, r8.xyzx
 260  0x000024F8: dp3 r2.y, r8.xyzx, r7.xyzx
 261  0x00002514: div_sat r6.y, r2.y, r2.x
 262  0x00002530: max r2.xy, r5.xyxx, r6.xyxx
 263  0x0000254C: add r2.xy, -r2.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 264  0x00002578: mad r1.x, r2.x, r2.x, r1.x
 265  0x0000259C: mad r1.x, r2.y, r2.y, r1.x
 266  0x000025C0: mul r5.xyzw, r0.xyzw, l(-0.711000, -0.711000, 0.274000, 0.274000)
 267  0x000025E8: mul r0.xyzw, r0.xyzw, l(0.060000, 0.060000, 0.900000, 0.900000)
 268  0x00002610: add r0.xy, r0.zwzz, r0.xyxx
 269  0x0000262C: add r0.zw, r5.zzzw, r5.xxxy
 270  0x00002648: mad r2.xy, r0.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000), r2.zwzz
 271  0x00002678: mad r5.xy, cb0[27].xyxx, r2.xyxx, cb0[27].zwzz
 272  0x000026A4: mul r6.xyzw, cb0[23].zzzz, l(0.375000, 0.750000, 0.458333, 0.916667)
 273  0x000026D0: log r6.xyzw, r6.xyzw
 274  0x000026E4: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.xyxx, t1.yzwx, s1, r6.x
 275  0x00002718: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 276  0x00002748: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 277  0x00002774: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 278  0x0000279C: add r5.z, r3.w, r4.w
 279  0x000027B8: mul r5.xy, r2.xyxx, r5.zzzz
 280  0x000027D4: add r5.xyz, -r1.yzwy, r5.xyzx
 281  0x000027F4: mul r5.xyz, r3.xyzx, r5.xyzx
 282  0x00002810: dp3 r2.x, r5.xyzx, r5.xyzx
 283  0x0000282C: dp3 r2.y, r5.xyzx, r7.xyzx
 284  0x00002848: div_sat r2.x, r2.y, r2.x
 285  0x00002864: mad r5.xy, -r0.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000), r2.zwzz
 286  0x00002898: mad r5.zw, cb0[27].xxxy, r5.xxxy, cb0[27].zzzw
 287  0x000028C4: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.x
 288  0x000028F8: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 289  0x00002928: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 290  0x00002954: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 291  0x0000297C: add r8.z, r3.w, r4.w
 292  0x00002998: mul r8.xy, r5.xyxx, r8.zzzz
 293  0x000029B4: add r5.xyz, -r1.yzwy, r8.xyzx
 294  0x000029D4: mul r5.xyz, r3.xyzx, r5.xyzx
 295  0x000029F0: dp3 r3.w, r5.xyzx, r5.xyzx
 296  0x00002A0C: dp3 r4.w, r5.xyzx, r7.xyzx
 297  0x00002A28: div_sat r2.y, r4.w, r3.w
 298  0x00002A44: add r5.xy, r0.zwzz, r2.zwzz
 299  0x00002A60: add r0.zw, -r0.zzzw, r2.zzzw
 300  0x00002A80: mad r5.zw, cb0[27].xxxy, r5.xxxy, cb0[27].zzzw
 301  0x00002AAC: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.y
 302  0x00002AE0: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 303  0x00002B10: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 304  0x00002B3C: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 305  0x00002B64: add r8.z, r3.w, r4.w
 306  0x00002B80: mul r8.xy, r5.xyxx, r8.zzzz
 307  0x00002B9C: add r5.xyz, -r1.yzwy, r8.xyzx
 308  0x00002BBC: mul r5.xyz, r3.xyzx, r5.xyzx
 309  0x00002BD8: dp3 r3.w, r5.xyzx, r5.xyzx
 310  0x00002BF4: dp3 r4.w, r5.xyzx, r7.xyzx
 311  0x00002C10: div_sat r5.x, r4.w, r3.w
 312  0x00002C2C: mad r5.zw, cb0[27].xxxy, r0.zzzw, cb0[27].zzzw
 313  0x00002C58: sample_l_indexable(texture2d)(float,float,float,float) r3.w, r5.zwzz, t1.yzwx, s1, r6.y
 314  0x00002C8C: mad r4.w, r3.w, cb1[57].z, -cb1[57].w
 315  0x00002CBC: mad r3.w, r3.w, cb1[57].x, cb1[57].y
 316  0x00002CE8: div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
 317  0x00002D10: add r8.z, r3.w, r4.w
 318  0x00002D2C: mul r8.xy, r0.zwzz, r8.zzzz
 319  0x00002D48: add r8.xyz, -r1.yzwy, r8.xyzx
 320  0x00002D68: mul r8.xyz, r3.xyzx, r8.xyzx
 321  0x00002D84: dp3 r0.z, r8.xyzx, r8.xyzx
 322  0x00002DA0: dp3 r0.w, r8.xyzx, r7.xyzx
 323  0x00002DBC: div_sat r5.y, r0.w, r0.z
 324  0x00002DD8: max r0.zw, r2.xxxy, r5.xxxy
 325  0x00002DF4: add r0.zw, -r0.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
 326  0x00002E20: mad r0.z, r0.z, r0.z, r1.x
 327  0x00002E44: mad r0.z, r0.w, r0.w, r0.z
 328  0x00002E68: mad r2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.zwzz
 329  0x00002E98: mad r5.xy, cb0[27].xyxx, r2.xyxx, cb0[27].zwzz
 330  0x00002EC4: sample_l_indexable(texture2d)(float,float,float,float) r0.w, r5.xyxx, t1.yzwx, s1, r6.z
 331  0x00002EF8: mad r1.x, r0.w, cb1[57].z, -cb1[57].w
 332  0x00002F28: mad r0.w, r0.w, cb1[57].x, cb1[57].y
 333  0x00002F54: div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
 334  0x00002F7C: add r5.z, r0.w, r1.x
 335  0x00002F98: mul r5.xy, r2.xyxx, r5.zzzz
 336  0x00002FB4: add r5.xyz, -r1.yzwy, r5.xyzx
 337  0x00002FD4: mul r5.xyz, r3.xyzx, r5.xyzx
 338  0x00002FF0: dp3 r0.w, r5.xyzx, r5.xyzx
 339  0x0000300C: dp3 r1.x, r5.xyzx, r7.xyzx
 340  0x00003028: div_sat r2.x, r1.x, r0.w
 341  0x00003044: mad r5.xy, -r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r2.zwzz
 342  0x00003078: mad r5.zw, cb0[27].xxxy, r5.xxxy, cb0[27].zzzw
 343  0x000030A4: sample_l_indexable(texture2d)(float,float,float,float) r0.w, r5.zwzz, t1.yzwx, s1, r6.z
 344  0x000030D8: mad r1.x, r0.w, cb1[57].z, -cb1[57].w
 345  0x00003108: mad r0.w, r0.w, cb1[57].x, cb1[57].y
 346  0x00003134: div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
 347  0x0000315C: add r6.z, r0.w, r1.x
 348  0x00003178: mul r6.xy, r5.xyxx, r6.zzzz
 349  0x00003194: add r5.xyz, -r1.yzwy, r6.xyzx
 350  0x000031B4: mul r5.xyz, r3.xyzx, r5.xyzx
 351  0x000031D0: dp3 r0.w, r5.xyzx, r5.xyzx
 352  0x000031EC: dp3 r1.x, r5.xyzx, r7.xyzx
 353  0x00003208: div_sat r2.y, r1.x, r0.w
 354  0x00003224: add r5.xy, r0.xyxx, r2.zwzz
 355  0x00003240: add r0.xy, -r0.xyxx, r2.zwzz
 356  0x00003260: mad r2.zw, cb0[27].xxxy, r5.xxxy, cb0[27].zzzw
 357  0x0000328C: sample_l_indexable(texture2d)(float,float,float,float) r0.w, r2.zwzz, t1.yzwx, s1, r6.w
 358  0x000032C0: mad r1.x, r0.w, cb1[57].z, -cb1[57].w
 359  0x000032F0: mad r0.w, r0.w, cb1[57].x, cb1[57].y
 360  0x0000331C: div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
 361  0x00003344: add r6.z, r0.w, r1.x
 362  0x00003360: mul r6.xy, r5.xyxx, r6.zzzz
 363  0x0000337C: add r5.xyz, -r1.yzwy, r6.xyzx
 364  0x0000339C: mul r5.xyz, r3.xyzx, r5.xyzx
 365  0x000033B8: dp3 r0.w, r5.xyzx, r7.xyzx
 366  0x000033D4: dp3 r1.x, r5.xyzx, r5.xyzx
 367  0x000033F0: div_sat r5.x, r0.w, r1.x
 368  0x0000340C: mad r2.zw, cb0[27].xxxy, r0.xxxy, cb0[27].zzzw
 369  0x00003438: sample_l_indexable(texture2d)(float,float,float,float) r0.w, r2.zwzz, t1.yzwx, s1, r6.w
 370  0x0000346C: mad r1.x, r0.w, cb1[57].z, -cb1[57].w
 371  0x0000349C: mad r0.w, r0.w, cb1[57].x, cb1[57].y
 372  0x000034C8: div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
 373  0x000034F0: add r6.z, r0.w, r1.x
 374  0x0000350C: mul r6.xy, r0.xyxx, r6.zzzz
 375  0x00003528: add r0.xyw, -r1.yzyw, r6.xyxz
 376  0x00003548: mul r0.xyw, r3.xyxz, r0.xyxw
 377  0x00003564: dp3 r1.x, r0.xywx, r7.xyzx
 378  0x00003580: dp3 r0.x, r0.xywx, r0.xywx
 379  0x0000359C: div_sat r5.y, r1.x, r0.x
 380  0x000035B8: max r0.xy, r2.xyxx, r5.xyxx
 381  0x000035D4: add r0.xy, -r0.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
 382  0x00003600: mad r0.x, r0.x, r0.x, r0.z
 383  0x00003624: mad r0.x, r0.y, r0.y, r0.x
 384  0x00003648: mul r4.x, r0.x, l(0.083333)
 385  0x00003664: deriv_rtx_fine r0.xyz, r4.xyzx
 386  0x00003678: ftou r1.xy, v1.xyxx
 387  0x0000368C: bfi r1.xy, l(1, 1, 0, 0), l(1, 1, 0, 0), r1.xyxx, l(0, 0, 0, 0)
 388  0x000036DC: iadd r1.xy, r1.xyxx, l(-1, -1, 0, 0)
 389  0x00003704: itof r1.xy, r1.xyxx
 390  0x00003718: mad r0.xyz, -r0.xyzx, r1.xxxx, r4.xyzx
 391  0x00003740: dp2 r1.x, r0.yzyy, r0.yzyy
 392  0x0000375C: add r1.x, -r1.x, l(1.000000)
 393  0x0000377C: sqrt r0.w, r1.x
 394  0x00003790: dp2 r1.x, r4.yzyy, r4.yzyy
 395  0x000037AC: add r1.x, -r1.x, l(1.000000)
 396  0x000037CC: sqrt r2.z, r1.x
 397  0x000037E0: mov r2.xy, r4.yzyy
 398  0x000037F4: dp3_sat r0.y, r2.xyzx, r0.yzwy
 399  0x00003810: mul r0.y, r0.y, r0.y
 400  0x0000382C: mul r0.y, r0.y, r0.y
 401  0x00003848: deriv_rty_fine r1.xzw, r4.xxyz
 402  0x0000385C: mad r1.xyz, -r1.xzwx, r1.yyyy, r4.xyzx
 403  0x00003884: dp2 r0.z, r1.yzyy, r1.yzyy
 404  0x000038A0: add r0.z, -r0.z, l(1.000000)
 405  0x000038C0: sqrt r1.w, r0.z
 406  0x000038D4: dp3_sat r0.z, r2.xyzx, r1.yzwy
 407  0x000038F0: mul r0.z, r0.z, r0.z
 408  0x0000390C: mad r0.w, r0.z, r0.z, r0.y
 409  0x00003930: add r0.w, r0.w, l(1.000000)
 410  0x0000394C: div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
 411  0x00003974: mul r0.yz, r0.wwzw, r0.yyzy
 412  0x00003990: mul r0.x, r0.x, r0.y
 413  0x000039AC: mad r0.x, r0.w, r4.x, r0.x
 414  0x000039D0: mul r0.y, r0.w, r0.z
 415  0x000039EC: mad o0.xyzw, r0.yyyy, r1.xxxx, r0.xxxx
 416  0x00003A10: ret 
// Approximately 0 instruction slots used
