//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// TEXCOORD                 3     zw        0     NONE   float       
// TEXCOORD                 1   xyz         1     NONE   float   x   
// TEXCOORD                 2   xyzw        2     NONE   float       
// TEXCOORD                 4   xy          3     NONE   float       
// SV_POSITION              0   xyzw        4      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[48], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[141], dynamicIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_sampler s1, mode_default
      0x00000044: dcl_sampler s2, mode_default
      0x00000050: dcl_sampler s3, mode_default
      0x0000005C: dcl_resource_texture2d (float,float,float,float) t0
      0x0000006C: dcl_resource_texture2d (float,float,float,float) t1
      0x0000007C: dcl_resource_texture2d (float,float,float,float) t2
      0x0000008C: dcl_resource_texture2d (float,float,float,float) t3
      0x0000009C: dcl_input_ps linear noperspective v0.xy
      0x000000A8: dcl_input_ps linear noperspective v1.x
      0x000000B4: dcl_output o0.xyzw
      0x000000C0: dcl_temps 10
   0  0x000000C8: mad r0.xy, v0.xyxx, cb1[140].xyxx, -cb1[138].xyxx
   1  0x000000F8: mul r0.xy, r0.xyxx, cb1[139].zwzz
   2  0x00000118: add r1.xy, r0.xyxx, r0.xyxx
   3  0x00000134: mad r0.z, r0.x, l(2.000000), l(-1.000000)
   4  0x00000158: mad r0.w, -r0.y, l(2.000000), l(1.000000)
   5  0x00000180: mad r0.xy, r0.xyxx, cb0[42].xyxx, cb0[42].zwzz
   6  0x000001AC: sample_l_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r2.x, r0.xyxx, t0.xyzw, s0, l(0.000000)
   7  0x000001E4: sample_l_aoffimmi_indexable(-2,-2,0)(texture2d)(float,float,float,float) r2.w, r0.xyxx, t0.yzwx, s0, l(0.000000)
   8  0x0000021C: sample_l_aoffimmi_indexable(2,-2,0)(texture2d)(float,float,float,float) r3.x, r0.xyxx, t0.xyzw, s0, l(0.000000)
   9  0x00000254: sample_l_aoffimmi_indexable(-2,2,0)(texture2d)(float,float,float,float) r3.y, r0.xyxx, t0.yxzw, s0, l(0.000000)
  10  0x0000028C: sample_l_aoffimmi_indexable(2,2,0)(texture2d)(float,float,float,float) r3.z, r0.xyxx, t0.yzxw, s0, l(0.000000)
  11  0x000002C4: lt r3.w, r3.x, r2.w
  12  0x000002E0: movc r4.y, r3.w, l(-2.000000), l(2.000000)
  13  0x00000304: lt r3.w, r3.z, r3.y
  14  0x00000320: movc r5.y, r3.w, l(-2.000000), l(2.000000)
  15  0x00000344: max r2.w, r2.w, r3.x
  16  0x00000360: max r3.x, r3.z, r3.y
  17  0x0000037C: lt r3.y, r3.x, r2.w
  18  0x00000398: mov r4.z, l(-2.000000)
  19  0x000003AC: mov r5.z, l(2.000000)
  20  0x000003C0: movc r3.yz, r3.yyyy, r4.yyzy, r5.yyzy
  21  0x000003E4: max r4.x, r2.w, r3.x
  22  0x00000400: lt r2.w, r2.x, r4.x
  23  0x0000041C: mul r4.yz, r3.yyzy, cb0[0].zzwz
  24  0x0000043C: mov r2.yz, l(0,0,0,0)
  25  0x0000045C: movc r2.xyz, r2.wwww, r4.xyzx, r2.xyzx
  26  0x00000480: ge r2.w, r2.x, l(0.875000)
  27  0x0000049C: bfi r2.w, l(1), l(2), r2.w, l(0)
  28  0x000004C8: mul r3.xyz, r0.wwww, cb1[r2.w + 128].xywx
  29  0x000004F0: mad r3.xyz, r0.zzzz, cb1[r2.w + 127].xywx, r3.xyzx
  30  0x00000520: mad r3.xyz, r2.xxxx, cb1[r2.w + 129].xywx, r3.xyzx
  31  0x00000550: add r3.xyz, r3.xyzx, cb1[r2.w + 130].xywx
  32  0x00000578: div r0.zw, r3.yyyx, r3.zzzz
  33  0x00000594: mad r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, -1.000000), l(0.000000, 0.000000, -1.000000, 1.000000)
  34  0x000005D0: add r0.zw, -r0.zzzw, r1.wwwz
  35  0x000005F0: add r1.yz, r0.xxyx, r2.yyzy
  36  0x0000060C: sample_l_indexable(texture2d)(float,float,float,float) r1.yz, r1.yzyy, t2.zxyw, s2, l(0.000000)
  37  0x00000640: lt r2.x, l(0.000000), r1.y
  38  0x0000065C: mad r1.yz, r1.zzyz, l(0.000000, 4.008016, 4.008016, 0.000000), l(0.000000, -2.003978, -2.003978, 0.000000)
  39  0x00000698: movc r0.zw, r2.xxxx, r1.yyyz, r0.zzzw
  40  0x000006BC: mul r1.yz, r0.wwzw, cb0[22].xxyx
  41  0x000006DC: dp2 r1.y, r1.yzyy, r1.yzyy
  42  0x000006F8: sqrt r1.y, r1.y
  43  0x0000070C: add r1.xz, r1.xxwx, l(-1.000000, 0.000000, 0.000000, 0.000000)
  44  0x00000734: add r0.zw, -r0.zzzw, r1.zzzx
  45  0x00000754: max r1.w, |r0.z|, |r0.w|
  46  0x00000778: sample_l_aoffimmi_indexable(0,-1,0)(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t1.xyzw, s1, l(0.000000)
  47  0x000007B0: dp3 r3.x, r2.xzyx, l(1.000000, 1.000000, 2.000000, 0.000000)
  48  0x000007D8: dp2 r3.y, r2.xzxx, l(2.000000, -2.000000, 0.000000, 0.000000)
  49  0x00000800: dp3 r3.z, r2.xzyx, l(-1.000000, -1.000000, 2.000000, 0.000000)
  50  0x00000828: sample_l_aoffimmi_indexable(-1,0,0)(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t1.xyzw, s1, l(0.000000)
  51  0x00000860: dp3 r4.x, r2.xzyx, l(1.000000, 1.000000, 2.000000, 0.000000)
  52  0x00000888: dp2 r4.y, r2.xzxx, l(2.000000, -2.000000, 0.000000, 0.000000)
  53  0x000008B0: dp3 r4.z, r2.xzyx, l(-1.000000, -1.000000, 2.000000, 0.000000)
  54  0x000008D8: sample_l_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t1.xyzw, s1, l(0.000000)
  55  0x00000910: dp3 r5.x, r2.xzyx, l(1.000000, 1.000000, 2.000000, 0.000000)
  56  0x00000938: dp2 r5.y, r2.xzxx, l(2.000000, -2.000000, 0.000000, 0.000000)
  57  0x00000960: dp3 r5.z, r2.xzyx, l(-1.000000, -1.000000, 2.000000, 0.000000)
  58  0x00000988: sample_l_aoffimmi_indexable(1,0,0)(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t1.xyzw, s1, l(0.000000)
  59  0x000009C0: dp3 r6.x, r2.xzyx, l(1.000000, 1.000000, 2.000000, 0.000000)
  60  0x000009E8: dp2 r6.y, r2.xzxx, l(2.000000, -2.000000, 0.000000, 0.000000)
  61  0x00000A10: dp3 r6.z, r2.xzyx, l(-1.000000, -1.000000, 2.000000, 0.000000)
  62  0x00000A38: sample_l_aoffimmi_indexable(0,1,0)(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t1.xyzw, s1, l(0.000000)
  63  0x00000A70: dp3 r7.x, r2.xzyx, l(1.000000, 1.000000, 2.000000, 0.000000)
  64  0x00000A98: dp2 r7.y, r2.xzxx, l(2.000000, -2.000000, 0.000000, 0.000000)
  65  0x00000AC0: dp3 r7.z, r2.xzyx, l(-1.000000, -1.000000, 2.000000, 0.000000)
  66  0x00000AE8: mad r1.xz, cb0[22].zzwz, l(2.000000, 0.000000, 2.000000, 0.000000), |r1.xxzx|
  67  0x00000B20: max r1.x, r1.z, r1.x
  68  0x00000B3C: ge r1.xw, r1.xxxw, l(1.000000, 0.000000, 0.000000, 1.000000)
  69  0x00000B64: if_nz r1.x
  70  0x00000B70:   mov r2.xyz, r5.xyzx
  71  0x00000B84: else 
  72  0x00000B88:   mad r1.x, r3.x, v1.x, l(4.000000)
  73  0x00000BAC:   rcp r1.x, r1.x
  74  0x00000BC0:   mul r1.z, r1.x, cb0[37].x
  75  0x00000BE0:   mad r2.w, r4.x, v1.x, l(4.000000)
  76  0x00000C04:   rcp r2.w, r2.w
  77  0x00000C18:   mul r2.w, r2.w, cb0[38].x
  78  0x00000C38:   mul r8.xyz, r4.xyzx, r2.wwww
  79  0x00000C54:   mad r8.xyz, r1.zzzz, r3.xyzx, r8.xyzx
  80  0x00000C78:   mad r1.x, cb0[37].x, r1.x, r2.w
  81  0x00000CA0:   mad r1.z, r5.x, v1.x, l(4.000000)
  82  0x00000CC4:   rcp r1.z, r1.z
  83  0x00000CD8:   mul r2.w, r1.z, cb0[39].x
  84  0x00000CF8:   mad r8.xyz, r2.wwww, r5.xyzx, r8.xyzx
  85  0x00000D1C:   mad r1.x, cb0[39].x, r1.z, r1.x
  86  0x00000D44:   mad r1.z, r6.x, v1.x, l(4.000000)
  87  0x00000D68:   rcp r1.z, r1.z
  88  0x00000D7C:   mul r2.w, r1.z, cb0[40].x
  89  0x00000D9C:   mad r8.xyz, r2.wwww, r6.xyzx, r8.xyzx
  90  0x00000DC0:   mad r1.x, cb0[40].x, r1.z, r1.x
  91  0x00000DE8:   mad r1.z, r7.x, v1.x, l(4.000000)
  92  0x00000E0C:   rcp r1.z, r1.z
  93  0x00000E20:   mul r2.w, r1.z, cb0[41].x
  94  0x00000E40:   mad r8.xyz, r2.wwww, r7.xyzx, r8.xyzx
  95  0x00000E64:   mad r1.x, cb0[41].x, r1.z, r1.x
  96  0x00000E8C:   rcp r1.x, r1.x
  97  0x00000EA0:   mul r2.xyz, r1.xxxx, r8.xyzx
  98  0x00000EBC: endif 
  99  0x00000EC0: min r8.xyz, r4.xyzx, r5.xyzx
 100  0x00000EDC: min r8.xyz, r3.xyzx, r8.xyzx
 101  0x00000EF8: min r9.xyz, r6.xyzx, r7.xyzx
 102  0x00000F14: min r8.xyz, r8.xyzx, r9.xyzx
 103  0x00000F30: max r4.xyz, r4.xyzx, r5.xyzx
 104  0x00000F4C: max r3.xyz, r3.xyzx, r4.xyzx
 105  0x00000F68: max r4.xyz, r6.xyzx, r7.xyzx
 106  0x00000F84: max r3.xyz, r3.xyzx, r4.xyzx
 107  0x00000FA0: mad r0.zw, r0.zzzw, cb0[45].yyyx, cb0[45].wwwz
 108  0x00000FCC: max r0.zw, r0.zzzw, cb0[47].yyyx
 109  0x00000FEC: min r0.zw, r0.zzzw, cb0[47].wwwz
 110  0x0000100C: mad r1.xz, r0.wwzw, cb0[46].xxyx, l(-0.500000, 0.000000, -0.500000, 0.000000)
 111  0x00001040: round_ni r1.xz, r1.xxzx
 112  0x00001054: add r4.xyzw, r1.xzxz, l(0.500000, 0.500000, -0.500000, -0.500000)
 113  0x0000107C: mad r0.zw, r0.zzzw, cb0[46].yyyx, -r4.yyyx
 114  0x000010A8: mul r5.xy, r0.wzww, r0.wzww
 115  0x000010C4: mul r5.zw, r0.wwwz, r5.xxxy
 116  0x000010E0: mad r6.xy, r5.yxyy, r0.zwzz, r0.zwzz
 117  0x00001104: mad r6.xy, -r6.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), r5.yxyy
 118  0x00001138: mul r6.zw, r5.yyyx, l(0.000000, 0.000000, 2.500000, 2.500000)
 119  0x00001160: mad r5.zw, r5.wwwz, l(0.000000, 0.000000, 1.500000, 1.500000), -r6.zzzw
 120  0x00001194: add r5.zw, r5.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
 121  0x000011BC: mad r0.zw, r5.xxxy, r0.wwwz, -r5.xxxy
 122  0x000011E4: mul r5.xy, r0.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
 123  0x0000120C: add r6.zw, -r6.yyyx, l(0.000000, 0.000000, 1.000000, 1.000000)
 124  0x00001238: add r6.zw, -r5.wwwz, r6.zzzw
 125  0x00001258: mad r0.zw, -r0.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000), r6.zzzw
 126  0x0000128C: add r5.zw, r0.wwwz, r5.zzzw
 127  0x000012A8: div r0.zw, r0.zzzw, r5.wwwz
 128  0x000012C4: add r0.zw, r0.zzzw, r4.xxxy
 129  0x000012E0: add r1.xz, r1.xxzx, l(2.500000, 0.000000, 2.500000, 0.000000)
 130  0x00001308: mul r4.xy, r4.wzww, cb0[46].wzww
 131  0x00001328: mul r7.zw, r0.wwwz, cb0[46].wwwz
 132  0x00001348: mul r0.zw, r1.xxxz, cb0[46].zzzw
 133  0x00001368: mul r1.xz, r6.xxyx, r5.wwzw
 134  0x00001384: mul r2.w, r5.z, r5.w
 135  0x000013A0: mul r4.zw, r5.zzzw, r5.xxxy
 136  0x000013BC: add r3.w, r1.z, r1.x
 137  0x000013D8: mad r3.w, r5.w, r5.z, r3.w
 138  0x000013FC: mad r3.w, r5.x, r5.z, r3.w
 139  0x00001420: mad r3.w, r5.y, r5.w, r3.w
 140  0x00001444: div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
 141  0x0000146C: max r7.xy, r4.xyxx, cb0[47].yxyy
 142  0x0000148C: sample_l_indexable(texture2d)(float,float,float,float) r5.xyzw, r7.wxww, t3.xyzw, s3, l(0.000000)
 143  0x000014C0: sample_l_indexable(texture2d)(float,float,float,float) r6.xyzw, r7.yzyy, t3.xyzw, s3, l(0.000000)
 144  0x000014F4: mul r6.xyzw, r1.zzzz, r6.xyzw
 145  0x00001510: mad r5.xyzw, r5.xyzw, r1.xxxx, r6.xyzw
 146  0x00001534: sample_l_indexable(texture2d)(float,float,float,float) r6.xyzw, r7.wzww, t3.xyzw, s3, l(0.000000)
 147  0x00001568: mad r5.xyzw, r6.xyzw, r2.wwww, r5.xyzw
 148  0x0000158C: min r7.xy, r0.zwzz, cb0[47].zwzz
 149  0x000015AC: sample_l_indexable(texture2d)(float,float,float,float) r6.xyzw, r7.xzxx, t3.xyzw, s3, l(0.000000)
 150  0x000015E0: mad r5.xyzw, r6.xyzw, r4.zzzz, r5.xyzw
 151  0x00001604: sample_l_indexable(texture2d)(float,float,float,float) r6.xyzw, r7.wyww, t3.xyzw, s3, l(0.000000)
 152  0x00001638: mad r4.xyzw, r6.xyzw, r4.wwww, r5.xyzw
 153  0x0000165C: mul r4.xyzw, r3.wwww, r4.xyzw
 154  0x00001678: dp3 r5.x, r4.xzyx, l(1.000000, 1.000000, 2.000000, 0.000000)
 155  0x000016A0: dp2 r5.y, r4.xzxx, l(2.000000, -2.000000, 0.000000, 0.000000)
 156  0x000016C8: dp3 r5.z, r4.xzyx, l(-1.000000, -1.000000, 2.000000, 0.000000)
 157  0x000016F0: sample_l_aoffimmi_indexable(0,-1,0)(texture2d)(float,float,float,float) r0.z, r0.xyxx, t2.yzxw, s2, l(0.000000)
 158  0x00001728: lt r0.z, l(0.000000), r0.z
 159  0x00001744: sample_l_aoffimmi_indexable(-1,0,0)(texture2d)(float,float,float,float) r0.w, r0.xyxx, t2.yzwx, s2, l(0.000000)
 160  0x0000177C: lt r0.w, l(0.000000), r0.w
 161  0x00001798: sample_l_indexable(texture2d)(float,float,float,float) r1.x, r0.xyxx, t2.xyzw, s2, l(0.000000)
 162  0x000017CC: lt r1.x, l(0.000000), r1.x
 163  0x000017E8: sample_l_aoffimmi_indexable(1,0,0)(texture2d)(float,float,float,float) r1.z, r0.xyxx, t2.yzxw, s2, l(0.000000)
 164  0x00001820: lt r1.z, l(0.000000), r1.z
 165  0x0000183C: sample_l_aoffimmi_indexable(0,1,0)(texture2d)(float,float,float,float) r0.x, r0.xyxx, t2.xyzw, s2, l(0.000000)
 166  0x00001874: lt r0.x, l(0.000000), r0.x
 167  0x00001890: or r0.y, r0.w, r0.z
 168  0x000018AC: or r0.y, r1.x, r0.y
 169  0x000018C8: or r0.y, r1.z, r0.y
 170  0x000018E4: or r0.x, r0.x, r0.y
 171  0x00001900: not r0.x, r0.x
 172  0x00001914: lt r0.y, l(0.000000), r4.w
 173  0x00001930: and r0.x, r0.y, r0.x
 174  0x0000194C: or r0.x, r0.x, r1.w
 175  0x00001968: max r0.yzw, r8.xxyz, r5.xxyz
 176  0x00001984: min r0.yzw, r3.xxyz, r0.yyzw
 177  0x000019A0: mul r1.y, r1.y, l(0.025000)
 178  0x000019BC: min r1.y, r1.y, l(1.000000)
 179  0x000019D8: add r1.z, -cb0[41].y, l(0.200000)
 180  0x000019FC: mad r1.y, r1.y, r1.z, cb0[41].y
 181  0x00001A24: mul r1.z, r5.x, l(0.010000)
 182  0x00001A40: add r1.w, r2.x, -r5.x
 183  0x00001A60: div_sat r1.z, r1.z, |r1.w|
 184  0x00001A80: max r1.y, r1.z, r1.y
 185  0x00001A9C: movc r0.xyz, r0.xxxx, r2.xyzx, r0.yzwy
 186  0x00001AC0: mad r0.w, r2.x, v1.x, l(4.000000)
 187  0x00001AE4: rcp r0.w, r0.w
 188  0x00001AF8: mad r1.z, r0.x, v1.x, l(4.000000)
 189  0x00001B1C: rcp r1.z, r1.z
 190  0x00001B30: add r1.w, -r1.y, l(1.000000)
 191  0x00001B50: mul r2.w, r1.z, r1.w
 192  0x00001B6C: mul r0.w, r0.w, r1.y
 193  0x00001B88: mad r1.y, r1.w, r1.z, r0.w
 194  0x00001BAC: rcp r1.y, r1.y
 195  0x00001BC0: mul r1.z, r1.y, r2.w
 196  0x00001BDC: mul r0.w, r0.w, r1.y
 197  0x00001BF8: mul r2.xyz, r0.wwww, r2.xyzx
 198  0x00001C14: mad r0.xyz, r0.xyzx, r1.zzzz, r2.xyzx
 199  0x00001C38: mul r1.yzw, r0.xxyz, l(0.000000, 0.250000, 0.250000, 0.250000)
 200  0x00001C60: add r2.yz, r1.zzwz, r1.yyyy
 201  0x00001C7C: mad r2.x, -r0.z, l(0.250000), r2.y
 202  0x00001CA4: mad r0.x, r0.x, l(0.250000), -r1.z
 203  0x00001CCC: mad r2.w, -r0.z, l(0.250000), r0.x
 204  0x00001CF4: min r0.xyz, -r2.xzwx, l(0.000000, 0.000000, 0.000000, 0.000000)
 205  0x00001D20: mov o0.xyz, -r0.xyzx
 206  0x00001D38: and o0.w, r1.x, l(0x3f800000)
 207  0x00001D54: ret 
// Approximately 0 instruction slots used
