//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer SceneBuffer
// {
//
//   float4x4 g_View;                   // Offset:    0 Size:    64 [unused]
//   float4x4 g_Proj;                   // Offset:   64 Size:    64
//   float4x4 g_ViewProjection;         // Offset:  128 Size:    64 [unused]
//   float4x4 g_ViewInverseMatrix;      // Offset:  192 Size:    64 [unused]
//   float4x4 g_PrevView;               // Offset:  256 Size:    64 [unused]
//   float4x4 g_PrevProj;               // Offset:  320 Size:    64 [unused]
//   float4x4 g_PrevViewProjection;     // Offset:  384 Size:    64 [unused]
//   float4x4 g_PrevViewInverseMatrix;  // Offset:  448 Size:    64 [unused]
//   float4 g_ProjectionOffset;         // Offset:  512 Size:    16
//   int g_FrameCount[4];               // Offset:  528 Size:    52 [unused]
//
// }
//
// cbuffer HPixel_Buffer
// {
//
//   float4 g_TargetUvParam;            // Offset:    0 Size:    16
//
// }
//
// cbuffer CamParam_HPixel_Buffer
// {
//
//   float4 g_CameraParam;              // Offset:    0 Size:    16
//   float4 g_CameraVec;                // Offset:   16 Size:    16 [unused]
//   float4 g_CameraParam2;             // Offset:   32 Size:    16 [unused]
//
// }
//
// cbuffer PrecomputeValue_Buffer
// {
//
//   float4 g_TileScaleAndSize;         // Offset:    0 Size:    16
//
// }
//
// Resource bind info for gTileInfo
// {
//
//   struct sTileInfo
//   {
//       
//       float4 tileAABBCenterAndZMin;  // Offset:    0
//       float4 tileAABBSizeAndZMax;    // Offset:   16
//       float4 tileDepthMask;          // Offset:   32
//       float4 tileConeDirAndAngle;    // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// g_LinearZBuffer                   texture  float4          2d             t0      1 
// gTileInfo                             UAV  struct         r/w             u1      1 
// SceneBuffer                       cbuffer      NA          NA            cb0      1 
// PrecomputeValue_Buffer            cbuffer      NA          NA            cb7      1 
// HPixel_Buffer                     cbuffer      NA          NA           cb12      1 
// CamParam_HPixel_Buffer            cbuffer      NA          NA           cb13      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
      0x00000000: cs_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[33], immediateIndexed
      0x0000001C: dcl_constantbuffer CB12[1], immediateIndexed
      0x0000002C: dcl_constantbuffer CB13[1], immediateIndexed
      0x0000003C: dcl_constantbuffer CB7[1], immediateIndexed
      0x0000004C: dcl_resource_texture2d (float,float,float,float) t0
      0x0000005C: dcl_uav_structured u1, 64
      0x0000006C: dcl_input vThreadGroupID.xy
      0x00000074: dcl_input vThreadIDInGroup.xy
      0x0000007C: dcl_input vThreadID.xy
      0x00000084: dcl_temps 11
      0x0000008C: dcl_tgsm_raw g0, 4
      0x0000009C: dcl_tgsm_raw g1, 4
      0x000000AC: dcl_tgsm_raw g2, 4
      0x000000BC: dcl_thread_group 32, 30, 1
   0  0x000000CC: imad r0.x, vThreadIDInGroup.y, l(32), vThreadIDInGroup.x
   1  0x000000E8: mov r1.xy, vThreadID.xyxx
   2  0x000000F8: mov r1.zw, l(0,0,0,0)
   3  0x00000118: ld_indexable(texture2d)(float,float,float,float) r0.y, r1.xyzw, t0.yxzw
   4  0x0000013C: mad r0.y, r0.y, cb13[0].y, cb13[0].x
   5  0x00000168: if_z r0.x
   6  0x00000174:   store_raw g0.x, l(0), l(340282346638528859811704183484516925440.000000)
   7  0x00000190:   store_raw g1.x, l(0), l(0)
   8  0x000001AC:   store_raw g2.x, l(0), l(0)
   9  0x000001C8: endif 
  10  0x000001CC: sync_g_t
  11  0x000001D0: atomic_umin g0, l(0), r0.y
  12  0x000001EC: atomic_umax g1, l(0), r0.y
  13  0x00000208: sync_g_t
  14  0x0000020C: ld_raw r1.x, l(0), g0.xxxx
  15  0x00000228: ld_raw r2.x, l(0), g1.xxxx
  16  0x00000244: mov r3.w, -r1.x
  17  0x0000025C: add r0.z, r2.x, r3.w
  18  0x00000278: add r0.z, r0.z, l(0.000100)
  19  0x00000294: div r0.z, l(32.000000), r0.z
  20  0x000002B0: add r0.y, r0.y, r3.w
  21  0x000002CC: mul r0.y, r0.z, r0.y
  22  0x000002E8: round_ni r0.y, r0.y
  23  0x000002FC: min r0.y, r0.y, l(32.000000)
  24  0x00000318: max r0.y, r0.y, l(0.000000)
  25  0x00000334: ftou r0.y, r0.y
  26  0x00000348: ishl r0.y, l(1), r0.y
  27  0x00000364: atomic_or g2, l(0), r0.y
  28  0x00000380: sync_g_t
  29  0x00000384: if_z r0.x
  30  0x00000390:   ftou r0.x, cb7[0].z
  31  0x000003A8:   imad r0.x, vThreadGroupID.y, r0.x, vThreadGroupID.x
  32  0x000003C4:   utof r0.yz, vThreadGroupID.xxyx
  33  0x000003D4:   mul r0.yz, r0.yyzy, l(0.000000, 32.000000, 30.000000, 0.000000)
  34  0x000003FC:   round_z r2.zw, cb12[0].zzzw
  35  0x00000414:   div r0.yz, r0.yyzy, r2.zzwz
  36  0x00000430:   iadd r4.xy, vThreadGroupID.xyxx, l(1, 1, 0, 0)
  37  0x00000454:   utof r4.xy, r4.xyxx
  38  0x00000468:   mul r4.xy, r4.xyxx, l(32.000000, 30.000000, 0.000000, 0.000000)
  39  0x00000490:   div r2.zw, r4.xxxy, r2.zzzw
  40  0x000004AC:   div r4.y, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[4].x
  41  0x000004D8:   div r4.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[5].y
  42  0x00000504:   mad r4.xw, r0.yyyz, l(2.000000, 0.000000, 0.000000, -2.000000), l(-1.000000, 0.000000, 0.000000, 1.000000)
  43  0x00000540:   add r4.xw, r4.xxxw, cb0[32].xxxy
  44  0x00000560:   mul r5.xy, r1.xxxx, r4.xwxx
  45  0x0000057C:   mul r3.yz, r4.yyzy, r5.xxyx
  46  0x00000598:   mad r5.xy, r2.zwzz, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
  47  0x000005D4:   add r5.xy, r5.xyxx, cb0[32].xyxx
  48  0x000005F4:   mul r5.zw, r1.xxxx, r5.xxxy
  49  0x00000610:   mul r6.yz, r4.yyzy, r5.zzwz
  50  0x0000062C:   dp3 r0.w, r3.yzwy, r3.yzwy
  51  0x00000648:   rsq r0.w, r0.w
  52  0x0000065C:   mul r7.xyz, r0.wwww, r3.yzwy
  53  0x00000678:   mov r6.w, r3.w
  54  0x0000068C:   dp3 r3.x, r6.yzwy, r6.yzwy
  55  0x000006A8:   rsq r3.x, r3.x
  56  0x000006BC:   mul r8.xyz, r3.xxxx, r6.yzwy
  57  0x000006D8:   mad r9.xyz, r3.yzwy, r0.wwww, r8.xyzx
  58  0x000006FC:   dp3 r0.w, r9.xyzx, r9.xyzx
  59  0x00000718:   rsq r0.w, r0.w
  60  0x0000072C:   mul r9.xyz, r0.wwww, r9.xyzx
  61  0x00000748:   dp3 r0.w, r7.xyzx, r9.xyzx
  62  0x00000764:   dp3 r3.x, r8.xyzx, r9.xyzx
  63  0x00000780:   min r9.w, r0.w, r3.x
  64  0x0000079C:   mad r0.w, -r9.w, r9.w, l(1.000000)
  65  0x000007C4:   sqrt r7.z, r0.w
  66  0x000007D8:   mul r4.xw, r2.xxxx, r4.xxxw
  67  0x000007F4:   mul r8.yz, r4.yyzy, r4.xxwx
  68  0x00000810:   mov r8.w, -r2.x
  69  0x00000828:   mul r4.xw, r2.xxxx, r5.xxxy
  70  0x00000844:   mul r5.yz, r4.yyzy, r4.xxwx
  71  0x00000860:   dp3 r0.w, r8.yzwy, r9.xyzx
  72  0x0000087C:   mov r5.w, r8.w
  73  0x00000890:   dp3 r3.x, r5.yzwy, r9.xyzx
  74  0x000008AC:   max r7.y, r0.w, r3.x
  75  0x000008C8:   dp3 r0.w, r3.yzwy, r9.xyzx
  76  0x000008E4:   dp3 r3.x, r6.yzwy, r9.xyzx
  77  0x00000900:   min r7.x, r0.w, r3.x
  78  0x0000091C:   store_structured u1.xyzw, r0.x, l(48), r9.xyzw
  79  0x00000940:   store_structured u1.xyz, r0.x, l(36), r7.xyzx
  80  0x00000964:   mad r7.y, r0.y, l(2.000000), l(-1.000000)
  81  0x00000988:   mad r7.z, r2.w, l(-2.000000), l(1.000000)
  82  0x000009AC:   add r0.yw, r7.yyyz, cb0[32].xxxy
  83  0x000009CC:   mul r4.xw, r1.xxxx, r0.yyyw
  84  0x000009E8:   mul r7.yz, r4.yyzy, r4.xxwx
  85  0x00000A04:   mad r9.y, r2.z, l(2.000000), l(-1.000000)
  86  0x00000A28:   mad r9.z, r0.z, l(-2.000000), l(1.000000)
  87  0x00000A4C:   add r2.zw, r9.yyyz, cb0[32].xxxy
  88  0x00000A6C:   mul r4.xw, r1.xxxx, r2.zzzw
  89  0x00000A88:   mul r9.yz, r4.yyzy, r4.xxwx
  90  0x00000AA4:   mul r0.yz, r2.xxxx, r0.yywy
  91  0x00000AC0:   mul r0.yz, r4.yyzy, r0.yyzy
  92  0x00000ADC:   mul r2.zw, r2.xxxx, r2.zzzw
  93  0x00000AF8:   mul r4.yz, r4.yyzy, r2.zzwz
  94  0x00000B14:   mov r4.w, r5.w
  95  0x00000B28:   min r10.xyz, r5.yzwy, r4.yzwy
  96  0x00000B44:   mov r0.w, r4.w
  97  0x00000B58:   min r10.xyz, r0.yzwy, r10.xyzx
  98  0x00000B74:   min r10.xyz, r8.yzwy, r10.xyzx
  99  0x00000B90:   min r10.xyz, r6.yzwy, r10.xyzx
 100  0x00000BAC:   mov r9.w, r6.w
 101  0x00000BC0:   min r10.xyz, r9.yzwy, r10.xyzx
 102  0x00000BDC:   mov r7.w, r9.w
 103  0x00000BF0:   min r10.xyz, r7.yzwy, r10.xyzx
 104  0x00000C0C:   min r10.xyz, r3.yzwy, r10.xyzx
 105  0x00000C28:   max r4.xyz, r5.yzwy, r4.yzwy
 106  0x00000C44:   max r0.yzw, r0.yyzw, r4.xxyz
 107  0x00000C60:   max r0.yzw, r0.yyzw, r8.yyzw
 108  0x00000C7C:   max r0.yzw, r0.yyzw, r6.yyzw
 109  0x00000C98:   max r0.yzw, r0.yyzw, r9.yyzw
 110  0x00000CB4:   max r0.yzw, r0.yyzw, r7.yyzw
 111  0x00000CD0:   max r0.yzw, r0.yyzw, r3.yyzw
 112  0x00000CEC:   add r3.xyz, r10.xyzx, r0.yzwy
 113  0x00000D08:   mul r3.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
 114  0x00000D30:   add r0.yzw, -r10.xxyz, r0.yyzw
 115  0x00000D50:   mul r1.yzw, r0.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)
 116  0x00000D78:   store_structured u1.xyz, r0.x, l(0), r3.xyzx
 117  0x00000D9C:   store_structured u1.xyzw, r0.x, l(12), r1.xyzw
 118  0x00000DC0:   ld_raw r2.y, l(0), g2.xxxx
 119  0x00000DDC:   store_structured u1.xy, r0.x, l(28), r2.xyxx
 120  0x00000E00: endif 
 121  0x00000E04: ret 
// Approximately 122 instruction slots used
