//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer cbPerFrame
// {
//
//   struct ScbPerFrame
//   {
//       
//       float4 time;                   // Offset:    0
//       float2 _SystemInverseRTDimensions;// Offset:   16
//       float2 _SystemDepthConv;       // Offset:   24
//       float _FlowOrientation;        // Offset:   32
//       float _debug_0;                // Offset:   36
//       float _debug_1;                // Offset:   40
//       float _debug_2;                // Offset:   44
//       float3 CameraPos;              // Offset:   48
//       float g_EmissiveScale;         // Offset:   60
//       float LodScale;                // Offset:   64
//       uint frameCount;               // Offset:   68
//       uint depthPassMode;            // Offset:   72
//       float dummy;                   // Offset:   76
//       float2 WetAmountBlend;         // Offset:   80
//       float2 WetOffset;              // Offset:   88
//       float4 WetRippleWeights;       // Offset:   96
//       float4 WetRippleUVScale;       // Offset:  112
//       float3 WetFlowDirection;       // Offset:  128
//       float WetFlowWeight;           // Offset:  140
//       float WetFlowStretch;          // Offset:  144
//       float WetFlowSpeed;            // Offset:  148
//       float WetFlowNoiseScale;       // Offset:  152
//       float WetFlowNoiseMin;         // Offset:  156
//       float WetRainVolume;           // Offset:  160
//       float WetClock;                // Offset:  164
//       float2 WetFadeStartRangeInv;   // Offset:  168
//       row_major float3x4 RainDepthMapProj;// Offset:  176
//       float4 RainDepthMapZDir;       // Offset:  224
//       float RainDepthMapResolution;  // Offset:  240
//       float RainDepthMapTexelSize;   // Offset:  244
//       int2 DitherOffsetPixel;        // Offset:  248
//       float3 g_LPVCorner1;           // Offset:  256
//       float g_LPVSize1;              // Offset:  268
//       float3 g_LPVCorner2;           // Offset:  272
//       float g_LPVSize2;              // Offset:  284
//       float3 g_LPVCorner3;           // Offset:  288
//       float g_LPVSize3;              // Offset:  300
//       float2 g_StartEndFade1;        // Offset:  304
//       float2 g_StartEndFade2;        // Offset:  312
//       float3 g_CamPos;               // Offset:  320
//       float g_lpvDummy;              // Offset:  332
//       float3 g_ColorScale;           // Offset:  336
//       float g_lpvDummy2;             // Offset:  348
//
//   } cbPerFrame_CB;                   // Offset:    0 Size:   352
//
// }
//
// cbuffer CHR_nhNoctSkin_Material
// {
//
//   struct SCHR_nhNoctSkin_Material
//   {
//       
//       float3 BaseColor0;             // Offset:    0
//       float3 BaseColor1;             // Offset:   16
//       float MultiMask0_Power;        // Offset:   28
//       float3 BaseColor2;             // Offset:   32
//       float MultiMask1_Power;        // Offset:   44
//       float Emissive0_Power;         // Offset:   48
//       float Light_EV;                // Offset:   52
//       float Emissive_EV;             // Offset:   56
//       float3 Emissive0_Color;        // Offset:   64
//       float EmissiveScale_Power;     // Offset:   76
//       float Metallic0_Power;         // Offset:   80
//       float Roughness0_Power;        // Offset:   84
//       float Specular0_Power;         // Offset:   88
//       float3 SSS_HueColor;           // Offset:   96
//       float SSSStrength;             // Offset:  108
//       float Occlusion0_Power;        // Offset:  112
//       float2 mapLM_UVScale;          // Offset:  116
//       float SSAO_Blend;              // Offset:  124
//       int occlusion_set;             // Offset:  128
//       float AlphaThreshold;          // Offset:  132
//       float Fade_Power;              // Offset:  136
//       float AlphaAllFadeInEndDistance;// Offset:  140
//       float AlphaAllFadeInStartDistance;// Offset:  144
//       bool FP_FadePower;             // Offset:  148
//       float Normal1_Power;           // Offset:  152
//       float Normal0_Power;           // Offset:  156
//       float Normal2_Power;           // Offset:  160
//       float2 DirtTextureUVScale;     // Offset:  164
//       float3 DirtTextureColor;       // Offset:  176
//       float SkinDirtAmount_B;        // Offset:  188
//       float2 BloodTextureUVScale;    // Offset:  192
//       float3 BloodTextureColor;      // Offset:  208
//       float SkinBloodAmount_R;       // Offset:  220
//       float SkinBloodAmount_G;       // Offset:  224
//       float SkinBloodAmount_B;       // Offset:  228
//       float SkinBloodAmount_A;       // Offset:  232
//       float SweatAmount;             // Offset:  236
//       float2 Sweat_UVScale;          // Offset:  240
//       float3 StoneColor;             // Offset:  256
//       float2 StoneMap_UVScale;       // Offset:  272
//       float StoneNormal_Power;       // Offset:  280
//       float Stone_Power;             // Offset:  284
//       float Effect0Fazz_length;      // Offset:  288
//       float EffectBiass_length;      // Offset:  292
//       float3 Effect0_Power;          // Offset:  304
//       float WetnessScale;            // Offset:  316
//       float WetnessAbsorbency;       // Offset:  320
//       float MagicDamageMask;         // Offset:  324
//       float MagicDamageAmount;       // Offset:  328
//       float2 MagicDamages_UVScale;   // Offset:  336
//       float AddNormal_Power;         // Offset:  344
//       float VertexColor_MaskControl; // Offset:  348
//       float3 IceColorAdd;            // Offset:  352
//       float IceColorPower;           // Offset:  364
//
//   } CHR_nhNoctSkin_Material_CB;      // Offset:    0 Size:   368
//
// }
//
// cbuffer cbMeshFlags
// {
//
//   struct ScbMeshFlags
//   {
//       
//       bool indoor;                   // Offset:    0
//
//   } cbMeshFlags_CB;                  // Offset:    0 Size:     4
//
// }
//
// cbuffer IView_Combined_cbView
// {
//
//   struct SIView_Combined_cbView
//   {
//       
//       row_major float4x4 Projection; // Offset:    0
//       row_major float4x4 View;       // Offset:   64
//       row_major float4x4 ViewProj;   // Offset:  128
//       row_major float4x4 InvView;    // Offset:  192
//       row_major float4x4 InvProjection;// Offset:  256
//       
//       struct Viewport
//       {
//           
//           int2 TopLeft;              // Offset:  320
//           int2 Size;                 // Offset:  328
//
//       } ViewPort;                    // Offset:  320
//       float3 ViewPoint;              // Offset:  336
//       row_major float4x4 PreviousView;// Offset:  352
//       row_major float4x4 PreviousProj;// Offset:  416
//       row_major float4x4 PreviousViewProj;// Offset:  480
//       row_major float4x4 InvViewProj;// Offset:  544
//       int RenderTargetViewIndex;     // Offset:  608
//       int dummy_0;                   // Offset:  612
//       int dummy_1;                   // Offset:  616
//       int dummy_2;                   // Offset:  620
//       row_major float4x4 ViewProjLS; // Offset:  624
//       row_major float4x4 PreviousViewProjLS;// Offset:  688
//       float3 PreviousViewPoint;      // Offset:  752
//
//   } IView_Combined_cbView_CB;        // Offset:    0 Size:   764
//
// }
//
// Resource bind info for ExposureBuffer_SRV_core
// {
//
//   struct ExposureValues
//   {
//       
//       float exposure_;               // Offset:    0
//       float exposureScale_;          // Offset:    4
//       float maxExposure_;            // Offset:    8
//
//   } $Element;                        // Offset:    0 Size:    12
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Alpha                             sampler      NA          NA             s0      1 
// Basic                             sampler      NA          NA             s1      1 
// BaseColor0_Texture_TEX_Material0_    texture  float4          2d             t0      1 
// BaseColor2_Texture_TEX_Material0_    texture  float4          2d             t1      1 
// BloodTexture_TEX_Material0_       texture  float4          2d             t2      1 
// BloodTexture_Mask_TEX_Material0_    texture  float4          2d             t3      1 
// DirtTexture_TEX_Material0_        texture  float4          2d             t4      1 
// DirtTexture_Mask_TEX_Material0_    texture  float4          2d             t5      1 
// Emissive0_Texture_TEX_Material0_    texture  float4          2d             t6      1 
// LayeredMask0_AlphaTextures_TEX_Material0_    texture  float4     2darray             t7      1 
// LayeredMask0_BaseColorTextures_TEX_Material0_    texture  float4     2darray             t8      1 
// LayeredMask0_SpeculerTextures_TEX_Material0_    texture  float4     2darray             t9      1 
// MRS0_Texture_TEX_Material0_       texture  float4          2d            t10      1 
// MultiMask0_Texture_TEX_Material0_    texture  float4          2d            t11      1 
// MultiMask1_Texture_TEX_Material0_    texture  float4          2d            t12      1 
// Normal0_Texture_TEX_Material0_    texture  float4          2d            t13      1 
// Normal2_Texture_TEX_Material0_    texture  float4          2d            t14      1 
// SSSMask_Texture_TEX_Material0_    texture  float4          2d            t15      1 
// StoneColor_Texture_TEX_Material0_    texture  float4          2d            t16      1 
// StoneNormal_Texture_TEX_Material0_    texture  float4          2d            t17      1 
// Sweat_Textuer_TEX_Material0_      texture  float4          2d            t18      1 
// ExposureBuffer_SRV_core           texture  struct         r/o            t19      1 
// cbPerFrame                        cbuffer      NA          NA            cb0      1 
// CHR_nhNoctSkin_Material           cbuffer      NA          NA            cb1      1 
// cbMeshFlags                       cbuffer      NA          NA            cb2      1 
// IView_Combined_cbView             cbuffer      NA          NA            cb3      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// SEM_BINORMAL_SIGN        0   x           1     NONE   float   x   
// SEM_DEPTH_PS             0    y          1     NONE   float    y  
// SEM_TEXCOORD_UV          0     zw        1     NONE   float     zw
// SEM_COLOR                0   xyzw        2     NONE   float    yz 
// SEM_COLOR                1   xyzw        3     NONE   float   xyzw
// SEM_COLOR                2   xyzw        4     NONE   float       
// SEM_NORMAL_WS            0   xyz         5     NONE   float   xyz 
// SEM_POSITION_WS          0   xyz         6     NONE   float   xyz 
// SEM_PREV_POSITION_XYW_PS     0   xyz         7     NONE   float   xyz 
// SEM_TANGENT_WS           0   xyz         8     NONE   float   xyz 
// SEM_TEXCOORD_UV          1   xy          9     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
// SV_Target                3   xyzw        3   TARGET   float   xyzw
// SV_Target                4   xy          4   TARGET   float   xy  
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[16], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[22], immediateIndexed
      0x0000002C: dcl_constantbuffer CB2[1], immediateIndexed
      0x0000003C: dcl_constantbuffer CB3[22], immediateIndexed
      0x0000004C: dcl_sampler s0, mode_default
      0x00000058: dcl_sampler s1, mode_default
      0x00000064: dcl_resource_texture2d (float,float,float,float) t0
      0x00000074: dcl_resource_texture2d (float,float,float,float) t1
      0x00000084: dcl_resource_texture2d (float,float,float,float) t2
      0x00000094: dcl_resource_texture2d (float,float,float,float) t3
      0x000000A4: dcl_resource_texture2d (float,float,float,float) t4
      0x000000B4: dcl_resource_texture2d (float,float,float,float) t5
      0x000000C4: dcl_resource_texture2d (float,float,float,float) t6
      0x000000D4: dcl_resource_texture2darray (float,float,float,float) t7
      0x000000E4: dcl_resource_texture2darray (float,float,float,float) t8
      0x000000F4: dcl_resource_texture2darray (float,float,float,float) t9
      0x00000104: dcl_resource_texture2d (float,float,float,float) t10
      0x00000114: dcl_resource_texture2d (float,float,float,float) t11
      0x00000124: dcl_resource_texture2d (float,float,float,float) t12
      0x00000134: dcl_resource_texture2d (float,float,float,float) t13
      0x00000144: dcl_resource_texture2d (float,float,float,float) t14
      0x00000154: dcl_resource_texture2d (float,float,float,float) t15
      0x00000164: dcl_resource_texture2d (float,float,float,float) t16
      0x00000174: dcl_resource_texture2d (float,float,float,float) t17
      0x00000184: dcl_resource_texture2d (float,float,float,float) t18
      0x00000194: dcl_resource_structured t19, 12
      0x000001A4: dcl_input_ps_siv linear noperspective v0.xy, position
      0x000001B4: dcl_input_ps linear v1.x
      0x000001C0: dcl_input_ps linear v1.y
      0x000001CC: dcl_input_ps linear v1.zw
      0x000001D8: dcl_input_ps linear v2.yz
      0x000001E4: dcl_input_ps linear v3.xyzw
      0x000001F0: dcl_input_ps linear v5.xyz
      0x000001FC: dcl_input_ps linear v6.xyz
      0x00000208: dcl_input_ps linear v7.xyz
      0x00000214: dcl_input_ps linear v8.xyz
      0x00000220: dcl_input_ps linear v9.xy
      0x0000022C: dcl_output o0.xyzw
      0x00000238: dcl_output o1.xyzw
      0x00000244: dcl_output o2.xyzw
      0x00000250: dcl_output o3.xyzw
      0x0000025C: dcl_output o4.xy
      0x00000268: dcl_temps 7
   0  0x00000270: ftoi r0.xy, v0.xyxx
   1  0x00000284: iadd r0.xy, r0.xyxx, cb0[15].zwzz
   2  0x000002A4: ilt r0.zw, r0.xxxy, l(0, 0, 0, 0)
   3  0x000002CC: itof r0.xy, r0.xyxx
   4  0x000002E0: movc r0.xy, r0.zwzz, v0.xyxx, r0.xyxx
   5  0x00000304: ftoi r0.xy, r0.xyxx
   6  0x00000318: ishr r0.zw, r0.xxxy, l(0, 0, 1, 1)
   7  0x00000340: and r0.xyzw, r0.xyzw, l(1, 1, 1, 1)
   8  0x00000368: xor r1.x, r0.w, r0.z
   9  0x00000384: imul null, r1.xy, r0.zwzz, r1.xxxx
  10  0x000003A4: and r0.z, r0.w, r0.z
  11  0x000003C0: imul null, r1.xy, r1.xyxx, l(2, 3, 0, 0)
  12  0x000003EC: iadd r0.w, r1.y, r1.x
  13  0x00000408: imad r0.z, r0.z, l(1), r0.w
  14  0x0000042C: xor r0.w, r0.y, r0.x
  15  0x00000448: imul null, r1.xy, r0.wwww, r0.xyxx
  16  0x00000468: and r0.x, r0.y, r0.x
  17  0x00000484: imul null, r0.yw, r1.xxxy, l(0, 2, 0, 3)
  18  0x000004B0: iadd r0.y, r0.w, r0.y
  19  0x000004CC: imad r0.x, r0.x, l(1), r0.y
  20  0x000004F0: ishl r0.x, r0.x, l(2)
  21  0x0000050C: iadd r0.x, r0.z, r0.x
  22  0x00000528: add r0.y, cb1[8].w, -cb1[9].x
  23  0x00000550: add r0.z, v1.y, -cb1[9].x
  24  0x00000574: div_sat r0.y, r0.z, r0.y
  25  0x00000590: movc r0.y, cb1[9].y, r0.y, cb1[8].z
  26  0x000005BC: mul r0.y, r0.y, l(16.000000)
  27  0x000005D8: round_ne r0.y, r0.y
  28  0x000005EC: ftou r0.y, r0.y
  29  0x00000600: ult r0.x, r0.x, r0.y
  30  0x0000061C: discard_z r0.x
  31  0x00000628: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r0.xyz, v1.zwzz, t6.xyzw, s1
  32  0x00000658: add r1.xyz, r0.xyzx, l(0.055000, 0.055000, 0.055000, 0.000000)
  33  0x00000680: mul r1.xyz, r1.xyzx, l(0.947867, 0.947867, 0.947867, 0.000000)
  34  0x000006A8: log r1.xyz, r1.xyzx
  35  0x000006BC: mul r1.xyz, r1.xyzx, l(2.400000, 2.400000, 2.400000, 0.000000)
  36  0x000006E4: exp r1.xyz, r1.xyzx
  37  0x000006F8: mad r1.xyz, -r0.xyzx, l(0.077399, 0.077399, 0.077399, 0.000000), r1.xyzx
  38  0x0000072C: ge r2.xyz, r0.xyzx, l(0.039280, 0.039280, 0.039280, 0.000000)
  39  0x00000754: mul r0.xyz, r0.xyzx, l(0.077399, 0.077399, 0.077399, 0.000000)
  40  0x0000077C: and r2.xyz, r2.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
  41  0x000007A4: mad r0.xyz, r2.xyzx, r1.xyzx, r0.xyzx
  42  0x000007C8: mul r0.xyz, r0.xyzx, cb1[4].xyzx
  43  0x000007E8: exp r1.xy, cb1[3].zyzz
  44  0x00000800: mul r0.xyz, r0.xyzx, r1.xxxx
  45  0x0000081C: mul r0.xyz, r0.xyzx, cb1[3].xxxx
  46  0x0000083C: mul r0.xyz, r1.yyyy, r0.xyzx
  47  0x00000858: ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r0.w, l(0), l(4), t19.xxxx
  48  0x00000884: add r1.x, -r0.w, l(1.000000)
  49  0x000008A4: mad r1.x, cb1[4].w, r1.x, r0.w
  50  0x000008CC: div r0.xyz, r0.xyzx, r1.xxxx
  51  0x000008E8: add r1.xyz, -v6.xyzx, cb3[21].xyzx
  52  0x0000090C: dp3 r1.w, r1.xyzx, r1.xyzx
  53  0x00000928: rsq r1.w, r1.w
  54  0x0000093C: mul r1.xyz, r1.wwww, r1.xyzx
  55  0x00000958: dp3 r1.x, v5.xyzx, r1.xyzx
  56  0x00000974: add r1.x, -|r1.x|, cb1[18].y
  57  0x00000998: min r1.x, |r1.x|, l(1.000000)
  58  0x000009B8: log r1.x, r1.x
  59  0x000009CC: mul r1.x, r1.x, cb1[18].x
  60  0x000009EC: exp r1.x, r1.x
  61  0x00000A00: min r1.x, r1.x, l(1.000000)
  62  0x00000A1C: add r1.x, -r1.x, l(1.000000)
  63  0x00000A3C: add r1.x, -r1.x, l(1.000000)
  64  0x00000A5C: mul r1.xyz, r1.xxxx, cb1[19].xyzx
  65  0x00000A7C: div r1.xyz, r1.xyzx, r0.wwww
  66  0x00000A98: add r0.xyz, r0.xyzx, r1.xyzx
  67  0x00000AB4: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r1.x, v1.zwzz, t12.xyzw, s1
  68  0x00000AE4: add r1.y, -cb1[2].w, l(1.000000)
  69  0x00000B08: add r1.x, -r1.y, r1.x
  70  0x00000B28: mul_sat r1.x, r1.x, l(-2.857143)
  71  0x00000B44: mul r1.y, r1.x, r1.x
  72  0x00000B60: mad r1.x, -r1.x, l(2.000000), l(3.000000)
  73  0x00000B88: mad r1.x, -r1.y, r1.x, l(1.000000)
  74  0x00000BB0: max r1.x, r1.x, l(0.000000)
  75  0x00000BCC: mul r0.xyz, r0.xyzx, r1.xxxx
  76  0x00000BE8: mul o0.xyz, r0.wwww, r0.xyzx
  77  0x00000C04: mov o0.w, l(0)
  78  0x00000C18: mul r0.xyz, v5.zxyz, v8.yzxy
  79  0x00000C34: mad r0.xyz, v5.yzxy, v8.zxyz, -r0.xyzx
  80  0x00000C5C: mul r0.xyz, r0.xyzx, v1.xxxx
  81  0x00000C78: dp3 r0.w, r0.xyzx, r0.xyzx
  82  0x00000C94: rsq r0.w, r0.w
  83  0x00000CA8: mul r0.xyz, r0.wwww, r0.xyzx
  84  0x00000CC4: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r1.yz, v1.zwzz, t14.zxyw, s1
  85  0x00000CF4: mad r1.yz, r1.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
  86  0x00000D30: mul r1.yz, r1.yyzy, cb1[10].xxxx
  87  0x00000D50: mul r1.yz, r1.xxxx, r1.yyzy
  88  0x00000D6C: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r2.xy, v1.zwzz, t13.xyzw, s1
  89  0x00000D9C: mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  90  0x00000DD8: mad r1.yz, r2.xxyx, cb1[9].wwww, r1.yyzy
  91  0x00000E00: mul r2.xy, v1.zwzz, cb1[17].xyxx
  92  0x00000E20: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r2.xy, r2.xyxx, t17.xyzw, s1
  93  0x00000E50: mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
  94  0x00000E8C: mul r2.xy, r2.xyxx, cb1[17].zzzz
  95  0x00000EAC: mad r2.xy, r2.xyxx, cb1[17].wwww, -r1.yzyy
  96  0x00000ED8: mad r1.yz, cb1[17].wwww, r2.xxyx, r1.yyzy
  97  0x00000F00: mul r0.xyz, r0.xyzx, r1.zzzz
  98  0x00000F1C: mad r0.xyz, r1.yyyy, v8.xyzx, r0.xyzx
  99  0x00000F40: mad r0.w, -r1.y, r1.y, l(1.000000)
 100  0x00000F68: mad r0.w, -r1.z, r1.z, r0.w
 101  0x00000F90: max r0.w, r0.w, l(0.000000)
 102  0x00000FAC: sqrt r0.w, r0.w
 103  0x00000FC0: mad r0.xyz, r0.wwww, v5.xyzx, r0.xyzx
 104  0x00000FE4: dp3 r0.w, r0.xyzx, r0.xyzx
 105  0x00001000: rsq r0.w, r0.w
 106  0x00001014: mul r0.xyz, r0.wwww, r0.xyzx
 107  0x00001030: add r0.w, |r0.y|, |r0.x|
 108  0x00001054: add r0.w, |r0.z|, r0.w
 109  0x00001074: div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
 110  0x0000109C: mul r0.xy, r0.wwww, r0.xyxx
 111  0x000010B8: lt r0.z, r0.z, l(0.000000)
 112  0x000010D4: ge r1.yz, r0.xxyx, l(0.000000, 0.000000, 0.000000, 0.000000)
 113  0x000010FC: movc r1.yz, r1.yyzy, l(0,1,1,0), l(0,-1,-1,0)
 114  0x00001138: itof r1.yz, r1.yyzy
 115  0x0000114C: add r2.xy, -|r0.yxyy|, l(1.000000, 1.000000, 0.000000, 0.000000)
 116  0x00001178: mul r1.yz, r1.yyzy, r2.xxyx
 117  0x00001194: movc r0.xy, r0.zzzz, r1.yzyy, r0.xyxx
 118  0x000011B8: mad_sat r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
 119  0x000011F4: mul r0.xy, r0.xyxx, l(4095.000000, 4095.000000, 0.000000, 0.000000)
 120  0x0000121C: round_ne r0.xy, r0.xyxx
 121  0x00001230: mul r0.xz, r0.xxyx, l(0.062500, 0.000000, 0.003906, 0.000000)
 122  0x00001258: frc r0.w, r0.x
 123  0x0000126C: round_ni r2.xy, r0.zxzz
 124  0x00001280: mad r0.x, r0.w, l(256.000000), r2.x
 125  0x000012A4: round_ni r2.z, r0.x
 126  0x000012B8: mad r2.w, -r2.x, l(256.000000), r0.y
 127  0x000012E0: mul o1.xyz, r2.yzwy, l(0.003922, 0.003922, 0.003922, 0.000000)
 128  0x00001308: mul r0.xy, v1.zwzz, cb1[21].xyxx
 129  0x00001328: ge r1.yz, l(0.000000, 0.000000, 0.000000, 0.000000), r0.xxyx
 130  0x00001350: and r1.yz, r1.yyzy, l(0, 0x3f800000, 0x3f800000, 0)
 131  0x00001378: round_ni r2.xy, r0.xyxx
 132  0x0000138C: mad r1.yz, r2.xxyx, l(0.000000, 7.000000, 4.000000, 0.000000), r1.yyzy
 133  0x000013BC: add r0.w, r1.z, r1.y
 134  0x000013D8: mul r0.w, r0.w, l(0.058824)
 135  0x000013F4: ge r1.y, r0.w, -r0.w
 136  0x00001414: frc r0.w, |r0.w|
 137  0x0000142C: movc r0.w, r1.y, r0.w, -r0.w
 138  0x00001454: ge r1.yzw, r0.wwww, l(0.000000, 0.294118, 0.764706, 0.529412)
 139  0x0000147C: and r1.yzw, r1.yyzw, l(0, 0x3f800000, 0x3f800000, 0x3f800000)
 140  0x000014A4: mov r0.z, l(-1.000000)
 141  0x000014B8: sample_aoffimmi_indexable(0,0,0)(texture2darray)(float,float,float,float) r2.xyzw, r0.xyzx, t7.xyzw, s0
 142  0x000014E8: add r2.yw, -r2.xxxz, r2.yyyw
 143  0x00001508: mad r1.yz, r1.yyzy, r2.yywy, r2.xxzx
 144  0x0000152C: add r0.w, -r1.y, r1.z
 145  0x0000154C: mad r0.w, r1.w, r0.w, r1.y
 146  0x00001570: add r1.y, -cb1[20].z, l(1.000000)
 147  0x00001594: add r0.w, r0.w, -r1.y
 148  0x000015B4: mul_sat r0.w, r0.w, l(-4.000000)
 149  0x000015D0: mul r1.z, r0.w, r0.w
 150  0x000015EC: mad r0.w, -r0.w, l(2.000000), l(3.000000)
 151  0x00001614: mad r0.w, -r1.z, r0.w, l(1.000000)
 152  0x0000163C: max r0.w, r0.w, l(0.000000)
 153  0x00001658: add r1.zw, -cb1[21].wwwz, l(0.000000, 0.000000, 0.000000, 1.000000)
 154  0x00001688: div_sat r1.y, -r1.y, r1.z
 155  0x000016A8: mul_sat r1.z, r1.w, l(10.000000)
 156  0x000016C4: mul r1.w, r1.y, r1.y
 157  0x000016E0: mad r1.y, -r1.y, l(2.000000), l(3.000000)
 158  0x00001708: mad r1.y, -r1.w, r1.y, l(1.000000)
 159  0x00001730: max r1.y, r1.y, l(0.000000)
 160  0x0000174C: mul r1.w, r0.w, r1.y
 161  0x00001768: mul r2.xy, v1.wzww, cb1[12].yxyy
 162  0x00001788: ge r2.zw, l(0.000000, 0.000000, 0.000000, 0.000000), r2.yyyx
 163  0x000017B0: and r2.zw, r2.zzzw, l(0, 0, 0x3f800000, 0x3f800000)
 164  0x000017D8: round_ni r3.xy, r2.yxyy
 165  0x000017EC: mad r3.xy, r3.xyxx, l(7.000000, 4.000000, 0.000000, 0.000000), r2.zwzz
 166  0x0000181C: add r3.x, r3.y, r3.x
 167  0x00001838: mul r3.x, r3.x, l(0.058824)
 168  0x00001854: ge r3.y, r3.x, -r3.x
 169  0x00001874: frc r3.x, |r3.x|
 170  0x0000188C: movc r3.x, r3.y, r3.x, -r3.x
 171  0x000018B4: ge r3.xyz, r3.xxxx, l(0.294118, 0.764706, 0.529412, 0.000000)
 172  0x000018DC: and r3.xyz, r3.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
 173  0x00001904: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r4.xyzw, r2.yxyy, t3.xyzw, s1
 174  0x00001934: add r4.yw, -r4.xxxz, r4.yyyw
 175  0x00001954: mad r3.xy, r3.xyxx, r4.ywyy, r4.xzxx
 176  0x00001978: add r3.y, -r3.x, r3.y
 177  0x00001998: mad r3.x, r3.z, r3.y, r3.x
 178  0x000019BC: add r3.y, -r3.x, l(1.000000)
 179  0x000019DC: mul r3.zw, v1.wwwz, cb1[10].zzzy
 180  0x000019FC: ge r4.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r3.wzww
 181  0x00001A24: and r4.xy, r4.xyxx, l(0x3f800000, 0x3f800000, 0, 0)
 182  0x00001A4C: round_ni r4.zw, r3.wwwz
 183  0x00001A60: mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 7.000000, 4.000000), r4.xxxy
 184  0x00001A90: add r4.z, r4.w, r4.z
 185  0x00001AAC: mul r4.z, r4.z, l(0.058824)
 186  0x00001AC8: ge r4.w, r4.z, -r4.z
 187  0x00001AE8: frc r4.z, |r4.z|
 188  0x00001B00: movc r4.z, r4.w, r4.z, -r4.z
 189  0x00001B28: ge r5.xyz, r4.zzzz, l(0.294118, 0.764706, 0.529412, 0.000000)
 190  0x00001B50: and r5.xyz, r5.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
 191  0x00001B78: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r6.xyzw, r3.wzww, t5.xyzw, s1
 192  0x00001BA8: add r4.zw, -r6.xxxz, r6.yyyw
 193  0x00001BC8: mad r4.zw, r5.xxxy, r4.zzzw, r6.xxxz
 194  0x00001BEC: add r4.w, -r4.z, r4.w
 195  0x00001C0C: mad r4.z, r5.z, r4.w, r4.z
 196  0x00001C30: dp4 r4.w, v2.zzzz, cb1[11].wwww
 197  0x00001C50: mad r5.x, r4.w, r4.z, l(1.000000)
 198  0x00001C74: add r3.y, r3.y, -r5.x
 199  0x00001C94: mov r6.x, cb1[13].w
 200  0x00001CAC: mov r6.yzw, cb1[14].xxyz
 201  0x00001CC4: dp4 r5.y, v3.xyzw, r6.xyzw
 202  0x00001CE0: mul r3.x, r3.x, r5.y
 203  0x00001CFC: mad r3.y, r3.x, r3.y, r5.x
 204  0x00001D20: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r5.xy, v1.zwzz, t10.yzxw, s1
 205  0x00001D50: mul r5.xz, r5.xxyx, cb1[5].yyzy
 206  0x00001D70: mul r5.w, r3.y, r5.x
 207  0x00001D8C: mul r6.xy, v1.zwzz, cb1[15].xyxx
 208  0x00001DAC: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r6.x, r6.xyxx, t18.xyzw, s1
 209  0x00001DDC: dp4 r6.y, v2.yyyy, cb1[14].wwww
 210  0x00001DFC: mad r6.z, -r6.y, r6.x, l(1.000000)
 211  0x00001E24: mul r6.x, r6.x, r6.y
 212  0x00001E40: mad r3.y, -r5.x, r3.y, r6.z
 213  0x00001E68: mad r3.y, r6.x, r3.y, r5.w
 214  0x00001E8C: sample_aoffimmi_indexable(0,0,0)(texture2darray)(float,float,float,float) r5.x, r0.xyzx, t9.xyzw, s1
 215  0x00001EBC: sample_aoffimmi_indexable(0,0,0)(texture2darray)(float,float,float,float) r0.xyz, r0.xyzx, t8.xyzw, s1
 216  0x00001EEC: add r5.w, -r5.x, l(1.000000)
 217  0x00001F0C: mad r5.x, -cb1[5].z, r5.y, r5.x
 218  0x00001F38: mad_sat r5.x, r1.w, r5.x, r5.z
 219  0x00001F5C: add r5.y, -r3.y, r5.w
 220  0x00001F7C: mad r1.w, r1.w, r5.y, r3.y
 221  0x00001FA0: add r5.yz, -cb1[17].wwww, l(0.000000, 1.000000, 1.400000, 0.000000)
 222  0x00001FD0: mad r3.y, r1.w, r5.z, -r1.w
 223  0x00001FF8: mad o1.w, cb1[17].w, r3.y, r1.w
 224  0x00002020: mul r1.w, r5.y, cb1[6].w
 225  0x00002040: round_ni r5.yz, |r3.wwzw|
 226  0x00002058: mad r4.xy, r5.yzyy, l(11.000000, 7.000000, 0.000000, 0.000000), r4.xyxx
 227  0x00002088: add r3.y, r4.y, r4.x
 228  0x000020A4: mul r3.y, r3.y, l(0.058824)
 229  0x000020C0: ge r4.x, r3.y, -r3.y
 230  0x000020E0: frc r3.y, r3.y
 231  0x000020F4: movc r3.y, r4.x, r3.y, -r3.y
 232  0x0000211C: ge r4.x, l(0.529412), r3.y
 233  0x00002138: and r4.xy, r4.xxxx, l(0x3f800000, 0x41000000, 0, 0)
 234  0x00002160: mad r5.yz, v1.zzwz, cb1[10].yyzy, -r3.zzwz
 235  0x0000218C: mad r3.zw, r4.xxxx, r5.yyyz, r3.zzzw
 236  0x000021B0: mad r3.y, r3.y, l(17.000000), r4.y
 237  0x000021D4: add r4.xy, r3.zwzz, r3.zwzz
 238  0x000021F0: ge r5.y, l(13.000000), r3.y
 239  0x0000220C: and r5.yz, r5.yyyy, l(0, 0x3f800000, 0x40800000, 0)
 240  0x00002234: add r3.y, r3.y, r5.z
 241  0x00002250: mad r6.x, r5.y, r4.x, -r3.z
 242  0x00002278: ge r3.y, l(15.000000), r3.y
 243  0x00002294: and r3.y, r3.y, l(0x3f800000)
 244  0x000022B0: mad r6.y, r3.y, r4.y, -r3.w
 245  0x000022D8: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r3.yzw, r6.xyxx, t4.wxyz, s1
 246  0x00002308: mul r3.yzw, r3.yyzw, cb1[11].xxyz
 247  0x00002328: round_ni r4.xy, |r2.yxyy|
 248  0x00002340: mad r2.zw, r4.xxxy, l(0.000000, 0.000000, 11.000000, 7.000000), r2.zzzw
 249  0x00002370: add r2.z, r2.w, r2.z
 250  0x0000238C: mul r2.z, r2.z, l(0.058824)
 251  0x000023A8: ge r2.w, r2.z, -r2.z
 252  0x000023C8: frc r2.z, r2.z
 253  0x000023DC: movc r2.z, r2.w, r2.z, -r2.z
 254  0x00002404: ge r2.w, l(0.529412), r2.z
 255  0x00002420: and r4.xy, r2.wwww, l(0x3f800000, 0x41000000, 0, 0)
 256  0x00002448: mad r5.yz, v1.zzwz, cb1[12].xxyx, -r2.xxyx
 257  0x00002474: mad r2.xy, r4.xxxx, r5.yzyy, r2.xyxx
 258  0x00002498: mad r2.z, r2.z, l(17.000000), r4.y
 259  0x000024BC: add r4.xy, r2.xyxx, r2.xyxx
 260  0x000024D8: ge r2.w, l(13.000000), r2.z
 261  0x000024F4: and r5.yz, r2.wwww, l(0, 0x3f800000, 0x40800000, 0)
 262  0x0000251C: add r2.z, r2.z, r5.z
 263  0x00002538: mad r6.x, r5.y, r4.x, -r2.x
 264  0x00002560: ge r2.x, l(15.000000), r2.z
 265  0x0000257C: and r2.x, r2.x, l(0x3f800000)
 266  0x00002598: mad r6.y, r2.x, r4.y, -r2.y
 267  0x000025C0: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r2.xyz, r6.xyxx, t2.xyzw, s1
 268  0x000025F0: mul r2.xyz, r2.xyzx, cb1[13].xyzx
 269  0x00002610: mov_sat r2.w, r3.x
 270  0x00002624: mul r2.xyz, r2.wwww, r2.xyzx
 271  0x00002640: mad_sat r2.w, r4.w, r4.z, -r3.x
 272  0x00002668: mul r4.x, r4.z, r4.w
 273  0x00002684: max r3.x, r3.x, r4.x
 274  0x000026A0: add_sat r3.x, -r3.x, l(1.000000)
 275  0x000026C0: mad r2.xyz, r3.yzwy, r2.wwww, r2.xyzx
 276  0x000026E4: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r3.yzw, v9.xyxx, t11.wxyz, s1
 277  0x00002714: mul r3.yzw, r3.yyzw, cb1[1].wwww
 278  0x00002734: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r4.xyz, v1.zwzz, t0.xyzw, s1
 279  0x00002764: mul r5.yzw, r4.xxyz, cb1[0].xxyz
 280  0x00002784: mad r4.xyz, -cb1[0].xyzx, r4.xyzx, cb1[1].xyzx
 281  0x000027B4: mad r3.yzw, r3.yyzw, r4.xxyz, r5.yyzw
 282  0x000027D8: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r4.xyz, v1.zwzz, t1.xyzw, s1
 283  0x00002808: mad r4.xyz, cb1[2].xyzx, r4.xyzx, -r3.yzwy
 284  0x00002834: mad r3.yzw, r1.xxxx, r4.xxyz, r3.yyzw
 285  0x00002858: mad r2.xyz, r3.yzwy, r3.xxxx, r2.xyzx
 286  0x0000287C: max r1.x, cb1[19].y, cb1[19].x
 287  0x000028A0: max r1.x, r1.x, cb1[19].z
 288  0x000028C0: mul r3.xyz, r1.xxxx, r2.xyzx
 289  0x000028DC: mad r2.xyz, r3.xyzx, l(-0.800000, -0.800000, -0.800000, 0.000000), r2.xyzx
 290  0x0000290C: add r0.xyz, r0.xyzx, -r2.xyzx
 291  0x0000292C: mul r1.x, r1.z, r1.z
 292  0x00002948: mad r1.z, -r1.z, l(2.000000), l(3.000000)
 293  0x00002970: mad r1.x, -r1.x, r1.z, l(1.000000)
 294  0x00002998: max r1.x, r1.x, l(0.000000)
 295  0x000029B4: mad r0.w, r0.w, r1.y, r1.x
 296  0x000029D8: mad r0.xyz, r0.wwww, r0.xyzx, r2.xyzx
 297  0x000029FC: mul r1.xy, v9.xyxx, cb1[17].xyxx
 298  0x00002A1C: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t16.xyzw, s1
 299  0x00002A4C: mad r1.xyz, cb1[16].xyzx, r1.xyzx, -r0.xyzx
 300  0x00002A78: mad o2.xyz, cb1[17].wwww, r1.xyzx, r0.xyzx
 301  0x00002AA0: mov o2.w, l(1.000000)
 302  0x00002AB4: sample_aoffimmi_indexable(0,0,0)(texture2d)(float,float,float,float) r0.x, v9.xyxx, t15.xyzw, s1
 303  0x00002AE4: mul r0.x, r1.w, r0.x
 304  0x00002B00: max o3.z, r0.x, l(0.004000)
 305  0x00002B1C: movc r0.x, cb2[0].x, l(0.501961), l(0)
 306  0x00002B44: mad o3.w, r5.x, l(0.498039), r0.x
 307  0x00002B68: min r0.x, cb1[6].y, cb1[6].x
 308  0x00002B8C: min r0.x, r0.x, cb1[6].z
 309  0x00002BAC: max r0.y, cb1[6].y, cb1[6].x
 310  0x00002BD0: max r0.y, r0.y, cb1[6].z
 311  0x00002BF0: add r0.x, -r0.x, r0.y
 312  0x00002C10: max r0.x, r0.x, l(0.000100)
 313  0x00002C2C: add r1.xyz, r0.yyyy, -cb1[6].yzxy
 314  0x00002C50: eq r0.yz, r0.yyyy, cb1[6].xxyx
 315  0x00002C70: div r1.xyz, r1.xyzx, r0.xxxx
 316  0x00002C8C: add r0.xw, r1.zzzx, l(2.000000, 0.000000, 0.000000, 4.000000)
 317  0x00002CB4: add r0.xw, -r1.yyyz, r0.xxxw
 318  0x00002CD4: add r1.x, -r1.x, r1.y
 319  0x00002CF4: movc r0.x, r0.z, r0.x, r0.w
 320  0x00002D18: movc r0.x, r0.y, r1.x, r0.x
 321  0x00002D3C: mul r0.y, r0.x, l(0.166667)
 322  0x00002D58: lt r0.z, r0.x, l(0.000000)
 323  0x00002D74: mad r0.x, r0.x, l(0.166667), l(1.000000)
 324  0x00002D98: movc o3.x, r0.z, r0.x, r0.y
 325  0x00002DBC: mov o3.y, l(0)
 326  0x00002DD0: mul r0.xy, v7.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000)
 327  0x00002DF8: div r0.xy, r0.xyxx, v7.zzzz
 328  0x00002E14: add r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
 329  0x00002E3C: mad o4.xy, -v0.xyxx, cb0[1].xyxx, r0.xyxx
 330  0x00002E68: ret 
// Approximately 331 instruction slots used
