//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                11   xyzw        1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// SV_IsFrontFace           0   x           3    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_DepthLessEqual        0    N/A oDepthLE  DEPTHLE   float    YES
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[152], immediateIndexed
      0x0000001C: dcl_constantbuffer CB1[10], immediateIndexed
      0x0000002C: dcl_sampler s0, mode_default
      0x00000038: dcl_resource_texture2d (float,float,float,float) t0
      0x00000048: dcl_input_ps_siv linear noperspective centroid v0.xyzw, position
      0x00000058: dcl_input_ps linear centroid v1.xyz
      0x00000064: dcl_input_ps linear v2.xy
      0x00000070: dcl_output o0.xyzw
      0x0000007C: dcl_output oDepthLE
      0x00000084: dcl_temps 2
   0  0x0000008C: mad r0.x, v0.y, l(2.000000), v0.x
   1  0x000000B0: add r0.x, r0.x, cb0[151].x
   2  0x000000D0: add r0.x, r0.x, l(-1.500000)
   3  0x000000EC: mul r0.x, r0.x, l(0.200000)
   4  0x00000108: dp2 r0.y, l(2.408451, 3.253521, 0.000000, 0.000000), v0.xyxx
   5  0x00000130: frc r0.xy, r0.xyxx
   6  0x00000144: mad r0.x, r0.x, l(5.000000), r0.y
   7  0x00000168: mul r0.x, r0.x, l(0.166667)
   8  0x00000184: mul r1.xyzw, v0.yyyy, cb0[45].xyzw
   9  0x000001A4: mad r1.xyzw, v0.xxxx, cb0[44].xyzw, r1.xyzw
  10  0x000001CC: mad r1.xyzw, v0.zzzz, cb0[46].xyzw, r1.xyzw
  11  0x000001F4: add r1.xyzw, r1.xyzw, cb0[47].xyzw
  12  0x00000214: div r0.yzw, r1.xxyz, r1.wwww
  13  0x00000230: dp3 r1.x, -r0.yzwy, -r0.yzwy
  14  0x00000254: rsq r1.x, r1.x
  15  0x00000268: mul r0.yzw, -r0.yyzw, r1.xxxx
  16  0x00000288: dp3 r0.y, r0.yzwy, v1.xyzx
  17  0x000002A4: mul r0.y, |r0.y|, l(1.500000)
  18  0x000002C4: add r0.z, -cb1[9].z, cb1[9].y
  19  0x000002EC: mad_sat r0.y, r0.y, r0.z, cb1[9].z
  20  0x00000314: mov r1.y, l(1.000000)
  21  0x00000328: mad r0.z, r1.y, v0.w, l(-350.000000)
  22  0x0000034C: mul_sat r0.z, r0.z, l(0.001111)
  23  0x00000368: add r0.w, -cb1[8].w, l(3.000000)
  24  0x0000038C: mad r0.z, r0.z, r0.w, cb1[8].w
  25  0x000003B4: add r0.w, -r0.z, l(1.000000)
  26  0x000003D4: mad r0.y, r0.y, r0.w, r0.z
  27  0x000003F8: sample_b_indexable(texture2d)(float,float,float,float) r0.zw, v2.xyxx, t0.xyzw, s0, cb1[7].x
  28  0x00000430: max r1.z, r0.z, l(0.000001)
  29  0x0000044C: mul r1.w, r1.z, r1.z
  30  0x00000468: mad r1.z, -r1.z, r1.z, l(1.000000)
  31  0x00000490: mad r0.y, r0.y, r1.z, r1.w
  32  0x000004B4: mad r0.x, r0.y, r0.w, r0.x
  33  0x000004D8: add r0.y, -r0.z, l(0.500000)
  34  0x000004F8: add r0.x, r0.x, l(-0.833300)
  35  0x00000514: lt r0.x, r0.x, l(0.000000)
  36  0x00000530: discard_nz r0.x
  37  0x0000053C: mov r1.x, v0.z
  38  0x00000550: mul r0.xz, r1.xxyx, v0.wwww
  39  0x0000056C: mad r0.y, r0.y, cb1[9].w, r0.z
  40  0x00000594: div r0.x, r0.x, r0.y
  41  0x000005B0: min r0.x, r0.x, v0.z
  42  0x000005CC: movc oDepthLE, cb0[143].w, v0.z, r0.x
  43  0x000005F0: mov o0.xyzw, l(0,0,0,0)
  44  0x00000610: ret 
// Approximately 0 instruction slots used